### PR TITLE
Fixed a spelling mistake

### PR DESCRIPTION
**Pull request by nawalhmw**
Changed the comment: "Create an store the VideoPlayerController. The VideoPlayerController" to "Create and store the VideoPlayerController. The VideoPlayerController"

### CODE REVIEW

**Comment by nawalhmw** [comment]
@googlebot I signed it!

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Comment by sfshaza2** [comment]
This didn't break the build. Forcing a merge.

**Comment by RedBrogdon** [comment]
This did actually break the build (though it may already have been broken for another reason). Because the error was in a code excerpt sourced from one of the projects in /examples, fixing the excerpt rather than the underlying code caused a mismatch, which the tests will detect (and ask you to run /tool/refresh_code_excerpts.sh to fix).

It's not a huge deal, but definitely something to bear in mind when one of the excerpts needs a fix.

**Comment by sfshaza2** [comment]
Ah,I must be more careful.

**Pull request merged**
