### PR TITLE
Tweaking text.

### PR DESCRIPTION
**Pull request by Sfshaza**
Please review. Am not entirely sure of timing.

@filiph @mit-mit

### CODE REVIEW

**Comment by Sfshaza** [comment]
Feel free to ignore...

**Comment by mit-mit** [comment]
cc @filiph were you doing this? We also need to update the `git clone` instruction

**Comment by Sfshaza** [comment]
I think he is, but I didn't see the PR so I put this here as a backup. I forgot about the flag. Also, I can't figure out where the docs landing page is linked to.  flutter.io/docs/

**Comment by Sfshaza** [comment]
Yes, Martin confirmed that @filiph is handling this at 6am.

**Comment by maguinis** [comment]
Yes, confirmed.

**Comment by filiph** [comment]
Yes, this was handled by me, and the `-b beta` as well.

**Pull request closed without merging**
