### PR TITLE
Tutorial layout and image debigification

### PR DESCRIPTION
**Pull request by sethladd**
* fixes a layout bug on wide screens
* shrinks first image on layout tutorial
* optimize all PNGs across website

### CODE REVIEW

**Comment by sethladd** [comment]
TBR @mit-mit

**Comment by mit-mit** [comment]
The image on the layout tutorial still appears to be super big!?
https://flutter-io-deploy-three.firebaseapp.com/tutorials/layout/

image

**Comment by mit-mit** [comment]
@sethladd travis is failing after this PR:

https://travis-ci.org/flutter/website/builds/226718731

```
Analyzing /home/travis/build/flutter/website/_includes/_code/container/main.dart...
  warning • The named parameter 'backgroundColor' isn't defined at _includes/_code/container/main.dart:41:9 • undefined_named_parameter
1 issue found.
(Ran in 5.6s)
```

**Comment by mit-mit** [comment]
Sorry, breaking change is unrelated to your change, fixing in https://github.com/flutter/website/pull/530

**Comment by sethladd** [comment]
The image used to be way way bigger :)

**Pull request merged**
