### PR TITLE
Remove unnecessary null safety query parameters from DartPads

### PR DESCRIPTION
**Pull request by parlough**
DartPad only supports null safety now and this query parameter was removed, so it is not doing anything and can be removed.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
PTAL @johnpryan

**Comment by sfshaza2** [comment]
I loooove this PR! The more cleanup the better. But, as @domesticmouse requested, will wait for @johnpryan's review.

**Comment by sfshaza2** [comment]
@johnpryan, please review.

**Comment by sfshaza2** [comment]
OK, John is swamped and Brett has approved, so I am merging. We can revert if needed.

**Pull request merged**
