### PR TITLE
Update mocking.md

### PR DESCRIPTION
**Pull request by rafamarqs**
variable for creating a mock object added in the main class

### CODE REVIEW

**Comment by rafamarqs** [comment]
@googlebot I signed it!

**Review by sfshaza2 — COMMENTED** [review]
@rafamarqs, in the cookbook we use a "check excerpts" tool. So if you change code in the page, you also need to change it in the /examples directory and run the "code refresh" script. I'm cc'sing @miquelbeltran on this PR because he is migrating our pages to use code snippets and also to use the latest null safe APIs. But I will most likely have to close this PR.

**Comment by miquelbeltran** [comment]
Hi @rafamarqs as Shams said, you cannot modify the code in the markdown directly because it is generated from a code sample in another folder.

Secondly, I am not sure what your change is trying to accomplish, could you explain a little further?

**Comment by sfshaza2** [comment]
I'm closing this, though feel free to continue chatting with @miquelbeltran on the closed PR.

**Comment by rafamarqs** [comment]
I understand. Thank you for that @sfshaza2 and @miquelbeltran.
I tried to run the cookbook (https://flutter.dev/docs/cookbook/testing/unit/mocking) but part 3 didn't work and the code seemed incomplete.
I looked in the package documentation (https://pub.dev/packages/mockito) and saw what seemed to be what was missing and it worked.

**Pull request closed without merging**
