### PR TITLE
Add Tiled to the Games Toolkit resources page

### LINKED ISSUE #9998: [Feature Request]: Add Tiled as a resource on the 'Casual Games Toolkit' page
### Page URL

https://docs.flutter.dev/resources/games-toolkit/

### Page source

https://github.com/flutter/website/tree/main/src/resources/games-toolkit.md

### Describe the problem

image
In the resources section, can we add another resource?

Tiled: https://www.mapeditor.org/ 
It is a free and open source level editor, and they also support Flame. 

### Expected fix

In the "Other resources" section,
under "Feature", add "Level editor", 
under "Resources", add "Tiled" with a hyperlink https://www.mapeditor.org/ 

### Additional context

_No response_

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

### PR DESCRIPTION
**Pull request by ghanghavmayur**
… 'Other resources'section

_Description of what this PR is changing or adding, and why:_

 Added "Level editor" under "Feature" and included "Tiled" with a hyperlink to [https://www.mapeditor.org/](https://www.mapeditor.org/) in the "Other resources" section.

_Issues fixed by this PR (if any):_

Fixes #9998

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by atsansone** [comment]
@ghanghavmayur : The issue only needed the changes you made on [lines 342-350](https://github.com/flutter/website/pull/10013/files#diff-34e0ebaba716c0f5e4a487657182bf2a7e114148d08f1326df7e9fb08e1a4524R342-R350) of this PR. The other changes run counter to existing style and format. Can you revert those changes and push the changes to this PR?

Thanks!

**Review by atsansone — APPROVED** [review]
LGTM. Thanks!

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
FYI @zoeyfan

**Pull request merged**
