### PR TITLE
Improve /jobs pages a bit

### PR DESCRIPTION
**Pull request by kwalrath**
_Description of what this PR is changing or adding, and why:_

* Updated application instructions in /jobs/writer
* Fixed a typo in /jobs
* Fixed a few other things in other job pages

Note that /jobs/devexp still has the old application instructions. (I couldn't find an external job posting for it.)

_Issues fixed by this PR (if any):_

None I could find.

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
A definite improvement! Thx! lgtm

**Comment by kwalrath** [comment]
I just remembered that I changed the wording & formatting of the application section a bit in /jobs/writers. To be thorough, I should make those changes in all the other pages, too, if reviewers like my changes.

**Comment by sfshaza2** [comment]
ok!

**Comment by kwalrath** [comment]
I'll make those formatting changes in the application sections now...

**Review by tvolkert — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
