### PR TITLE
Fix macOS version for notarizing

### PR DESCRIPTION
**Pull request by cervm**
This article confirms the version required (10.14.5).
https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

### CODE REVIEW

**Comment by cervm** [comment]
@googlebot I signed it!

**Review by sfshaza2 — COMMENTED** [review]
@xster, can you confirm? (Very quick.)

**Comment by sfshaza2** [comment]
@domesticmouse, can you confirm?

**Comment by xster** [comment]
LGTM

**Pull request merged**
