### PR TITLE
Capitalized "Hot Reload"

### PR DESCRIPTION
**Pull request by maguinis**
Since Hot Reload is a feature, it should be capitalized (unless used as a verb).

### CODE REVIEW

**Comment by kwalrath** [comment]
I'm not sure we should be doing this - I don't think we necessarily capitalize features. (I'll do a little research to see if I can back up my gut feeling.)

**Comment by InMatrix** [comment]
FWIW, React Native seems to capitalize "Hot Reloading": https://facebook.github.io/react-native/blog/2016/03/24/introducing-hot-reloading.html

**Comment by InMatrix** [comment]
Upon taking a closer look, they don't really capitalize hot reload consistently.

**Comment by Sfshaza** [comment]
My first instinct was also that we don't capitalize features. For example, we didn't introduce "Strong Mode", it was "strong mode." I looked in the [Google Style Guide](https://developers.google.com/style/capitalization) and it doesn't mention capitalization for features, unless patented or trademarked, etc.

**Comment by mit-mit** [comment]
Closing as there doesn't seem to be consensus to change our style here.

**Pull request closed without merging**
