### PR TITLE
Design doc for InputDecoration.centerFloatingLabel

### PR DESCRIPTION
**Pull request by werainkhatri**
PR related to Design Doc: flutter/flutter#90157

### CODE REVIEW

**Review by sfshaza2 — DISMISSED** [review]
LGTM!

**Comment by sfshaza2** [comment]
@werainkhatri, can you update this PR? We are no longer using the "archived-master" branch (that was formerly the "master" branch. We now use the "main" branch. Once you fix the PR I can land. Thx!

**Comment by werainkhatri** [comment]
Is this fine? 😬

**Review by sfshaza2 — APPROVED** [review]
LGTM!

**Pull request merged**
