### PR TITLE
Fixing some broken code

### PR DESCRIPTION
**Pull request by sfshaza2**
Fixing the build (I hope).

### CODE REVIEW

**Comment by kwalrath** [comment]
Looks like the build is still failing

**Comment by filiph** [comment]
Looks like a dartfmt issue in `src/docs/cookbook/networking/background-parsing.md`:

```
  FAIL: ----- diff -----
  <   final response = await client
  <       .get(Uri.parse('https://jsonplaceholder.typicode.com/photos'));
  ---
  >   final response =
  >       await client.get(Uri.parse('https://jsonplaceholder.typicode.com/photos'));
```

**Comment by mit-mit** [comment]
Oh, this is the same thing I just did in https://github.com/flutter/website/pull/5450

**Comment by sfshaza2** [comment]
Fixed by @mit-mit. Closing.

**Pull request closed without merging**
