### PR TITLE
add go/test-widgets-flutter-binding-clock link

### PR DESCRIPTION
**Pull request by jakemac53**
context https://github.com/flutter/flutter/pull/54125

### CODE REVIEW

**Comment by jakemac53** [comment]
@Sfshaza it looks like pub hit an infinite loop in the version solve, is that a known problem? Can I submit?

**Comment by sfshaza2** [comment]
@jakemac53, I have never seen this before. We can't merge if Travis won't pass. Do you have any idea why this might happen?

**Comment by sfshaza2** [comment]
I've kicked off the build again. Maybe it was a fluke?

**Comment by jakemac53** [comment]
I haven't seen it happen before :/

**Comment by sfshaza2** [comment]
OK, it passed! https://travis-ci.org/github/flutter/website/builds/672547746. But, for some reason, it's not updating this page to say it passed. But I'm going to merge it.

**Comment by jakemac53** [comment]
thanks!

**Pull request merged**
