### PR TITLE
Pass a URI to package:http API

### PR DESCRIPTION
**Pull request by natebosch**
Updates example to be forwards compatible with the breaking change in
https://github.com/dart-lang/http/pull/507

### CODE REVIEW

**Comment by sfshaza2** [comment]
Hi, @natebosch! It's unclear to me. Will this update work now when analyzed against the stable channel? If so, let's go for it. If not, we'll have to wait for this change to hit stable. The website is analyzed against stable. Alternatively, we could document both for now, but annotate the not-yet-working code with the  tag which tells Travis to not analyze it.

**Comment by natebosch** [comment]
This will work correctly when analyzed against the current package versions.

The existing published API is statically typed `dynamic` and at runtime it allows either `String` or `Uri`. The upcoming API is statically typed `Uri`. This PR does not break backwards compatibility, it adds forwards compatibility.

**Comment by sfshaza2** [comment]
Sounds great!

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Comment by sfshaza2** [comment]
@RedBrogdon fixed the cookbook code check errors in another PR. Forcing a merge.

**Pull request merged**
