### PR TITLE
Move "Our Values" section from individual job descriptions into the overview page

### PR DESCRIPTION
**Pull request by mkustermann**
This makes individual job postings more concise and avoids differences
in the "Our Values" section across postings.

### CODE REVIEW

**Review by khanhnwin — APPROVED** [review]

**Comment by domesticmouse** [comment]
> My only concern is that many people might skip the index page and go straight to the job posting.

Can this be placed into a template and included in each post?

**Comment by mkustermann** [comment]
> Can this be placed into a template and included in each post?

It is in the template (see the change in `src/jobs/_template.md`), but it's not in every existing posting. The phrasing of it is also flutter specific, which may be a reason it wasn't included in some postings - since we have flutter and dart postings.

> My only concern is that many people might skip the index page and go straight to the job posting.

It seems to me that main landing pages are flutter.dev/jobs & dart.dev/jobs which is the index page. When searching for `flutter team jobs` etc one ends up also in the index landing page.

If there's strong opinions on not doing this, I can also drop this PR, though IMHO it would make sense to do it.

**Review by sfshaza2 — CHANGES_REQUESTED** [review]
I prefer one of the following solutions:
- Update the template to be more Dart inclusive and less Flutter-focused.
- Update each job listing to refer to the index page for that info. You see, people DO tweet the job postings, and could easily miss that info.

Of the two approaches, I prefer the former. But I totally understand if you would rather not expend that effort. I don't mind doing it.

Also, just a little FYI, but dart.dev/jobs just redirects to our site.

**Comment by mkustermann** [comment]
> Update the template to be more Dart inclusive and less Flutter-focused.
> 
> I don't mind doing it.

That works as well - though the section should then be consistently there for all postings.

@sfshaza2  Thanks for volunteering, then I'll close this PR.

**Pull request closed without merging**
