### PR TITLE
Devtools release notes 20

### PR DESCRIPTION
**Pull request by polina-c**

### CODE REVIEW

**Comment by kenzieschmoll** [comment]
Can we make the screenshots smaller? These will be displayed in a small viewer inside DevTools, so making the screenshots smaller and more localized to the specific feature you are describing is best. Feel free to even annotate with arrows or boxes to point to the important part of the image

**Comment by sfshaza2** [comment]
I'll wait until Kenzie's requested changes land before merging.

**Comment by polina-c** [comment]
> I'll wait until Kenzie's requested changes land before merging.

done

**Comment by kenzieschmoll** [comment]
I think image 4693 should be the drop down where you can select "Group by User Tag"

**Comment by kenzieschmoll** [comment]
Screen Shot 2022-11-29 at 1 42 53 PM

**Review by kenzieschmoll — APPROVED** [review]

**Pull request merged**
