### PR TITLE
Update internationalization.md

### PR DESCRIPTION
**Pull request by Pingear**
Running "flutter pub get" in app...                     
Because app depends on flutter_localizations any from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because app depends on intl ^0.16.1, version solving failed.

pub get failed (1; So, because app depends on intl ^0.16.1, version solving failed.)
exit code 1

### CODE REVIEW

**Review by sfshaza2 — COMMENTED** [review]
This looks OK to me. @shihaohong, this is a one-line PR, what say you?

**Review by shihaohong — APPROVED** [review]

**Comment by shihaohong** [comment]
Looks good to me!

**Comment by Pingear** [comment]
@googlebot I signed it!

**Comment by Pingear** [comment]
@shihaohong 
Hi!
I've done it)

**Review by sfshaza2 — COMMENTED** [review]
On fixing a conflict for this PR, I see that this has already been fixed. Removing.

**Pull request closed without merging**
