### PR TITLE
cookbook: link to error reporting example repo

### PR DESCRIPTION
**Pull request by bruno-garcia**
Crashy is private archived: https://github.com/flutter/crashy

### CODE REVIEW

**Comment by sfshaza2** [comment]
@mit-mit, crashy is no more? (I see you've archived that repo).

**Comment by sfshaza2** [comment]
Also cc'ing @kwalrath, in case she knows.

**Comment by bruno-garcia** [comment]
It was private archived. I opened a PR to remove the link from the website.

**Comment by mit-mit** [comment]
> @mit-mit, crashy is no more? (I see you've archived that repo).

Yes, this was archived. The example lives here now:
https://github.com/getsentry/sentry-dart/tree/main/flutter/example

**Comment by sfshaza2** [comment]
Thanks for that info, @mit-mit! @bruno-garcia, this is why I asked Mit. I suspected the files might have moved. Can you either close your PR or update it with the new location?

Thx!!

**Comment by bruno-garcia** [comment]
I'll update the PR. Thanks!

**Comment by bruno-garcia** [comment]
@sfshaza2 updated the PR. Thanks again for the review

**Review by sfshaza2 — APPROVED** [review]
LGTM!

**Pull request merged**
