### PR TITLE
Update some text to reflect Ads being launched to GA. 

### PR DESCRIPTION
**Pull request by zoeyfan**
_Description of what this PR is changing or adding, and why:_

Update some texts to reflect Ads being launched to GA. 

_Issues fixed by this PR (if any):_

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Comment by sfshaza2** [comment]
@zoeyfan, can you fix the conflicts?

**Comment by zoeyfan** [comment]
@sfshaza2 my bad. I updated the texts, but later realized that a better approach would be just shutting down this page, and redirect traffic to flutter.dev/monetization. The request was captured in a different bug: https://github.com/flutter/website/issues/6510

**Comment by domesticmouse** [comment]
Closing this PR out.

**Pull request closed without merging**
