### PR TITLE
Add a link to the tools job posting

### PR DESCRIPTION
**Pull request by zanderso**
From https://github.com/flutter/website/pull/6301

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
LGTM!

**Comment by zanderso** [comment]
@sfshaza2 Does the failing presubmit check need a kick?

**Comment by zanderso** [comment]
Oh, it looks like I'm allowed to click the button, so I did that.

**Comment by zanderso** [comment]
Ah, it failed again. @sfshaza2 Do you if there's any way I can fix this?

**Review by domesticmouse — APPROVED** [review]

**Comment by sfshaza2** [comment]
I'm at the doctor's office, but I believe that Khanh fixed this? In a PR I
merged before leaving home. The problem wasn't your PR.

**Pull request closed without merging**
