### PR TITLE
[dash] Add GitHub org link and Twitter to main nav

### LINKED ISSUE #1400: [dash] Include Github and Community link on the top nav
We suggest to put the Github and Community links back to the top nav. These two links are the top links that new users want to learn more about.

### PR DESCRIPTION
**Pull request by chalin**
Closes #1400

Staged at https://ng2-io.firebaseapp.com

- Add to main nav:
  - Link to GitHub Flutter organization as an icon
  - Link to Twitter feed
- Remove from footer:
  - GitHub org link
  - Twitter feed link

This most closely resembles what other sites have including, for example, https://angular.io.

---

Screenshots:

screen shot 2018-10-08 at 18 30 01

&nbsp;

screen shot 2018-10-08 at 18 32 46

### CODE REVIEW

**Comment by Sfshaza** [comment]
So the only GitHub link is now Octokitty and that takes you to the particular page you are looking at?

**Comment by chalin** [comment]
> Showing two Octokitty icons seems confusing. Can we use other icon, like the existing pen icon?

The problem with the pen icon, is that it suggests that the link opens up on an editor over the page source. That isn't the case. The link is to the GitHub repo page source. Then, whether a user has permissions to edit the source will depend on the user's access rights, and whether they've setup a clone, etc.

How about an icon suggesting that the link is to the page source, something like this:
> screen shot 2018-10-08 at 20 29 32

**Comment by galeyang** [comment]
I didn't quite get the reason of showing the page source if a user doesn't permissions to edit the source, but I do feel the file icon you suggested work better than the pen icon!

**Comment by chalin** [comment]
> ... I do feel the file icon you suggested work better than the pen icon!

Ok, I'll make that change.

**Comment by chalin** [comment]
@galeyang, how does this look?

> screen shot 2018-10-08 at 20 47 18

**Comment by galeyang** [comment]
Looks good! Thanks for updating the icon.

**Comment by Sfshaza** [comment]
I'm confused. What does the file icon and the debug icon link to?

**Comment by chalin** [comment]
> What does the file icon and the debug icon link to?

They are page links for "View page source" and "Report a issue with this page".

**Comment by chalin** [comment]
Travis is green so I'll go ahead and merge. We can always tweak in a followup PR.

**Pull request merged**
