### PR TITLE
update wrong variable name in cookbook 

### PR DESCRIPTION
**Pull request by bringbackthedog**
`initialSetupRoute` should be `setupPageRoute`

### CODE REVIEW

**Comment by bringbackthedog** [comment]
@googlebot I signed it!

**Comment by sfshaza2** [comment]
Hi, @bringbackthedog, thanks for this update!

We need to make sure that all the code is migrated, too. All code excerpts on flutter.dev are checked in CI. The code shown in the cookbook section is found here: https://github.com/flutter/website/tree/master/null_safety_examples/cookbook. Are you able to update all that?

More about the testing of code excerpts: https://github.com/dart-lang/site-shared/blob/master/doc/code-excerpts.md.

**Review by sfshaza2 — CHANGES_REQUESTED** [review]
Please fix the code as well so it will pass CI.

**Review by sfshaza2 — APPROVED** [review]
This has already been fixed in the examples repo (website/examples/codelabs/cookbook/lib/examples). LGTM

**Comment by bringbackthedog** [comment]
Sorry just saw this thank you for your help with this.

**Comment by sfshaza2** [comment]
No need to be sorry! Thank you for your contribution, @bringbackthedog!



1

**Pull request merged**
