### PR TITLE
Add internet permission / entitlement instructions.

### PR DESCRIPTION
**Pull request by domesticmouse**
Using the same phrasing as `networking/fetch-data` everywhere.

## Presubmit checklist

- [x] This PR is marked as draft with an explanation if not meant to land until a future stable release.
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by parlough — APPROVED** [review]
Makes sense to me. Optionally consider moving the text out to an include.

**Review by sfshaza2 — APPROVED** [review]
lgtm! I also approve of Parker's idea of putting this in an include file.

**Comment by domesticmouse** [comment]
> lgtm! I also approve of Parker's idea of putting this in an include file.

As `flutter/website` is not my usual hunting grounds, where would you like me to put the include file? I had a look in `_includes` but i'm not seeing anything appropriate.

**Comment by sfshaza2** [comment]
_includes/docs

But it's really not a huge deal.  :)

**Pull request merged**
