### PR TITLE
docs(platform-integration): added pattern to note alert

### PR DESCRIPTION
**Pull request by LeonardoRosaa**
Changes proposed in this pull request:
*  Added pattern note styles to [Writing custom platform-specific code](https://flutter.dev/docs/development/platform-integration/platform-channels#architecture) section

Before:
before_note_alert

After:
after_note_alert

Thanks! 💙

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
Nice improvement, @LeonardoRosaa! Thx!

**Comment by sfshaza2** [comment]
Oh, I can't merge this until you sign the CLA.

**Comment by LeonardoRosaa** [comment]
> Oh, I can't merge this until you sign the CLA.

I think created successfully, is to resubmit PR?

**Comment by sfshaza2** [comment]
I was able to verify that you have signed it! LGTM

**Pull request merged**
