### PR TITLE
Add ValueNotifier & InheritedNotifier as state management option

### PR DESCRIPTION
**Pull request by tadaspetra**
A solution using the built-in functionality in the Flutter SDK such as InheritedNotifier and ValueNotifier.

The other documentation doesn't reference the use of these two together which results in a simple approach to immutable state management

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
I can't see why `flutter-website-staging` is failing. Insufficient permissions?

**Comment by tadaspetra** [comment]
> I can't see why `flutter-website-staging` is failing. Insufficient permissions?

Is there anything that I need to do on my end?

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Pull request merged**
