### PR TITLE
Remove Rosetta instructions from macOS page

### PR DESCRIPTION
**Pull request by timsneath**
Removes Rosetta instructions now that we have M1 support. Also clarifies that you can build macOS apps with a macOS developer workstation. 

_Issues fixed by this PR (if any):_
https://github.com/flutter/website/issues/7137

## Presubmit checklist
- [X] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [X] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [X] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by domesticmouse** [comment]
PTAL @jmagman

**Comment by jmagman** [comment]
We still need Rosetta installed on the host for several binaries as explained in https://github.com/flutter/website/pull/7119.

**Comment by jmagman** [comment]
Actually reopening, I didn't see the second non-Rosetta part which is a good change.

**Review by jmagman — CHANGES_REQUESTED** [review]
Need to keep the Rosetta instructions.

**Comment by timsneath** [comment]
Ah. Thanks. I’ll tweak the Rosetta part to explain and resubmit.

**Comment by timsneath** [comment]
Have a look and see if this is OK with you -- I added back the Rosetta sidebar with an embedded link to your comment on the older bug so that it's clear to those (like myself) who might have thought that Rosetta was no longer needed as of Flutter 3.

**Review by jmagman — APPROVED** [review]
LGTM!

**Review by domesticmouse — APPROVED** [review]

**Pull request merged**
