### PR TITLE
Tweaking the contact info on the books page

### PR DESCRIPTION
**Pull request by sfshaza2**
Fixes https://github.com/flutter/website/issues/6029

Staged:  https://sz-flutter.firebaseapp.com/docs/resources/books

@kwalrath, there's some HTML error in the page that I'm not seeing. The "sample" link isn't working. Not sure why...

### CODE REVIEW

**Comment by kwalrath** [comment]
> @kwalrath, there's some HTML error in the page that I'm not seeing. The "sample" link isn't working. Not sure why...

Interesting... I'll try to figure it out.

**Comment by kwalrath** [comment]
It seems to have a relationship to whether _samples_ is above the big right column (title/text) or the left column, so I bet the right column is stealing the mouse events, somehow.

**Comment by kwalrath** [comment]
Yep, that's almost certainly the problem. I don't know how to fix it, though.

image

**Review by kwalrath — APPROVED** [review]

**Comment by sfshaza2** [comment]
Thanks for that research!

**Pull request merged**
