### PR TITLE
iOS looking screenshot - take 1

### PR DESCRIPTION
**Pull request by xster**

### CODE REVIEW

**Comment by sethladd** [comment]
Lovely! We'll wait to merge this in when the code for this is a bit more cleaned up.

**Comment by mit-mit** [comment]
Can we merge this? Or close it, and open a new one later? I'd like to get the PR queue flushed...

**Comment by sethladd** [comment]
@xster is working on the code. We'd like to leave this open because we intend to land this soon.

**Comment by xster** [comment]
I'll close it for now. Will reopen when it's easy to do in production

**Pull request closed without merging**
