### PR TITLE
Fix format of sample code (Navigation and routing)

### PR DESCRIPTION
**Pull request by koji-1009**
_Description of what this PR is changing or adding, and why:_
The indentation of the sample code was incorrect.

_Issues fixed by this PR (if any):_
none.

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]
This looks like the mentioned code is not an excerpt. 

LGTM

**Review by parlough — APPROVED** [review]
Nice catch, thank you!

_Side note: I opened https://github.com/flutter/website/issues/10057 to track adding [code excerpts](https://github.com/dart-lang/site-shared/blob/main/doc/code-excerpts.md) to this page._

**Pull request merged**
