### PR TITLE
Update iOS Simulator setup documentation

### PR DESCRIPTION
**Pull request by tylerwgrass**
_Description of what this PR is changing or adding, and why:_
At some point, the iOS Simulator removed the **Hardware** menu.  I was able to find what I think the docs are attempting to point to:
image

_Issues fixed by this PR (if any):_

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by tylerwgrass** [comment]
I've just signed the CLA.

**Review by domesticmouse — APPROVED** [review]

**Review by sfshaza2 — APPROVED** [review]
Don't you love it when a very simple text update triggers an error against the stable branch? LGTM

**Comment by sfshaza2** [comment]
@tylerwgrass, would you mind terribly updating this PR with the latest changes to the site? That should fix the build error that you did not create. Otherwise, I'll have to close this PR and open another with your changes.

**Review by khanhnwin — APPROVED** [review]

**Comment by khanhnwin** [comment]
LGTM! Thanks so much @tylerwgrass!

**Pull request merged**
