### PR TITLE
Switched order of 'Get Started' and 'Setup' in nav sidebar.

### PR DESCRIPTION
**Pull request by qchong**
Fixes https://github.com/flutter/flutter/issues/4035

### CODE REVIEW

**Comment by sethladd** [comment]
Thanks! There's a lot of commits in here. I wonder if we can help you branch off of an updated version of master, so the only commits in here will be your changes (and any merges since).

**Comment by stevenroose** [comment]
The changes also seem to include more than just what the title says.

**Comment by sethladd** [comment]
> The changes also seem to include more than just what the title says.

We'll take a look at this PR and see if we can squash and rebase. Thanks for the head's up.

**Comment by qchong** [comment]
Abandoning this pull request to retry with a squashed commit list.

**Pull request closed without merging**
