### PR TITLE
Add go link to multi-window status

### PR DESCRIPTION
**Pull request by loic-sharma**
## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by atsansone — APPROVED** [review]

**Review by sfshaza2 — COMMENTED** [review]
This doc doesn't use the standard template. Why is that? Also, the top of the page shows an internal-only link.

**Comment by sfshaza2** [comment]
Despite @atsansone approval, do NOT land this until you've removed the internal link and answered why this doesn't use the template.

**Review by domesticmouse — CHANGES_REQUESTED** [review]
Per @sfshaza2 request, take out the `go` link at the top and port to the external template.

**Comment by loic-sharma** [comment]
Hello everyone, this doesn't use the design doc template as this isn't a design doc. Instead, this is a knowledge dump of the multi-window project. We've shared this document publicly as part of [our announcement that we are pausing this effort](https://github.com/flutter/flutter/issues/30701#issuecomment-2087377696). I'd like to add a public go link to make this document easier to find in the future when we resume this effort :)

> Also, the top of the page shows an internal-only link.

Removed!

**Comment by sfshaza2** [comment]
I see, @loic-sharma. Thanks for clarifying.

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Comment by sfshaza2** [comment]
@domesticmouse, can you remove your "request changes" and land this? Thx!

**Review by domesticmouse — APPROVED** [review]

**Pull request merged**
