### PR TITLE
Fix discord link

### LINKED ISSUE #7110: [PAGE ISSUE]: 'Security'
### Page URL

https://docs.flutter.dev/security/

### Page source

https://github.com/flutter/website/tree/main/src/security/index.md

### Describe the problem

Link to discord under [receiving security updates](https://docs.flutter.dev/security#receiving-security-updates) needs to be an invite link to the discord, instead of a direct url to the channel in question. I ended up just staying on an infinite loading screen in discord, either because that channel was deleted or possibly because you can't navigate directly to a channel without being a member of that server.

### Expected fix

Switch out the channel link <https://discord.com/channels/608014603317936148/608116355836805126> to be the discords invite link <https://discord.com/invite/N7Yshp4>

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by micpap25**
Changes the discord link to properly invite users to the Flutter server.
Fixes #7110

## Presubmit checklist
- [X] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [X] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [X] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by micpap25** [comment]
Are PRs being accepted? Just confirming

**Comment by domesticmouse** [comment]
> Are PRs being accepted? Just confirming

Yup, we have landed the Flutter 3 changes that we were holding this repo steady for. PRs are open again =)

**Comment by khanhnwin** [comment]
Hey @micpap25 - Thanks for the PR! I suspect the discord link is was meant to be this link instead: https://discord.gg/BS8KZyg It's the one linked on the flutter/flutter repo: https://github.com/flutter/flutter/wiki/Chat

The proposed link in the PR seems to point to the /r/FlutterDev server.

**Comment by micpap25** [comment]
Alright, fixed

**Comment by khanhnwin** [comment]
Thanks @micpap25! Will land once the build goes green!

**Pull request merged**
