### PR TITLE
Fixing site layout on smaller screens

### PR DESCRIPTION
**Pull request by ThomasOrlita**
[#10229](https://github.com/flutter/flutter/issues/10229)

### CODE REVIEW

**Comment by ThomasOrlita** [comment]
I signed it!

**Comment by eseidelGoogle** [comment]
Wherefore art thou staging bot? (normally a bot posts a URL to see the site with the changes applied)

**Comment by ThomasOrlita** [comment]
Ok, here's the URL: http://flutter-website.github.thomasorlita.cz/

**Comment by eseidelGoogle** [comment]
@ThomasOrlita no, sorry!  I didn't mean to imply *you* needed to do any work.  There is a bot which automatically creates staged versions of every flutter/website PR.  I'm not sure why it didn't work here.  @sethladd?

**Comment by sethladd** [comment]
I learned that the staging bot only works for branches on this repo. We can chat with @FaisalAbid to see if there's a workaround...

**Comment by sethladd** [comment]
Thank for the patch!  lgtm

**Comment by FaisalAbid** [comment]
Yea @eseidelGoogle @sethladd , Travis removes all the secret tokens from external contributions when they are built. The workaround to this would be an external service that monitors the pull requests, rather than it executing from Travis itself.

**Pull request merged**
