### PR TITLE
Docs integration test

### PR DESCRIPTION
**Pull request by Abhishek01039**
image
Here docs says to create `integration_test_driver.dart`. So here https://flutter.dev/docs/testing/integration-tests#directory-structure should be something like this 
image

The same thing for command as well !

### CODE REVIEW

**Comment by Abhishek01039** [comment]
@bkonyi 
can you please review this PR?
Thanks

**Comment by Abhishek01039** [comment]
Hello @mit-mit 
can you please review this PR?
Thanks

**Comment by mit-mit** [comment]
I'm not the right reviewer for this. But I suspect it will be reviewed soon now that folks are coming back from the holidays.

**Comment by Abhishek01039** [comment]
Thanks

**Comment by Abhishek01039** [comment]
@sfshaza2 
can you please review this PR?
Thanks

**Comment by Abhishek01039** [comment]
Hello @sfshaza2 , @Sfshaza 
can you please review this PR?
Thanks

**Comment by sfshaza2** [comment]
Hey, @johnpryan, this looks easy. Can you confirm this PR?

**Review by johnpryan — APPROVED** [review]

**Pull request merged**
