### PR TITLE
Migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by athomas**
Changes proposed in this pull request:

* Replace the Travis workflow with a GitHub Actions workflow.

### CODE REVIEW

**Comment by athomas** [comment]
@kwalrath @RedBrogdon This PR mostly emulates what Travis does, but there are a few significant changes:

* flutter doctor is only run on the "right" version (the submodule version, or the version of the specific branch).
* git magic is used to switch flutter channels rather than the flutter tool (to stay on a single branch/shallow checkout rather than syncing all the tags and most of the repo).
* the deploy is done with stable versions only (Travis ran the deploy on all versions, resulting in multiple deploys per landed commit).

I don't have rights in flutter/website or the Firebase project, before this PR can be landed somebody with the keys needs to add the `FIREBASE_TOKEN` repository secret in the GitHub repo. There may also be other tokens configured in Travis and used by the script. Travis prints this:

```
$ export FIREBASE_FILE=[secure]
$ export FUNCTION_PASSWORD=[secure]
$ export GITHUB_TOKEN=[secure]
$ export ENABLE_PR_BOT=[secure]
$ export FIREBASE_TOKEN=[secure]
```

`FIREBASE_TOKEN` is definitely needed, I'm not sure if any of the other ones are in use. `tool/prdeployer.dart` uses `GITHUB_TOKEN` but that doesn't seem to be hooked-up in Travis.

**Comment by athomas** [comment]
Marking as draft until the secrets are configured.

To see what it does before landing it, you can look at the output in my fork:
https://github.com/athomas/website/actions/runs/577854876

To kickstart GitHub Actions in flutter/website, a repo admin would need to open a PR adding some GitHub Actions workflow from the UI (https://github.com/flutter/website/actions). It doesn't matter what is in the PR, and it can be closed immediately after creation (without merging it).

**Comment by kwalrath** [comment]
> To kickstart GitHub Actions in flutter/website, a repo admin would need to open a PR adding some GitHub Actions workflow from the UI (https://github.com/flutter/website/actions). It doesn't matter what is in the PR, and it can be closed immediately after creation (without merging it).

Done: #5315

**Comment by kwalrath** [comment]
I don't know who has the keys... @RedBrogdon?

**Comment by sfshaza2** [comment]
Thanks so much, @athomas! Waiting for @RedBrogdon or @filiph to get the secret sauce working.

**Review by sfshaza2 — APPROVED** [review]
LGTM. (As far as Filip and I can tell.)

**Review by filiph — APPROVED** [review]
LGTM

**Pull request merged**
