### PR TITLE
Change `flutter packages` to `flutter pub`

### PR DESCRIPTION
**Pull request by mit-mit**
Related to https://github.com/flutter/flutter/pull/33041

### CODE REVIEW

**Comment by mit-mit** [comment]
This was related to the overall branding change to pub.dev. It's all pub now!

**Comment by sfshaza2** [comment]
Yes, it makes sense. I just hadn't thought about it. Thanks for taking care of it!

Btw, can you add me as an admin on the flutter/website repo?

**Comment by MaikuB** [comment]
@mit-mit from what I've seen, the code changes to enable the use of the `flutter pub` command only landed in master recently and aren't in the stable channel. Therefore, if i'm not mistaken, those that follow the Flutter installation guide on the website will be on the stable channel and will find that running the commands will fail to run. If that's the case then the change would either need to be reverted until the changes have flowed through to stable, or both `flutter packages` and `flutter pub` is listed with a note that the latter isn't on stable yet.

**Comment by mit-mit** [comment]
@MaikuB the changes landed over two different PRs:

  * https://github.com/flutter/flutter/pull/30115: This added support in `flutter packages/flutter pub` (those two are aliases) for all existing pub commands (downgrade, deps, run, activate, etc.). This landed on March 28th, and is in all Flutter channels incl. stable.
  * https://github.com/flutter/flutter/pull/33041: This did indeed just land, but all that that is to "advertize" `flutter pub` over `flutter packages` (and note that `flutter packages` is still a valid alias, so it's non-breaking)

**Comment by MaikuB** [comment]
@mit-mit Thanks for the fast reply and clarification. In that case there may an issue and I've logged it on the flutter/flutter repo [here](https://github.com/flutter/flutter/issues/33302)

**Pull request merged**
