### PR TITLE
Adding package dependencies for tools/*

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Comment by domesticmouse** [comment]
Can someone please re-trigger the Travis build? It timed out downloading dart 😂

**Comment by sfshaza2** [comment]
Re-triggered.

**Comment by domesticmouse** [comment]
I don't understand the failure log. Help @filiph and @kevmoo =)

**Comment by kevmoo** [comment]
🤷‍♂

**Comment by filiph** [comment]
The linkchecking failed on:

```
http://localhost:4002/showcase
- (616:40) 'Android' => https://play.google.com/store/apps/details?id=com.taobao.idlefish&e=-EnableAppDetailsPageRedesign (HTTP 404)
```

Seems like that app was removed from the app store. Not your fault, @domesticmouse.

cc @maguinis, I will remove that Alibaba's play store link

**Comment by filiph** [comment]
Oh wait, @kwalrath already did this. Thanks Kathy!

**Comment by filiph** [comment]
LGTM, merging. @domesticmouse, what are these dependencies good for? Or is it that we depended on all of them transitively?

**Comment by domesticmouse** [comment]
@filiph these were required by scripts under tools/ 😁

**Pull request merged**
