### PR TITLE
Added design doc for Backdrop Material Component

### PR DESCRIPTION
**Pull request by daadu**
Drafted till the Website Freeze and draft for design doc is ready.

### CODE REVIEW

**Review by sfshaza2 — COMMENTED** [review]
@daadu, is this ready to land? (I see the public doc is there.)

**Comment by daadu** [comment]
@sfshaza2 No, this isn't. It might take some time. In that case should I close this? and open when ready?

**Comment by sfshaza2** [comment]
No, it's fine. Though, in general, I don't like having PRs sit for long periods of time.

**Comment by sfshaza2** [comment]
@daadu, since this is taking so long, and the JSON file has changed, I'm going to close this. Please submit a new PR when your doc is ready.

**Pull request closed without merging**
