### PR TITLE
 Removed the `path` variable and argument for `takePicture` function

### LINKED ISSUE #5130: Camera example code doesn't pass analysis
This page has a full example of using the camera plugin:
https://flutter.dev/docs/cookbook/plugins/picture-using-camera#complete-example

This code doesn't work with the most recent version of the camera plugin (`0.6.2+1`), as it doesn't pass analysis:

```
Too many positional arguments: 0 expected, but 1 found.
Try removing the extra arguments.
```

The following line is the one that triggers this:

```dart
            // Attempt to take a picture and log where it's been saved.
            await _controller.takePicture(path);
```

### PR DESCRIPTION
**Pull request by VarunSAthreya**
Fixes #5130 & #5109

### CODE REVIEW

**Comment by VarunSAthreya** [comment]
@googlebot I signed it!

**Review by sfshaza2 — CHANGES_REQUESTED** [review]
@VarunSAthreya, this updated code failed analysis. You can read the log here:

```
   info • Unused import: 'package:path/path.dart' •
          src/docs/cookbook/plugins/picture_using_camera_md_1.dart:7:8 •
          unused_import
   info • Unused import: 'package:path_provider/path_provider.dart' •
          src/docs/cookbook/plugins/picture_using_camera_md_1.dart:8:8 •
          unused_import
  error • 1 positional argument(s) expected, but 0 found •
         src/docs/cookbook/plugins/picture_using_camera_md_1.dart:102:42 •
         not_enough_positional_arguments
  error • Undefined name 'path' •
         src/docs/cookbook/plugins/picture_using_camera_md_1.dart:108:71 •
         undefined_identifier
```

I can't merge until this passes analysis.

**Comment by VarunSAthreya** [comment]
I'll do the necessary changes.

**Comment by VarunSAthreya** [comment]
@sfshaza2 
In the analysis log the errors as:
error

Which is for the following code:

```dart
// Error #1
final image = await _controller.takePicture();

// Error #2
Navigator.push(
  context,
  builder: (context) =>
    DisplayPictureScreen(imagePath: image.path),
    ),
  );
```
As per the [changelog](https://pub.dev/packages/camera/changelog#060), the function `takePicture`  doesn't take any arguments and returns the image as an instance of `XFile` class.

changelog

I tried running the code in the emulator and it's working fine.

(SDK details:
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (8 days ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5)

https://user-images.githubusercontent.com/64711780/106369235-a970d680-6375-11eb-9d14-107b4432e184.mp4

In the analysis log, the dev and beta channel code checks are passing, and only in the stable channel, the code is failing.

analysis

Can I get any idea about the errors or is there anything I am missing?

**Review by sfshaza2 — COMMENTED** [review]
Dupe of https://github.com/flutter/website/pull/5342.  Closing.

**Pull request closed without merging**
