### PR TITLE
Enable refresh-code-excerpts.sh in docker

### PR DESCRIPTION
**Pull request by hrishikesh-kadam**
This will enable Refreshing Code Excerpts in the `make test` target.
As `make test` target is used in GitHub Actions CI, any error in code excerpts will fail the job.
This will alert the code reviewers before merging the PRs.

67f1377 will intentionally fail in GitHub Actions CI due to an incomplete fix in https://github.com/flutter/website/pull/6200
Once it fails, I will push the necessary changes to make the CI jobs pass.

### CODE REVIEW

**Comment by hrishikesh-kadam** [comment]
049ec43 failed as expected.
Pushing expected changes.

**Comment by hrishikesh-kadam** [comment]
Stable channel Test passed.

**Comment by hrishikesh-kadam** [comment]
Thank you Flutter team for incorporating the Docker concept.
I finally got the motivation to learn this skill.

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Pull request merged**
