### PR TITLE
Typo fixes for Actions & Shortcuts

### PR DESCRIPTION
**Pull request by chenglu**
Two typo fixes:

- [X] Fixed the URL link in the sidebar
- [X] There is an embedded DartPad at the bottom that is not in effect, maybe forgot to import the JS file?

### CODE REVIEW

**Review by johnpryan — APPROVED** [review]

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
Please bring this PR up to date with the `main` branch to fix the CI failures.

**Comment by chenglu** [comment]
Done and the CI has been passed, please considering merge this PR, thanks!

**Comment by domesticmouse** [comment]
PTAL @sfshaza2 =)

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Pull request merged**
