### PR TITLE
Update Windows supported platforms: Updates Windows 7 and 8 to unsupported

### PR DESCRIPTION
**Pull request by itsjustkevin**
## Description
Updates Windows Supported Deployment Platforms, moving Windows 7 and 8 to the unsupported tier. 

## Issue addressed
- https://github.com/flutter/flutter/issues/140830

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by parlough** [comment]
I thought 3.19 still supports Windows 7 and 8, then 3.21 will drop them?

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
PTAL @sfshaza2

**Review by atsansone — APPROVED** [review]
LGTM. Thanks for the update!

**Review by parlough — CHANGES_REQUESTED** [review]
Thanks all for taking a look and approving.

However: Requesting changes to prevent accidental merging so my [above question](https://github.com/flutter/website/pull/10140#issuecomment-1941999247) can be clarified:

> I thought 3.19 still supports Windows 7 and 8, then the next beta and 3.22 will drop them?
> 
> While I'd like to introduce a UI for indicating beta platform support, this table currently is for the stable channel.

**Comment by itsjustkevin** [comment]
> @itsjustkevin @cbracken I thought 3.19 still supports Windows 7 and 8, then the next beta and 3.22 will drop them?
> 
> While I'd like to introduce a UI for indicating beta platform support, this table currently is for the `stable` channel.

The decision came down that this is the last stable release that will support those platforms.

**Comment by parlough** [comment]
By this, do you mean 3.19? If so, we should keep it on here, and then remove it closer to 3.22.

We'll also be publishing a breaking change guide for this on the [breaking change index](https://docs.flutter.dev/release/breaking-changes).

**Comment by itsjustkevin** [comment]
> > The decision came down that this is the last stable release that will support those platforms.
> 
> By "this", do you mean 3.19? That's what Chris mentioned on the linked bug. If so, we should keep it on here for now, and then remove it closer to 3.22.
> 
> We'll also be publishing a breaking change guide for this on the [breaking change index](https://docs.flutter.dev/release/breaking-changes).

Yeah, I see what you mean @parlough.  The timing is a bit confusing here, do we publish after the release, during the next release I am not entirely sure how to effectively communicate this.

**Comment by parlough** [comment]
Generally we communicate changes like this through the https://docs.flutter.dev/release/breaking-changes index page and the Flutter announce Google group: https://groups.google.com/g/flutter-announce. Those mentions can indicate that 3.19 will be the last release with support for Windows 7 and 8, link to relevant material, what developers need to do, etc.

I plan to expand this supported deployment platforms to have a way to indicate what platforms beta supports as well, and I'll make sure to account for this.

**Comment by itsjustkevin** [comment]
100% fair and thanks for this @parlough.  

On the announcement message, I already have one cooked up, just getting it reviewed and set to send.

**Comment by parlough** [comment]
Sounds great, thanks so much Kevin!

I'm going to close this change, but I'll make sure the supported platforms get updated for 3.19 (and again for 3.22), then account for this change where possible.

**Pull request closed without merging**
