### PR TITLE
Moving image files and also updating shared repos.

### PR DESCRIPTION
**Pull request by sfshaza2**
Moving image files so they can be used in DartPad instances as well as markdown files.

Also syncing the shared repos.

### CODE REVIEW

**Comment by kwalrath** [comment]
I expected some .md files in this PR, too. Are these files not referred to by anything on flutter.dev? (What _does_ refer to them?)

**Comment by sfshaza2** [comment]
DartPad. As it is now, they can't use these images from DartPad. They have
to be moved out of _assets.

**Comment by sfshaza2** [comment]
The md files are still to come. We are still reviewing them.  :)

**Comment by sfshaza2** [comment]
The Travis failure is due to out of date code excerpts, which this PR doesn't involve.

**Pull request merged**
