### PR TITLE
Add link to public FFI plugin doc

### PR DESCRIPTION
**Pull request by dcharkes**
Add a link to a public copy of the Flutter FFI plugins doc to solicit feedback 

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by sfshaza2** [comment]
@dcharkes, is this doc created on a Google owned doc (@google) file? If so, please change it to use an account created or gmail or something else. Thx

**Review by domesticmouse — APPROVED** [review]

**Comment by dcharkes** [comment]
> @dcharkes, is this doc created on a Google owned doc (@google) file? If so, please change it to use an account created or gmail or something else. Thx

It's on a gmail address.

**Comment by domesticmouse** [comment]
@dcharkes might want to open up acces

Screen Shot 2021-12-16 at 8 34 57 am
s

**Comment by dcharkes** [comment]
Uhm, I thought I did that. I'm not sure why it is not working. Any suggestions?

image

**Comment by domesticmouse** [comment]
Grab the url from the "Copy link", it'll probably have some arguments that act as a resource key.

**Comment by dcharkes** [comment]
Oh, I was being too smart, pattern matching with the line I copied that didn't have that key...

Fix: https://github.com/flutter/website/pull/6583

**Pull request merged**
