### PR TITLE
Fixing the typing indicator example

### PR DESCRIPTION
**Pull request by albertodev01**
_Description of what this PR is changing or adding, and why:_

The [typing indicator](https://docs.flutter.dev/cookbook/effects/typing-indicator) example uses helper functions rather than widgets, which is a bad practice (as stated [here](https://api.flutter.dev/flutter/widgets/StatefulWidget-class.html), [here](https://docs.flutter.dev/perf/rendering/best-practices#controlling-build-cost) and [here](https://www.youtube.com/watch?v=IOyq-eTRhvo)). I have simply replaced helper methods with stateless widgets

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by sfshaza2 — COMMENTED** [review]
This looks ok to me, but @khanhnwin, can you verify?

**Comment by albertodev01** [comment]
Why this got closed? @sfshaza2

**Comment by albertodev01** [comment]
Is there anything wrong in my PR? @domesticmouse @sfshaza2

**Comment by domesticmouse** [comment]
I'm curious why I can't see who closed this PR. Re-opening until @khanhnwin gets through her I/O work.

**Comment by sfshaza2** [comment]
Yeah, I don't know why it was closed. I don't think I closed it, did I?

**Comment by domesticmouse** [comment]
> Yeah, I don't know why it was closed. I don't think I closed it, did I?

I don't recall closing it. So, it's now officially a mystery =)

**Comment by sfshaza2** [comment]
Gentle ping to @khanhnwin to review the code.

**Review by khanhnwin — APPROVED** [review]
LGTM! Thank you, @albertodev01!

**Pull request merged**
