### PR TITLE
fix: Corrected path notation

### PR DESCRIPTION
**Pull request by koji-1009**
_Description of what this PR is changing or adding, and why:_

https://docs.flutter.dev/packages-and-plugins/swift-package-manager/for-plugin-authors,

I found a typo in the file path notation in the text. Since the correct path was obvious from the context of the text, a corrected PR was created.

_Issues fixed by this PR (if any):_

_PRs or commits this PR depends on (if any):_

## Presubmit checklist

- [ ] This PR is marked as draft with an explanation if not meant to land until a future stable release.
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by loic-sharma — APPROVED** [review]
I'm a bit embarrassed I copy-pasted this mistake so many times 😅 

Thank you for the wonderful contribution! 💙

**Review by parlough — APPROVED** [review]
Thanks so much! Approving and landing based on Loïc's approval :D

**Pull request merged**
