### PR TITLE
Fix icon for overflow menu to use three-dot more style

### PR DESCRIPTION
**Pull request by mit-mit**
Currently we use a hamburger icon for both main sidebar menu and the more menu when the page gets narrow, for example on mobile devices:
image

We should use the material "more" icon on the right.

### CODE REVIEW

**Comment by sethladd** [comment]
Can you remove the box that is drawn around the three dots? (presumably that's still there... ?)

**Comment by mit-mit** [comment]
I tried but could not figure out how to do that. Got any tips?

Also, need to get it to use a black font color

**Comment by sethladd** [comment]
NP, I'll remove the box. Thanks for switching to three dots!

**Comment by mit-mit** [comment]
@sethladd I merged with master so that this now passes Travis, and there is a staging URL. I would love your help with three CSS issues:

1. The box around the icon should not be shown in the "closed" state
1. The icon should be black, not default hyperlink blue
1. The icon should be placed further to the right (similar to the three-dot icon in Chrome).

**Comment by sethladd** [comment]
Thanks Michael. The three-dots is a definite improvement. I'm unlikely to get to the CSS fixin' soon, but maybe @FaisalAbid is interested in a little ninja CSS action here?

**Comment by FaisalAbid** [comment]
Hey @mit-mit I can totally help you out with this. I'll take a look at the 3 issues tonight

**Comment by sethladd** [comment]
Thanks @FaisalAbid . You 🎸 !

**Comment by FaisalAbid** [comment]
Howdy, I also moved the search a bit to the left so it wasn't touching the box.

Let me know if thats good!

screenshot 2017-05-03 01 06 05
screenshot 2017-05-03 01 06 08

**Comment by mit-mit** [comment]
RE: "it appears that one or more commits were authored by someone other than the pull request submitter. We need to confirm that they're okay with their commits being contributed to this project."

I'm OK with this!

**Comment by mit-mit** [comment]
Thanks so much @FaisalAbid, this looks great! I'll merge it.

**Comment by sethladd** [comment]
Thanks!!!

**Pull request merged**
