### PR TITLE
change to JPG for master screenshot of lakes, saving lots of space

### PR DESCRIPTION
**Pull request by sethladd**
From 1.1MB to ~300kb

### CODE REVIEW

**Comment by sethladd** [comment]
TBR= @Sfshaza

**Comment by Sfshaza** [comment]
This looks good, but did you want to change the examples, also? Under _includes/_code/lakes*? The pubspec and main.dart files would be affected.

LGTM, provided this is how you want to handle the example code.

**Comment by sethladd** [comment]
oh! yes, thank you! (I grepped too low in the tree)

**Comment by Sfshaza** [comment]
There is probably included code in the files that also need changing. Oy.

**Comment by sethladd** [comment]
I checked, and the code already uses lakes.jpg :)

**Comment by Sfshaza** [comment]
Awesome! LGTM

**Comment by eseidelGoogle** [comment]
Looks like you hadn't configured your git to set the author email correctly on this machine.

git config -a user.email foo@bar.com
iirc.

Plz don't ignore the CLA Bot. :(

**Comment by sethladd** [comment]
In the queue for things to fix today. Thanks for the instructions!

**Comment by sethladd** [comment]
Closes https://github.com/flutter/flutter/issues/8655

**Comment by Sfshaza** [comment]
Thanks for addressing this, @sethladd!

**Pull request merged**
