### PR TITLE
replace ios starter app screenshot, shrink all PNGs

### PR DESCRIPTION
**Pull request by sethladd**
closes https://github.com/flutter/flutter/issues/2124

screen shot 2016-02-25 at 1 56 38 pm

### CODE REVIEW

**Comment by sethladd** [comment]
cc @qchong

**Comment by sethladd** [comment]
closes https://github.com/flutter/flutter/issues/2183

**Comment by sethladd** [comment]
closes https://github.com/flutter/flutter/issues/2184

**Comment by qchong** [comment]
lgtm

**Pull request merged**
