### PR TITLE
Add the go router v14 migration guide

### PR DESCRIPTION
**Pull request by ValentinVignal**
Adds the migration guide for go router v14 (https://github.com/flutter/packages/pull/6495)

Fixes https://github.com/flutter/flutter/issues/146805

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by sfshaza2 — CHANGES_REQUESTED** [review]
Before I land this, @ValentinVignal, can you finish the doc? It still has template text and isn't complete. thx

**Comment by ValentinVignal** [comment]
> Before I land this, @ValentinVignal, can you finish the doc? It still has template text and isn't complete. thx

Oops, sorry about that ! I updated the doc

**Comment by domesticmouse** [comment]
> > Before I land this, @ValentinVignal, can you finish the doc? It still has template text and isn't complete. thx
> 
> Oops, sorry about that ! I updated the doc

I looked at the linked doc under incognito and it looks... very empty. Also, the images don't render under incognito.

**Comment by ValentinVignal** [comment]
> I looked at the linked doc under incognito and it looks... very empty. Also, the images don't render under incognito.

Oh weird, I also don't see the image, I don't know what's happening, I just followed the instructions. Let me investigate.

However, I'm able to see the content, not you? 

image

**Comment by domesticmouse** [comment]
Sorry @ValentinVignal, I'm used to these having a lot more content. If that's all that is required, sweet.

**Review by domesticmouse — APPROVED** [review]

**Comment by ValentinVignal** [comment]
That's super weird, on the first loading in an incognito tab, it shows the warning icon instead of the images. But if I load it in a 2nd incognito tab, it displays the images

<details>

<summary>Video</summary>


https://github.com/flutter/website/assets/32538273/88c71681-e971-41c1-91b6-5d2d03057303



</details>

**Comment by ValentinVignal** [comment]
If I start again from scratch:
1. Go to [flutter.dev/go/template](http://flutter.dev/go/template)
2. File > Make a copy
3. Click Share in the top right
4. Click “Change to anyone with the link” on the bottom left of the dialog that appears.
5. Change Viewer to Commenter in the dropdown near the bottom right corner.
6. Click Done.

I still get the same issue 🤔

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Pull request merged**
