### PR TITLE
Update download-button.md

### PR DESCRIPTION
**Pull request by AugustDG**
Added @ just before "required" keyword in constructor parameter, as it is required :D

Just a typo fix as otherwise the code does not compile!

### CODE REVIEW

**Comment by AugustDG** [comment]
@googlebot I signed it!

**Comment by sfshaza2** [comment]
@AugustDG, are you using Flutter 1.x or Flutter 2.x? The @ sign is no longer required in Flutter 2 due to null safety.

**Comment by sfshaza2** [comment]
@miquelbeltran

**Comment by AugustDG** [comment]
Oh, I see. I'm using 2.x, but without null-safety....

Probably why it was complaining 👌🏽

**Comment by sfshaza2** [comment]
Thanks for clearing that up, @AugustDG! At some point, null safety will no longer be optional.

**Pull request closed without merging**
