### PR TITLE
Update platform-views.md

### PR DESCRIPTION
**Pull request by ravindrabarthwal**
Fixed typo in the NativeViewFactory class constructor.

### CODE REVIEW

**Comment by pranjaljain0** [comment]
Hey @ravindrabarthwal do this

Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://cla.developers.google.com/ to sign.

Once you've signed (or fixed any issues), please reply here with @googlebot I signed it! and we'll verify it.

**Comment by sfshaza2** [comment]
@blasten, can you confirm?

Also, @ravindrabarthwal, if blasten does confirm, I can't merge this unless you sign the CLA.

**Comment by ravindrabarthwal** [comment]
I have signed the CLA.

**Comment by pranjaljain0** [comment]
> I have signed the CLA.

@ravindrabarthwal you have to reply to the same mail

**Comment by sfshaza2** [comment]
Thx!

**Review by blasten — APPROVED** [review]
LGTM

**Comment by sfshaza2** [comment]
I was able to manually verify that he's signed it. Thx!

**Pull request merged**
