### PR TITLE
Changes is Code snippet of Step 5&6

### PR DESCRIPTION
**Pull request by iamSahdeep**
I made changes to code snippets in step 5 and step 6 which shows people, where to exactly put that code.

Also I have added line in code snippet of step 6
 `title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),`
As it is included in is Step 3 but not [here](https://raw.githubusercontent.com/flutter/website/master/_includes/code/layout/lakes/main.dart).

### CODE REVIEW

**Comment by iamSahdeep** [comment]
I signed it!

**Comment by Sfshaza** [comment]
Thanks for submitting, @iamSahdeep!

I am currently in a mad rush for I/O. I'll look at this when I have time.

**Comment by iamSahdeep** [comment]
That's alright... take as much time as you want.

**Comment by Hixie** [comment]
@Sfshaza any chance you have time to review it now?

**Comment by Sfshaza** [comment]
LGTM

**Pull request merged**
