### PR TITLE
Show correct video for LinearGradient widget.

### PR DESCRIPTION
**Pull request by antfitch**
_Description of what this PR is changing or adding, and why:_
The same video was appearing twice. This PR updates the one of the videos to display the correct one for the LinearGradient widget.

_Issues fixed by this PR (if any):_
[11288](https://github.com/flutter/website/issues/11288)

_PRs or commits this PR depends on (if any):_
n/a

## Presubmit checklist

- [ x] This PR is marked as draft with an explanation if not meant to land until a future stable release.
- [ x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by sfshaza2** [comment]
@antfitch, I should have told you this. When creating a PR, paste the bug that it fixes in the description box. Then when the PR lands, the bug is automatically closed.

**Comment by antfitch** [comment]
> @antfitch, I should have told you this. When creating a PR, paste the bug that it fixes in the description box. Then when the PR lands, the bug is automatically closed.

Done! Thank you for catching this.

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Comment by parlough** [comment]
Just a note, to automatically close an issue when a PR is merged, you'll need to use of the [supported keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) and have the hash.

So in this case, something like this would work:

```
Fixes #11288
```

**Comment by antfitch** [comment]
> Just a note, to automatically close an issue when a PR is merged, you'll need to use of the [supported keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) and have the hash.
> 
> So in this case, something like this would work:
> 
> ```
> Fixes #11288
> ```
> 
> I personally prefer to just use the whole link:
> 
> ```
> Fixes https://github.com/flutter/website/issues/11288
> ```

Thank you for letting me know about this. I'll make sure to do that moving forward.

**Comment by sfshaza2** [comment]
Yeah, I paste in the full link, too, but GitHub shortens it to just the
number with a link.  Smart little GitHub.  :)

**Pull request merged**
