### PR TITLE
Snackbar component, deprecated pages

### PR DESCRIPTION
**Pull request by fertolg**
- Implements snackbar component and styles
- Adds deprecated metadata to catalog sample pages
- Adds a snackbar when a doc is deprecated

Staging links:
- https://flutter-web-staging.firebaseapp.com/docs/catalog/samples
- https://flutter-web-staging.firebaseapp.com/docs/catalog/samples/animated-list

Fixes: #1492

### CODE REVIEW

**Comment by fertolg** [comment]
@chalin I don't see the deprecated pages in the navigation structure, so I'm unsure how to tackle the part where the nav should show them greyed out. Should I add these pages into the side nav? If so, do you know where they are supposed to live under?

**Comment by chalin** [comment]
> I don't see the deprecated pages in the navigation structure ...

Right, that's what issue #1612 is about. Feel free to address #1612 in this PR or a followup PR (I'd be ok with the latter).

Personally, I find the snackbar too discrete. @sfshaza2, WDYT?

**Comment by chalin** [comment]
> My first reaction was similar to Patrice's - surprise that the note was not the width of the window. But as I scrolled around, it was very noticeable. So I'm OK with it.

I'm ok with the width. Maybe we could:

- Change the color of the snackbar to an alert color
- Also, change the page background color (a light tint of yellow or orange) -- that would catch the readers attention and lead them to read the snackbar message.

Given @InMatrix's stated preference in https://github.com/flutter/website/issues/1612#issuecomment-434756324, maybe you have an opinion about this PR? /cc @galeyang

**Comment by InMatrix** [comment]
Thanks for making this PR! I agree with [the comments](https://github.com/flutter/website/pull/1760#issuecomment-440908897) @Sfshaza made earlier. I don't think it's necessary to make the snackbar appear more prominently than it is.

**Pull request merged**
