### PR TITLE
bug fixed

### PR DESCRIPTION
**Pull request by Kartik-21**
change in sample code

### CODE REVIEW

**Comment by johnpryan** [comment]
Hi @Kartik-21, could you sign the CLA? Thanks for the pull request!

**Comment by Kartik-21** [comment]
Yes I have sign CLA

**Comment by domesticmouse** [comment]
@googlebot please verify

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
Thank you @Kartik-21!

**Comment by sfshaza2** [comment]
LGTM

**Pull request merged**
