### PR TITLE
some style tweaks to the website

### PR DESCRIPTION
**Pull request by devoncarew**
- make the `(alpha)` and side nav text not quite as small (have it take the normal page text)
- have the sidebar headers look closer to the in-page headers

### CODE REVIEW

**Comment by devoncarew** [comment]
Looks like coveralls.io is currently not reachable? It's breaking our link checker (https://coveralls.io/github/flutter/flutter?branch=master).

**Comment by sethladd** [comment]
Do you have a screenshot or a staging URL? Hard to tell the impact of this change.

(normally it stages this for us... maybe the error in travis prevented the auto-staging?)

**Comment by devoncarew** [comment]
I restarted travis - we have a preview link now. Here's the before and after (mostly, the nav text isn't slightly smaller than the body text):

screen shot 2017-10-13 at 4 48 24 am

screen shot 2017-10-13 at 4 50 59 am

**Comment by sethladd** [comment]
lgtm

**Pull request merged**
