### PR TITLE
Update visual debugging diagram to match latest UI

### PR DESCRIPTION
**Pull request by jacob314**
Update screenshot to reflect new location for Widgets and Render Tree tabs.

### CODE REVIEW

**Comment by mit-mit** [comment]
Hi @jacob314 which version is the new UI in? I still see the old UI in Version: 22.2.1.

**Comment by jacob314** [comment]
I'll hold up on landing this until a version of the intellij plugin with this tweak goes live. No rush as the old UI is fine as long as you only have one connected device.

**Comment by Hixie** [comment]
Can we automate the generation of these screenshots the way we automate the generation of the screenshots in the API docs?

**Comment by Hixie** [comment]
@jacob314 ping - we should either land this (ideally with the screenshots generated in an automated fashion) or close it for now to get it off the review queue.

**Comment by jacob314** [comment]
Closing for now. Re-landing on the next intellij release.
Automated generation is a good idea but we don't yet have tooling in place to support that in IntelliJ.

**Pull request closed without merging**
