### PR TITLE
Add toolbar screenshot

### PR DESCRIPTION
**Pull request by mit-mit**
Fixes https://github.com/flutter/flutter/issues/6624

### CODE REVIEW

**Comment by mit-mit** [comment]
@sethladd please review

**Comment by sethladd** [comment]
lgtm modulo travis

**Comment by mit-mit** [comment]
Travis failure seems totally unrelated to my oneline change!?

example/widgets_intro_md_8.dart

widgets.md

18 code snippets extracted.

Analyzing the extracted Dart libraries.

Analyzing 18 files...

[warning] Instance member 'white' can't be accessed using static access.
(example/widgets_intro_md_2.dart, line 43, col 64)

(Ran in 11.1s)

The command "./tool/travis.sh" exited with 1.

**Comment by sethladd** [comment]
Ah, yes, welcome to "analyze/lint all the code in the website on every PR". :) This is a very cool robustness feature added by @devoncarew to help ensure our code samples/snippets on the website are up-to-date w.r.t. the Flutter SDK.

What happens sometimes is that between the time you make a change and when you're ready to submit, the Flutter SDK changed an API. When Travis runs, it notices that a snippet on the website is stale.

You can try rebasing your branch to see if that helps.

**Comment by mit-mit** [comment]
Shouldn't we have nightly test runs to capture those kind of errors rather than wait until the next random PR?

**Pull request merged**
