### PR TITLE
Correct Web FAQ

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
Changes proposed in this pull request:

*  Add Firefox mobile to supported web platforms.

The mobile Firefox browser runs Flutter web apps (at least on Android).

For example: https://app.simpleclub.com

### CODE REVIEW

**Comment by sfshaza2** [comment]
@johnpryan, can you confirm?

**Comment by johnpryan** [comment]
It may run, but that doesn't mean we intend to support it. cc: @mariamhas

**Comment by creativecreatorormaybenot** [comment]
@johnpryan Then we should maybe update the wording. At the moment, it literally says:

>Flutter web apps can run on the following browsers:

**Comment by johnpryan** [comment]
Yeah, that's a little confusing. It currently says:

```
### Which web browsers are supported by Flutter?
Flutter web apps can run on the following browsers:
```

But probably should say:

```
### Which web browsers are supported by Flutter?
Flutter web apps support the following browsers:
```

**Review by sfshaza2 — CHANGES_REQUESTED** [review]
@creativecreatorormaybenot, would you mind making the change that @johnpryan suggests? Otherwise, I'll have to close this PR.  Thx!

**Comment by creativecreatorormaybenot** [comment]
@sfshaza2 But is Firefox mobile supported or not?

I see no reason why it would not be 🤔 Especially on iOS, it just uses WebKit, like all other browsers.

**Comment by sfshaza2** [comment]
@creativecreatorormaybenot, my understanding from the discussion is that it is not officially supported, though it may work.

**Comment by creativecreatorormaybenot** [comment]
@sfshaza2 

From:

> It may run, but that doesn't mean we intend to support it. cc: @mariamhas

I concluded that we are still waiting for an update on that matter (from @mariamhas).

**Comment by sfshaza2** [comment]
She doesn't monitor website issues, but @johnpryan speaks to her regularly. I'm assuming he's checked with her. @johnpryan, can you confirm?

**Comment by creativecreatorormaybenot** [comment]
@johnpryan @sfshaza2 Any update on this? I think we have concluded that the way it is currently is slightly misleading.

I understand that Firefox mobile might not have active support (even though we do not know why that would be, especially on iOS). Then again, I do not want to undersell Flutter because of that 😃

**Comment by johnpryan** [comment]
I'll see if I can get a concrete answer.

**Comment by sfshaza2** [comment]
Where are we on this PR, @johnpryan?

**Comment by johnpryan** [comment]
Right now we don't have automated testing set up for Firefox on mobile devices, so we can't guarantee support. It's likely that most of the features will work, but your milage may vary.

**Pull request closed without merging**
