### PR TITLE
fixing broken link

### LINKED ISSUE #4307: 'Samples' button redirects to 'Page not found'
Steps to reproduce:
- https://flutter.dev/docs
- Click on 'Samples' button
- Redirects to [https://github.com/flutter/samples/blob/master/INDEX.md](https://github.com/flutter/samples/blob/master/INDEX.md)
- 404 Page not found

This is the button:
```
<a class="card" href="https://github.com/flutter/samples/blob/master/INDEX.md">
      <div class="card-body">
        <header class="card-title">Samples</header>
        <p class="card-text">Check out the Flutter examples.</p>
      </div>
</a>
```

### PR DESCRIPTION
**Pull request by leonardopaffi**
Closes #4307 
Fixing "Samples" broken link on Docs page.

### CODE REVIEW

**Comment by leonardopaffi** [comment]
@googlebot I signed it!

**Comment by kwalrath** [comment]
Should we instead link to https://flutter.github.io/samples, as in #4288?

/cc @johnpryan @theacodes

**Comment by kwalrath** [comment]
Looks like we have 3 more occurrences that we should fix:

```
$ fgrep -Rl "blob/master/INDEX.md" src
src/404.html
src/docs/codelabs/layout-basics.md
src/docs/resources/technical-overview.md
src/docs/get-started/learn-more.md
src/_data/docs_cards.yml
```

**Comment by kwalrath** [comment]
Other related links:

```
$ fgrep -Rl flutter.github.io/samples src
src/docs/development/tools/sdk/release-notes/release-notes-1.7.8.md
src/docs/catalog/samples/index.md
src/docs/whats-new-archive.md
src/web.md
src/_data/sidenav.yml
```

**Comment by kwalrath** [comment]
I've just confirmed that, unless we're linking to a specific sample, we want to link to https://flutter.github.io/samples (not to the GitHub repo).

**Comment by leonardopaffi** [comment]
Hi @kwalrath, I redirected to https://flutter.github.io/samples as you mentioned in #4307

**Comment by kwalrath** [comment]
Oops, but the build failed... I'll look into it. It might not be specific to this PR.

**Pull request merged**
