### PR TITLE
Removing the GetX package from Options

### PR DESCRIPTION
**Pull request by filiph**
It looks like the package author makes some pretty wild claims* on social media. Removing the links, at least until we can verify that these claims are true.

*) The claims are about the package's official support from Google and/or usage by Google Product Managers — neither of which I'm aware of. I'd also like to verify the claims about performance (currently, they are backed only by a benchmark written by the author).

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
Thanks for that, @filiph

**Comment by OrlandoEduardo101** [comment]
Big day!

**Comment by BlackLeg15** [comment]
Make Flutter great again

**Comment by pauloantonelli** [comment]
finally! ¬¬.

**Comment by geronimoxd** [comment]
take out this shit! #bigday

**Comment by MaxweelFreitas** [comment]
Flutter really don't need of a toxic ambient. Let's cut it by root if is true!

**Comment by fabiojansenbr** [comment]
@filiph do you have any proof of this "wild claims"?

**Comment by fabioselau077** [comment]
I hope it's just a mistake and the package is added to the documentation again.
The package is one of the most used in the world by the Flutter community and removing the documentation will be a great loss for new users.

**Comment by pauloantonelli** [comment]
> I hope it's just a mistake and the package is added to the documentation again.
> The package is one of the most used in the world by the Flutter community and removing the documentation will be a great loss for new users.

I don't see it that way! I see that it is a way for new people to start correctly, with tools that follow good opensource practices.

**Comment by fabioselau077** [comment]
> > I hope it's just a mistake and the package is added to the documentation again.
> > The package is one of the most used in the world by the Flutter community and removing the documentation will be a great loss for new users.
> 
> I don't see it that way! I see that it is a way for new people to start correctly, with tools that follow good opensource practices.

From what I saw the people involved here in the post are from a community that always discussed with the author of the package.
Do you think doing this will contribute to the Flutter and open-source community in general?
Doing everything to harm a package designer who contributes much more to Flutter than you all do just by personal discussions doesn't help anything in the community, it just hurts.

**Comment by mkiisoft** [comment]
@fabiojansenbr yes, we have the proof.

**Comment by mkiisoft** [comment]
> Doing everything to harm a package designer who contributes much more to Flutter than you all do just by personal discussions doesn't help anything in the community, it just hurts.

Please, use a respectful language. This is a healthy community and we don't want toxicity.

**Comment by fabiojansenbr** [comment]
> @fabiojansenbr yes, we have the proof.

Where? Im Just trying to understand.

**Comment by gabrielscr** [comment]
@mkiisoft show us, i wanna see

**Comment by fabioselau077** [comment]
> > Doing everything to harm a package designer who contributes much more to Flutter than you all do just by personal discussions doesn't help anything in the community, it just hurts.
> 
> Please, use a respectful language. This is a healthy community and we don't want toxicity.

Doing everything to harm the author of a package just because you don't like it is not toxic, right?

**Comment by pauloantonelli** [comment]
> > > I hope it's just a mistake and the package is added to the documentation again.
> > > The package is one of the most used in the world by the Flutter community and removing the documentation will be a great loss for new users.
> > 
> > 
> > I don't see it that way! I see that it is a way for new people to start correctly, with tools that follow good opensource practices.
> 
> From what I saw the people involved here in the post are from a community that always discussed with the author of the package.
> Do you think doing this will contribute to the Flutter and open-source community in general?
> Doing everything to harm a package designer who contributes much more to Flutter than you all do just by personal discussions doesn't help anything in the community, it just hurts.
> I'm not saying that if he did something bad he shouldn't be punished but contributing to it just because he doesn't like the creator is a bad thing.

I think the issue is not community or package x or y, but the flutter is an environment with good practices from opensource, which always guarantee us software, tools ... reliable and also scalable.

**Comment by mkiisoft** [comment]
We should call a mod here and close this issue as the responses are not going anywhere. Thanks everyone for this effort.

**Comment by jehhxuxu** [comment]
> > @fabiojansenbr yes, we have the proof.
> 
> Where? Im Just trying to understand.

we need to explain? or the package?
image

**Comment by reness0** [comment]
brazilian guys celebrating that a brazilian package was officially removed, smh. Is that the way yall support the community? I mean, theres a plenty of ways to correct this issue, removing the package is a huge step towards back to the community. doesnt make sense: delete a WHOLE package just because of some BS that the creator has said

**Comment by OrlandoEduardo101** [comment]
> brazilian guys celebrating that a brazilian package was officially removed, smh. Is that the way yall support the community? I mean, theres a plenty of ways to correct this issue, removing the package is a huge step towards back to the community. doesnt make sense: delete a WHOLE package just because of some BS that the creator has said

man, did you read? it was only removed from the official flutter documentation.

**Comment by rkpontes** [comment]
Removing the Google package will favor a select group that people who are unable to compete honestly and use inefficient arguments.  I support Getx as it opens doors for new and experienced developers.

**Comment by jonataslaw** [comment]
Well, I'm seeing this now and:
I never said that Google officially supported the package (not least because it doesn't make sense, it is a package, not part of the SDK).
As for the performance issue, there are benchmarks in the repositories, but there is freedom to check.
I hope this is all a misunderstanding, I have always had the greatest respect for the flutter and dart team.
This will cause a revolution in the community, and this is bad.

**Comment by mkiisoft** [comment]
Everyone here: The package was not removed out of existence, only is not showing as Flutter supported/approved one in the site, that's all. Please, let's close comments for this PR.

**Comment by fabioselau077** [comment]
> brazilian guys celebrating that a brazilian package was officially removed, smh. Is that the way yall support the community? I mean, theres a plenty of ways to correct this issue, removing the package is a huge step towards back to the community. doesnt make sense: delete a WHOLE package just because of some BS that the creator has said

I just hovered over their profile and I noticed that they are from a group that has had discussions with the author of the package for years.
I just want to warn you that harming a fantastic plugin just by having a fight with the author is not good.
You are Brazilians, instead of helping a Brazilian who helps the community you are undoing just for the sake of ego.

**Comment by reness0** [comment]
> > brazilian guys celebrating that a brazilian package was officially removed, smh. Is that the way yall support the community? I mean, theres a plenty of ways to correct this issue, removing the package is a huge step towards back to the community. doesnt make sense: delete a WHOLE package just because of some BS that the creator has said
> 
> man, did you read? it was only removed from the official flutter documentation.

yeah, indeed, i get it wrong, sorry, thx anyway

**Comment by jehhxuxu** [comment]
> Removing the Google package will favor a select group that people who are unable to compete honestly and use inefficient arguments. I support Getx as it opens doors for new and experienced developers.

select group? this is an efficient argument? this is true?
image

**Comment by Hixie** [comment]
Folks, please recall our [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md), which is that we must all "Be kind. Be courteous. Be welcoming.".

It's not enough just to be polite. You have to be actively friendly and welcoming. Many of the comments here are unnecessarily antagonistic, aggressive, or generally less than entirely friendly.

**Comment by sfshaza2** [comment]
Thanks for locking, @Hixie! I was just coming to do that.

**Pull request merged**
