### PR TITLE
Update path-mac-linux.md

### PR DESCRIPTION
**Pull request by Hixie**
Based on https://github.com/flutter/flutter/issues/11974

### CODE REVIEW

**Comment by Hixie** [comment]
cc @LarkAscending

**Comment by Sfshaza** [comment]
LGTM!

**Comment by LarkAscending** [comment]
Good addition! 
LGTM.

A nit - the list numbering scales better when we leverage Markdown's automatic numbering feature. It's no problem and I don't think the CONTRIBUTING guide has anything to say about it. So this is FYI for future reference only.

**Comment by Hixie** [comment]
Yeah, I wondered about that. I figured this would make it easier to read while editing, and since it's so short... but yeah.

**Pull request merged**
