### PR TITLE
Add to app prebuilt binaries as xcframeworks

### PR DESCRIPTION
**Pull request by jmagman**
Update add-to-app iOS instructions to use `flutter build ios-framework --xcframework` in anticipation of Apple Silicon support.

`--xcframework` became the default as of https://github.com/flutter/flutter/pull/69720.

New image:
embed-xcode
Samples also updated at https://github.com/flutter/samples/pull/582.

### CODE REVIEW

**Comment by xster** [comment]
LGTM.

Did you optipng the image? Slightly surprised the similar dimension image doubled in size.

**Comment by jmagman** [comment]
> Did you optipng the image? Slightly surprised the similar dimension image doubled in size.

I tried `npx gulp compress-images --path` based on https://github.com/dart-lang/site-shared/blob/master/doc/images.md but maybe it didn't do anything.

**Comment by xster** [comment]
Try https://flutter.github.io/assets-for-api-docs/#optimization

**Review by xster — APPROVED** [review]

**Comment by jmagman** [comment]
> Try https://flutter.github.io/assets-for-api-docs/#optimization

It's 150% larger instead of 190% now, but it's still only 162KB.

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Pull request merged**
