### PR TITLE
Remove addFrameCallback from website

### PR DESCRIPTION
**Pull request by goderbauer**
Part of https://github.com/flutter/flutter/issues/7793.

### CODE REVIEW

**Comment by goderbauer** [comment]
@Hixie Is this replacement actually correct?

**Comment by abarth** [comment]
LGTM

**Comment by goderbauer** [comment]
@mit-mit is in the process of fixing the other link-issues reported by travis.

**Comment by mit-mit** [comment]
Thanks @goderbauer

**Comment by Hixie** [comment]
yes, lgtm

**Pull request merged**
