### PR TITLE
Add a link to China instructions

### PR DESCRIPTION
**Pull request by InMatrix**

### CODE REVIEW

**Comment by mit-mit** [comment]
This seems to visually too distinct and upfront for a note that applies to less than the majority of our users.

**Comment by InMatrix** [comment]
@mit-mit This message is likely to apply to the majority of our new users this week, so I'd like to make it easy to notice. I'm happy to downplay it next week.

**Comment by Hixie** [comment]
I don't think it's _that_ visually distinct. Certainly LGTM for this week, but I it may even be reasonable in general going forward, IMHO.

**Comment by InMatrix** [comment]
I'm going to merge this. Sorry about having to do it without consensus. We can certainly revisit the placement of the message next week.

**Comment by mit-mit** [comment]
No worries, I'm fine with this for now

**Pull request merged**
