### PR TITLE
Update firebase.json to add a "go" design doc

### PR DESCRIPTION
**Pull request by fzyzcjy**
I followed the [official guide](https://docs.google.com/document/d/1SFRO8U2toOlAaZ38dsuEU7Wm5fn41wvBCWKiwADqfmw/edit) and create a design doc https://docs.google.com/document/d/1FuNcBvAPghUyjeqQCOYxSt6lGDAQ1YxsNlOvrUx0Gko/edit#, and according to the guide, one step is to make a PR here to add a link, so I come :)

_Issues fixed by this PR (if any):_ Fixes #ISSUE-NUMBER

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

Btw I name it "sixty-fps" not "premption-for-60-fps", because I realized my solution is currently not a typical "preemption" anymore.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by fzyzcjy** [comment]
@domesticmouse So... What should I do now? Seems everything is green but I have not found a button to click to merge.

**Comment by domesticmouse** [comment]
@sfshaza2 should be along to land it soon. 😎

**Comment by fzyzcjy** [comment]
Thanks!

**Review by khanhnwin — APPROVED** [review]

**Comment by khanhnwin** [comment]
Landed!

**Pull request merged**
