### PR TITLE
adding missing createArgsCodec override in doc of platform-views - iOS

### PR DESCRIPTION
**Pull request by GJJ2019**
_Description of what this PR is changing or adding, and why:_

_Issues fixed by this PR (if any):
- adding missing createArgsCodec override in doc of platform-views - ios

## Presubmit checklist

- [ ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ ] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by atsansone** [comment]
@domesticmouse : Could you check this code? Thanks!

**Comment by mossmana** [comment]
Adding @stuartmorgan, who can help find a reviewer for this. I'm probably not the best contact for iOS related code.

**Comment by mossmana** [comment]
Also, @GJJ2019 would it be possible to link to the associated issue on this PR?

**Comment by GJJ2019** [comment]
> Also, @GJJ2019 would it be possible to link to the associated issue on this PR?

I'm not sure there are issues for this but just codec doc was missing so i created the pr. Shall I file issue as well ?

**Comment by stuartmorgan** [comment]
That's an optional part of the protocol, and it's only used if there are view creation arguments, which there aren't in this example, so the premise that the code is missing is not correct. It's not there because it would be dead code. Closing since the example is correct—and less verbose—as-is.

(Also, the Obj-C code in this PR is not at all correct; it's in the wrong part of the object definition, and on the wrong object.)

**Comment by GJJ2019** [comment]
but if i try `creationParamsCodec: const StandardMessageCodec(),` in uikitview then arg returns null for ios so createargscodec is must 

see this https://docs.flutter.dev/platform-integration/android/platform-views
https://docs.flutter.dev/platform-integration/ios/platform-views

**Comment by stuartmorgan** [comment]
> then arg returns null for ios so createargscodec is must

Please re-read my comment above about this example.

**Comment by GJJ2019** [comment]
ok i understand now thx

**Pull request closed without merging**
