### PR TITLE
Added the missing option "Google APIs" in Data & Backend tab

### PR DESCRIPTION
**Pull request by abhinav-m22**
_Description of what this PR is changing or adding, and why:_

Added the missing option "Google APIs" in Data & Backend tab oo the sidenav of the website.

_Issues fixed by this PR (if any):_

* Fixes the issue - #8418 

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by domesticmouse** [comment]
Please sign the CLA. We can't land your PR without it. 😏

**Comment by abhinav-m22** [comment]
I've signed the CLA, but it didn't reflect on the PR. Please check it once.

**Comment by abhinav-m22** [comment]
> Please sign the CLA. We can't land your PR without it. 😏

Done! 👍

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Pull request merged**
