### PR TITLE
Add js library hashes to ensure library is from a trusted source

### PR DESCRIPTION
**Pull request by drewroengoogle**
_Description of what this PR is changing or adding, and why:_
* Adds hash values to the js libraries in `base.html` to ensure that the library is from a trusted source

_Issues fixed by this PR (if any):_
* https://github.com/flutter/website/security/code-scanning/36
* https://github.com/flutter/website/security/code-scanning/37
* https://github.com/flutter/website/security/code-scanning/38
* https://github.com/flutter/website/security/code-scanning/39

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by sfshaza2 — COMMENTED** [review]
This looks good to me, but can you verify, @khanhnwin?

**Comment by khanhnwin** [comment]
LGTM! Though, stable build is failing on a dart analyze. Let me fix that so that we can merge the fix in from main.

**Comment by drewroengoogle** [comment]
Sounds good, thank you both! Is there any chance the build failure might be related to the new `url_launcher` package? https://pub.dev/packages/url_launcher/changelog

**Comment by khanhnwin** [comment]
Yep, that's exactly the problem!

**Comment by khanhnwin** [comment]
Just merged from main to resolve the failed dart analyze from `url_launcher`! Should be good to go as long as builds pass @sfshaza2! Thank you @drewroengoogle!

**Review by domesticmouse — APPROVED** [review]

**Review by khanhnwin — APPROVED** [review]

**Pull request merged**
