### PR TITLE
document add-to-app for web

### PR DESCRIPTION
**Pull request by yjbanov**
_Description of what this PR is changing or adding, and why:_

The web supports add-to-app via multi-view. This PR updates the add-to-app docs to include web. I also attempt to improve some existing text.

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @johnpryan RE refactoring all things web

**Comment by johnpryan** [comment]
LGTM

**Review by johnpryan — APPROVED** [review]

**Comment by johnpryan** [comment]
Helps resolve https://github.com/flutter/website/issues/8842

**Review by sfshaza2 — APPROVED** [review]
LGTM! Thanks for doing this, @yjbanov! I was tempted to replace "not practical" with "impractical", but that's just me being pedantic. Very useful!

**Pull request merged**
