### PR TITLE
Add instructions to uninstall flutter

### PR DESCRIPTION
**Pull request by Sameerkash**
related to #5695 

cc @Sfshaza

### CODE REVIEW

**Comment by Sameerkash** [comment]
This might need a bit more polishing, happy to follow up on changes required, also need a form at the end of the page I guess!

**Comment by jayoung-lee** [comment]
Filed a bug to follow up https://github.com/flutter/website/issues/5750 so the form does not hold up the page

**Comment by Sameerkash** [comment]
> @jayoung-lee, would this be a form you would be interested in creating/having? It does seem like a good idea...

Sure I can take it up, but I thought it'd need some internal discussion. 


Also where should the data go ?

Is a Google form okay ? Or should it be a part of the site ?

**Comment by Sameerkash** [comment]
@Sfshaza How is the rest of the PR? Any idea why the tests are failing? Should I push the submodule commit file too?

**Comment by Sameerkash** [comment]
@Sfshaza Thanks!, sure, it can wait till IO is over, I'll implement your suggested changes and try to improve it more.

**Comment by sfshaza2** [comment]
I'm about to freeze the website for infrastructure updates, so this will have to wait until later. Closing.

**Pull request closed without merging**
