### PR TITLE
Feature baseurl

### PR DESCRIPTION
**Pull request by liudonghua123**
_Description of what this PR is changing or adding, and why:_

The official Jekyll based site do not support baseurl. I tried to make it.

_Issues fixed by this PR (if any): https://github.com/flutter/website-cms/issues/107.

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by sfshaza2** [comment]
Can you weigh in on this pr, @parlough?

**Comment by parlough** [comment]
Thanks for the PR @liudonghua123! I won't have a chance to take a look at this today, but I'll make sure to get back to it tomorrow.

**Comment by sfshaza2** [comment]
@khanhnwin, Parker is on leave for June. Can you take a look?

**Comment by khanhnwin** [comment]
Thanks @liudonghua123! I tried staging this on my Firebase Hosting project, but unfortunately it seems to have broken images: [example 1](https://yenkhanh-flutter.web.app/data-and-backend/state-mgmt/declarative), [example 2](https://yenkhanh-flutter.web.app/add-to-app/android/add-flutter-fragment). I also can't seem to access https://liudonghua123.github.io/flutter_website/ to cross-check.

I see that you're serving via GitHub pages under liudonghua123.github.io/flutter_website/ which requires to specify the `flutter_website` portion of the path. I don't believe it should be needed as we're serving from the root of our site url docs.flutter.dev. If my understanding there is correct, we can go ahead and close this PR. (thank you for your effort!!)

To get it to work on GitHub pages, you could stick with this existing solution. Alternatively, are you able to replace the `url` variable in the site [`_config.yml`](https://github.com/flutter/website/blob/main/_config.yml) with GitHub Pages baseurl path and then use `make build`?

**Comment by liudonghua123** [comment]
@khanhnwin Yes, you are right. The  official doc.flutter.dev site is served under root path. However, if someone want to build the docs under a baseurl without other strategies like nginx rewrite, it would be difficult or impossible. Support baseurl in static site is a common scenario and it doesn't affect other parts of the site in my opinion.
I will fix the access problem of https://liudonghua123.github.io/flutter_website/ soon.

**Comment by khanhnwin** [comment]
Thanks for the clarification @liudonghua123! Discussed this with a few folks and we won't be adding this baseurl feature support to the website infrastructure at this time due to the complexity.

However, we want to make sure that you have access to docs.flutter.dev so that you aren't forced to host the docs site independently. Can you please share additional details is to why you aren't able to access it? I'll take a look into it. Thanks!

**Comment by liudonghua123** [comment]
I fixed the access problem of https://liudonghua123.github.io/flutter_website/, I found the page settings was reverted or reset for unknown reasons, and I tried to configure again. Now it should be working.
 
image

And I tested the links you provided and it worked in my own gh-pages site.

[/data-and-backend/state-mgmt/declarative/](https://liudonghua123.github.io/flutter_website/data-and-backend/state-mgmt/declarative/), [/add-to-app/android/add-flutter-fragment](https://liudonghua123.github.io/flutter_website/add-to-app/android/add-flutter-fragment).

**Comment by liudonghua123** [comment]
@khanhnwin 
> However, we want to make sure that you have access to docs.flutter.dev so that you aren't forced to host the docs site independently. Can you please share additional details is to why you aren't able to access it? I'll take a look into it. Thanks!

I could not visit https://docs.flutter.dev always before, but it seems the accessibility of this site has improved a lot recently, and I could not reproduce this inaccessible problem now. (Sorry for my poor English 😃)

**Comment by khanhnwin** [comment]
The links worked for me as well, apologies for not being clearer. It was specifically just the image link references on the page that was broken. i.e. on [/data-and-backend/state-mgmt/declarative/](https://liudonghua123.github.io/flutter_website/data-and-backend/state-mgmt/declarative/) it's rendering the html text instead of an image: 

`

`

I'm glad to hear that you're having an easier time reaching docs.flutter.dev more reliably now! Of course, please do [let us know](https://github.com/flutter/website/issues/new/choose) if you have reachability issues with the site again. Your English is also great, btw. 😄 

I'll go ahead and close this PR since we won't be implementing baseurl, but thank you for your work and contributing! If we decide to implement it in the future, we'll for sure be reusing a lot of the work you've already done.

**Pull request closed without merging**
