### PR TITLE
Fix incorrect assetBase documentation

### PR DESCRIPTION
**Pull request by dowski**
_Description of what this PR is changing or adding, and why:_ Fixing a documentation bug.

_Issues fixed by this PR (if any):_ #11341 

_PRs or commits this PR depends on (if any):_ N/A

## Presubmit checklist

- [ ] This PR is marked as draft with an explanation if not meant to land until a future stable release.
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Comment by dowski** [comment]
So actually, I just double-checked my code and the doc change I made is not right. `assetBase` is actually an argument to engine intializer `initializeEngine`, not `_flutter.loader.load()`.

**Comment by dowski** [comment]
The `assetBase` arg to `initializeEngine` is still documented, although the whole page that contains those docs say they are for legacy versions of Flutter.

https://docs.flutter.dev/platform-integration/web/initialization-legacy#initializing-the-engine

**Comment by dowski** [comment]
Okay, I tweaked this PR to make it correct. It does feel like some restructuring of the docs is in order (`assetBase` is nicely documented on the "legacy" initialization page). Maybe that's part of the goal of #11320?

**Comment by dowski** [comment]
*Sigh*

I think this is doc change is still wrong, after reading more of the code.

As long as you **don't supply a custom `onEntryPointLoaded` callback**, you *can* supply `assetBase` in the `config`. It will get passed to `initializeEngine` [here](https://github.com/flutter/engine/blob/05cb5d7f7939da58ef9897997004f181f2699075/lib/web_ui/flutter_js/src/entrypoint_loader.js#L63-L65).

If you **do supply a custom `onEntryPointLoaded` callback**, you must manually pass it the `config` that was passed to `_flutter.loader.load()` (or instead of passing it there? -- I'm not clear on that).

----

Maybe the real fix here is to document that the `initializeEngine` call should receive the same config that `_flutter.loader.load()` receives? What do you all think?

**Comment by dowski** [comment]
I'm going to close this and come back w/ a fresh PR focused on what I discovered above.

**Comment by johnpryan** [comment]
Thanks for sharing your findings @dowski! I haven't validated this, but am I understanding correctly that when you configure`assetBase` in`flutter.loader.load()`, you need to also provide it to the `onEntrypointLoaded` callback? cc: @ditman @eyebrowsoffire

**Comment by dowski** [comment]
Hey @johnpryan - you're welcome.

It's more like if you pass an `onEntryPointLoaded` callback, `assetBase` gets ignored unless you manually pass it to the `initializer. initializeEngine` call in the callback.

I wound up filing a new focused bug that includes sample code:

https://github.com/flutter/flutter/issues/158041

I didn't file it here in the `website` repo as I'm not sure it's strictly a documentation issue. The API feels plain hard to use.

**Pull request closed without merging**
