### PR TITLE
Update _ios-setup.md

### PR DESCRIPTION
**Pull request by divinebird**
Add description for prepare sdk in iOS using mac port

### CODE REVIEW

**Comment by divinebird** [comment]
I signed it!

**Comment by divinebird** [comment]
I signed it!

**Comment by christopherfujino** [comment]
@divinebird I'm not a mac ports expert, but is the duplication on line 104 a typo?

>     `$ port port deactivate libusbmuxd`

**Comment by sfshaza2** [comment]
Hi, @divinebird! Thanks so much for your PR! I did talk to folks internally who informed me that we are moving away from our dependence on Mac Port *and* homebrew. It's been pointed out that we wouldn't support an issue filed against the Mac Port install of Flutter. So I'm going to close this PR. Thanks again!

**Pull request closed without merging**
