### PR TITLE
Update firebase.json

### PR DESCRIPTION
**Pull request by chunhtai**

### CODE REVIEW

**Review by johnpryan — APPROVED** [review]

**Review by domesticmouse — APPROVED** [review]

**Review by sfshaza2 — DISMISSED** [review]
Alphabetically, it should be one line higher, but it's close enough.  :D LGTM

**Review by sfshaza2 — CHANGES_REQUESTED** [review]
Oops! No, this PR is currently trying to merge into our archived master. Can you update the PR (or issue a new one) that merges into main?

**Comment by chunhtai** [comment]
Moved one line up and point to main branch

**Review by sfshaza2 — APPROVED** [review]
That was quick! LGTM!

**Pull request merged**
