### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by weijiechai**

### CODE REVIEW

**Comment by weijiechai** [comment]
@googlebot I signed it!

**Review by sfshaza2 — COMMENTED** [review]
I see only the addition of an empty line. Closing.

**Comment by weijiechai** [comment]
You can see here that the missing line broke the link in the documentation.
https://flutter.dev/docs/get-started/install/windows

**Comment by sfshaza2** [comment]
Wow, I have never seen that before! Thanks for catching it, @weijiechai! LGTM

**Pull request merged**
