### PR TITLE
Update navigate-with-arguments.md

### PR DESCRIPTION
**Pull request by scott8013**
if not add Screen args.[xxx] will report an error.

_Description of what this PR is changing or adding, and why:_

_Issues fixed by this PR (if any):_ Fixes #ISSUE-NUMBER

## Presubmit checklist
- [ ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ ] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by domesticmouse** [comment]
Can you please create an issue with the reproduction of the issue you are seeing? This type declaration should not be required.

**Comment by sfshaza2** [comment]
@atsansone, can you explain these merges you do? I've seen this on at least one PR and it's confusing. I don't see why it's needed. @domesticmouse

**Comment by atsansone** [comment]
@sfshaza2 : The merges are updating the branch to make it up to date with `main`. I just click the **Update branch** button when the branch is out of date.

**Comment by domesticmouse** [comment]
@sfshaza2 updating the PR makes for a much clearer idea of what landing the PR will do. If linear history is enforced, these updates would be required before landing. This is the state of dart-services, for example.

**Comment by atsansone** [comment]
@scott8013 : Can you please sign the CLA and provide the information that @domesticmouse requested? Thank you for your help!

**Comment by sfshaza2** [comment]
@atsansone @domesticmouse, ahhh, that makes sense, I've done that myself but hadn't noticed the commit for it.

**Comment by sfshaza2** [comment]
This PR is starting to get stinky. @scott8013, if you believe it to still be needed, can you follow @domesticmouse's request and file an issue first? Closing for now.

**Pull request closed without merging**
