### PR TITLE
Update supported platforms for 3.22

### PR DESCRIPTION
**Pull request by parlough**

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
This lgtm, but is still in draft mode.

**Comment by sfshaza2** [comment]
Can we land this, @parlough?

**Review by sfshaza2 — APPROVED** [review]
lgtm (again)

**Comment by parlough** [comment]
I need to make some final adjustments then I can land this.

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Pull request merged**
