### PR TITLE
[Next stable] Update documentation for new location of linux source

### PR DESCRIPTION
**Pull request by robert-ancell**
The Linux directory was changed in https://github.com/flutter/flutter/pull/153812.

Land once https://github.com/flutter/flutter/commit/8925e1ffdfe880b06a8bc5877f017083d6652f5b is in stable.

### CODE REVIEW

**Comment by robert-ancell** [comment]
I'm not sure if this is required - the windows examples don't seem to mention the runner directory.

**Comment by stuartmorgan** [comment]
> I'm not sure if this is required - the windows examples don't seem to mention the runner directory.

The instructions are IDE-specific. VS doesn't display the source files using the directory hierarchy, so the Windows instructions don't have a path, whereas VS Code does use the hierarchy, so we should.

**Review by parlough — APPROVED** [review]
Thanks! Looks good to me.

We'll make sure this gets landed once the linked change lands in `stable`.

**Comment by sfshaza2** [comment]
@robert-ancell, the PR was merged back in September, but I gather it's not in the stable release yet?

**Comment by robert-ancell** [comment]
> @robert-ancell, the PR was merged back in September, but I gather it's not in the stable release yet?

Correct, this is not in stable yet.

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Comment by sfshaza2** [comment]
I'm landing this, as the (quiet) release happened yesterday.

**Pull request merged**
