### PR TITLE
Tweak VS Code format text

### PR DESCRIPTION
**Pull request by DanTup**
Minor tweak - VS Code only supports full document formatting (so selection/position of click doesn't matter) and it's labelled "Format Document" on the context (Or Edit) menu.

### CODE REVIEW

**Comment by mit-mit** [comment]
Lgtm

**Comment by DanTup** [comment]
Looks like Travis is upset:

```
Retrying fetcher due to error (2/4): Bundler::HTTPError The checksum of /info/nokogiri does not match the checksum provided by the server! Something is wrong (local checksum is "\"a080a1775e4c3f8b72707ef6a2e071b4\"", was expecting "\"5512cda1-50280\"")....
Retrying fetcher due to error (3/4): Bundler::HTTPError The checksum of /info/http_parser.rb does not match the checksum provided by the server! Something is wrong (local checksum is "\"a080a1775e4c3f8b72707ef6a2e071b4\"", was expecting "\"5512cda1-50280\"").....
Retrying fetcher due to error (4/4): Bundler::HTTPError The checksum of /info/spoon does not match the checksum provided by the server! Something is wrong (local checksum is "\"a080a1775e4c3f8b72707ef6a2e071b4\"", was expecting "\"5512cda1-50280\"")..
The checksum of /info/thin does not match the checksum provided by the server!
Something is wrong (local checksum is "\"a080a1775e4c3f8b72707ef6a2e071b4\"",
was expecting "\"5512cda1-50280\"").
The command "./tool/travis.sh" exited with 17.
```

Looks like a dependency being pulled has a bad checksum? :/

**Comment by DanTup** [comment]
Possibly related; though I'm not sure how to fix (seems like an issue at their end?)

https://github.com/bundler/bundler/issues/4472

**Comment by DanTup** [comment]
Never mind; forcing it seems to have fixed it - I guess it was temporary. Looks like your PR branch failed with the same issue so I've restarted that on Travis too.

**Comment by Sfshaza** [comment]
Thanks, @DanTup!!!

**Pull request merged**
