### PR TITLE
Update polar coordinate gist on 'Architectural Overview' page

### PR DESCRIPTION
**Pull request by parlough**
Eventually it would be nice to incorporate or test this on the site (https://github.com/flutter/website/issues/6912), but for now this updates the gist to null safety, by just copying the latest changes from the [original example on flutter/flutter](https://github.com/flutter/flutter/blob/master/examples/layers/rendering/src/sector_layout.dart).

Staged: https://dartpad.dev/?id=596b1d6331e3b9d7b00420085fab3e27

I also cleaned up the filename and title of the gist: https://gist.github.com/parlough/596b1d6331e3b9d7b00420085fab3e27

Fixes https://github.com/flutter/website/issues/8474

### CODE REVIEW

**Comment by domesticmouse** [comment]
Who owns the original gist?

**Comment by parlough** [comment]
Tim does: https://gist.github.com/timsneath/0f020197a5d4c980342d5c7d9e935cee

I'd like to move to something besides the gist, but don't have time currently.

**Comment by domesticmouse** [comment]
> I'd happily adjust this to one made by https://gist.github.com/flutterdevrelgists if that's preferred. I don't have access though.

For now I'm happy to land this PR as is while @RedBrogdon and I argue behind the scenes about how best to manage this going forwards =)

**Comment by parlough** [comment]
Sounds good, thanks!

I'll be tracking future improvements to this situation/sample in https://github.com/flutter/website/issues/6912.

**Pull request merged**
