### PR TITLE
Adding `/go/games-revenue` link for games revenue

### PR DESCRIPTION
**Pull request by sfshaza2**
As per discussions with PM and marketing.

### CODE REVIEW

**Review by parlough — COMMENTED** [review]
Is the doc intended to be private?

Also do you want it as a top-level link or a go link like the PR title mentions?

**Comment by atsansone** [comment]
This should also be against the games-v2 branch. I'll update that branch soon then you can change the PR upstream.

**Comment by sfshaza2** [comment]
@parlough, I think they pefer a go link, but it could possibly be either. I don't think it's a private page.

**Comment by parlough** [comment]
I didn't have access to it, so looks like it's an invite only doc.

**Comment by parlough** [comment]
Was a conclusion ever reached here? The slides at the target link aren't available for viewing without an invite. If we have permission and want to share them, can we make our own public copy?

\cc @sfshaza2 @zoeyfan

**Comment by atsansone** [comment]
This is blocked until Zoey gets back on Nov 21.

**Comment by zoeyfan** [comment]
I couldn't seem to review the staged change here:  "https://flutter-docs-prod--pr9771-games-q2ru98g3.web.app/"
Is this referring to the slides for the admob and ux presentation? If so, I believe @kkboateng helped create that link. Kelvin, would you please advise here?

**Comment by domesticmouse** [comment]
@zoeyfan the appropriate link would be https://flutter-docs-prod--pr9771-games-982635vs.web.app/games-revenue which links to a document that isn't public.

**Comment by zoeyfan** [comment]
Just to confirm, by non-public, does it mean that people have to request
permission when they want to access the content? Or does it mean that  as
long as they have a gmail account, they can access the content.

By the way, would you please advise if there is anyway we can create public
content with a Google owned account?


Thanks, Zoey

**Comment by kkboateng** [comment]
Hi - I just published the deck to the web so that anyone can view the
content. The new link is here ->
https://docs.google.com/presentation/d/e/2PACX-1vQHsmBMt_l8x9yhQpANPp-uaaa7lcII8VKSCiCHzelv86k5vydeVqIJsHCkgFQ6ypeMFmBjd9aGUypL/pub?start=false&loop=false&delayms=3000&slide=id.g1f9fbfe3213_0_2815

Can we update this by any chance and see if that solves the issue?

Best,
Kelvin
[image: Google Logo]
Kelvin Boateng
Product Marketing Manager
***@***.***
+16502534157
x

**Comment by parlough** [comment]
Thanks @kkboateng, however when I open it, it says "You need permission to access this published document." whether I'm logged in or not.

Also, would it be fine for this to be under `/go/games-revenue` or something like that instead of just `/games-revenue`? I'm a bit hesitant to add a top-level `/games-revenue` redirect.

**Comment by kkboateng** [comment]
Hi - Yes. Totally fine to update to /go/games-revenue if you're more
comfortable with that.

I'll continue to work on making the document accessible to everyone. Let me
work on that.

Best,
Kelvin
[image: Google Logo]
Kelvin Boateng
Product Marketing Manager
***@***.***
+16502534157
x

**Comment by domesticmouse** [comment]
> Hi - I just published the deck to the web so that anyone can view the content. The new link is here -> https://docs.google.com/presentation/d/e/2PACX-1vQHsmBMt_l8x9yhQpANPp-uaaa7lcII8VKSCiCHzelv86k5vydeVqIJsHCkgFQ6ypeMFmBjd9aGUypL/pub?start=false&loop=false&delayms=3000&slide=id.g1f9fbfe3213_0_2815 Can we update this by any chance and see if that solves the issue? 

Hey Kelvin, the slide deck link as currently specified lands the user on Slide 12 of the deck. Should we change the URL so that the user opens the deck on Slide 1?

**Comment by kkboateng** [comment]
Yes, we should! hopefully the URL below does the trick?

https://docs.google.com/presentation/d/e/2PACX-1vQfEXcGkkS1jb1pVcBz0wZxLMMtHikAc3ZnQZviorR9x99Kdo64TJKjjk2BvR8dQR7-Q01EVXKYjID6/pub?start=false&loop=false&delayms=3000

Best,
Kelvin
[image: Google Logo]
Kelvin Boateng
Product Marketing Manager
***@***.***
+16502534157
x

**Comment by sfshaza2** [comment]
I am now able to open this doc (without logging in) in an incognito window. I tried on two different browsers.

**Comment by kkboateng** [comment]
Hooray!
[image: Google Logo]
Kelvin Boateng
Product Marketing Manager
***@***.***
+16502534157
x

**Review by parlough — APPROVED** [review]
Thanks everyone for figuring that out!! Looks good to me.

I updated the redirect and the target link so `flutter.dev/go/games-revenue` will open to the 1st page of the slides linked.

Do note that the slides say "Proprietary + Confidential" in the upper right. Might be fine, not sure. But this is ready to go from my end :)

**Comment by kkboateng** [comment]
Thanks, Parker. We'll likely only keep this as a temp solution and:

   1. Update slides to remove that signage, and
   2. find a more permanent hosting solution

but we're good to go for now!

Best,
Kelvin
[image: Google Logo]
Kelvin Boateng
Product Marketing Manager
***@***.***
+16502534157
x

**Pull request merged**
