### PR TITLE
load languages dynamically

### PR DESCRIPTION
**Pull request by adnanjpg**

### CODE REVIEW

**Comment by adnanjpg** [comment]
@googlebot I signed it!

**Review by sfshaza2 — CHANGES_REQUESTED** [review]
Hi, @adnanjpg! When you update code on the site, you need to refresh the code_excerpts. You can find more info here:  https://github.com/dart-lang/site-shared/blob/master/doc/code-excerpts.md

**Comment by sfshaza2** [comment]
FYI. @adnanjpg, I am freezing the website repo next Friday (Aug 13th). We must either land this by then or you'll have to submit another PR. (We are changing the website infrastructure, so all remaining PRs will be landed or closed.)

**Comment by sfshaza2** [comment]
Closing

**Pull request closed without merging**
