### PR TITLE
Adding a banner for a link to user survey

### PR DESCRIPTION
**Pull request by jayoung-lee**
The link to the survey will go live on Monday, Oct 29. I will comment here once it is 100% ready!

### CODE REVIEW

**Comment by jayoung-lee** [comment]
The link to the survey is now live and it's ready to go.

**Comment by sfshaza2** [comment]
@jayoung-lee, this PR puts the banner on the docs page only. Don't you want it on every page? I've asked @chalin to rework this, if that's OK.

**Comment by sfshaza2** [comment]
@chalin will also add it to the new site.

**Comment by chalin** [comment]
Hi @jayoung-lee: the updated PR is #1581

**Pull request closed without merging**
