### PR TITLE
Game Toolkit v2 updates

### LINKED ISSUE #9668: Update the existing Games Toolkit page (Include adding links to new templates and removing old template)
Update the current [Casual Games Toolkit](https://docs.flutter.dev/resources/games-toolkit) page content including updating copy and links to new templates.

Fixed by #9780

### PR DESCRIPTION
**Pull request by parlough**
This is the final PR for the Games Toolkit v2.

**Staged:** https://flutter-docs-prod--pr9782-games-v2-zvcen6xm.web.app/

Fixes #9668

### CODE REVIEW

**Comment by atsansone** [comment]
@parlough : This isn't the right branch. The correct one would be atsansone/fix-9668. That has the latest.

**Comment by parlough** [comment]
This is just testing/staging the total combined changes in `games-v2` here.

**Comment by atsansone** [comment]
All work has been approved in prior PRs: https://github.com/flutter/website/pull/9758, https://github.com/flutter/website/pull/9730, https://github.com/flutter/website/pull/9678, https://github.com/flutter/website/pull/9780, https://github.com/flutter/website/pull/9781, and https://github.com/flutter/website/pull/9744

**Comment by parlough** [comment]
@atsansone It looks like you may have accidentally overwrote your latest changes to the games toolkit page when you force pushed. Would you like me to cherry-pick the commit back to this branch?

**Comment by atsansone** [comment]
@parlough : Yes please.

**Comment by parlough** [comment]
Changing to draft to prevent accidental squash merging.

We want to temporarily reenable non-squash merging (rebase or merge) to better preserve history when merging. \cc @sfshaza2 @atsansone

**Comment by parlough** [comment]
**Note for those reviewing.** Please do not Squash and merge this PR. Instead use Rebase and merge.

**Review by atsansone — APPROVED** [review]

**Pull request merged**
