### PR TITLE
Clarifying the update your path instructions

### PR DESCRIPTION
**Pull request by sfshaza2**
Fixes https://github.com/flutter/website/issues/4878

While I was at it, I removed all non-essential uses of "may" with either "might" or "could", as was appropriate. This is in accordance with the GDSG.

### CODE REVIEW

**Review by atsansone — CHANGES_REQUESTED** [review]
Please separate this into two PRs. I had a really difficult time seeing the change you made against the original issue. Thanks!

**Comment by sfshaza2** [comment]
@atsansone, that would be an enormous amount of work. Perhaps focus on the install files, which are where the actual work is.

**Comment by atsansone** [comment]
Not too much work. Just tested this.

```terminal
gh pr checkout 8951                                           // Requires GitHub CLI
git checkout -b fix-might upstream/set-path                   // Make new branch from PR
git reset --soft HEAD^                                        // Return all files to stage
git restore --staged src/get-started/install/_path-mac.md     // Remove file from stage
git restore --staged src/get-started/install/_get-sdk-mac.md  // Remove file from stage
git checkout -- .                                             // Clear unstaged files
git commit -m "Update may to might"                           // Create new commit
git push origin fix-might                                     // Push new commit
git checkout set-path                                         // Checkout the PR again
git reset                                                     // Unstage all files in the PR
git add src/get-started/install/_*mac.md                      // Stage the macOS files
git checkout -- .                                             // Remove the other unstaged files
git commit --amend                                            // Create new commit on original PR
git push origin set-path --force-with-lease                   // Push new commit to original PR
```

**Review by atsansone — APPROVED** [review]
Let's land it. If we need to revisit, we can.

**Comment by sfshaza2** [comment]
Thanks, Tony. I'll try not to do that to you again. It's definitely part of my OCD.  :D

**Pull request merged**
