### PR TITLE
Fix links in desktop.md

### PR DESCRIPTION
**Pull request by mit-mit**
Fixing broken links I introduced in https://github.com/flutter/website/pull/5952

### CODE REVIEW

**Comment by mit-mit** [comment]
Merging to fix links, TBR @sfshaza2

**Comment by mit-mit** [comment]
Oh, nevermind, I don't have write access so can't merge without a review. Can you approve @sfshaza2 ? And please merge on my behalf as I'm heading out early today.

**Review by GaryQian — APPROVED** [review]
LGTM!

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Pull request merged**
