### PR TITLE
Add initial pages for Architecture guidance

### PR DESCRIPTION
**Pull request by ericwindmill**
Adds the first 3 pages of the architecture guidance documentation. 

This PR **does not** add these pages to the side nav.  There will be another PR that fast follows this one and contains a couple more pages of docs, as well as the the side nav. 

FYI: These pages have been reviewed by @sfshaza2 in a Google Doc. Of course additional reviews are welcomed.

URL for added pages: https://flutter-docs-prod--pr11300-ew-app-architecture-first-xhdhrb5w.web.app/app-architecture

### CODE REVIEW

**Comment by miquelbeltran** [comment]
Not a full review yet, but I noticed that this table did not render correctly for me: 
image

Here I am using Chrome on macOS

**Review by sfshaza2 — COMMENTED** [review]
Hi @ericwindmill! Overall, this looks good. However, are some pages missing? The prev/next progression through the pages ended at the Guide, so I had to manually type in the recommendations page.

**Comment by sfshaza2** [comment]
Also, Miguel mentioned a table. I didn't see a table. Maybe that was another page I somehow missed?

**Comment by ericwindmill** [comment]
> Hi @ericwindmill! Overall, this looks good. However, are some pages missing? The prev/next progression through the pages ended at the Guide, so I had to manually type in the recommendations page.

@sfshaza2 -- There are pages missing. I wanted to split up the PR because theres going to be another PR thats about this same size. For now, I updated the prev/next progression in this PR, and I'll update as needed in future PRs.

I addressed all the other comments. You may have to hard refresh your browser to see the missing image. On my computer the broken image was cached.

**Comment by RedBrogdon** [comment]
q.v. #11374.

**Comment by ericwindmill** [comment]
@sfshaza2 PTAL

**Review by sfshaza2 — APPROVED** [review]
lgtm! I had a couple minor suggested edits, but they were so minor, I just deleted them.  :) These docs are looking very profresh.

**Comment by nhannah** [comment]
I believe it is worth taking a look back at the original declarative framework thoughts React had 11 years ago: https://www.youtube.com/watch?v=x7cQ3mrcKaY . As the intro to Flutter notes `Flutter widgets are built using a modern framework that takes inspiration from [React](https://react.dev/).` Moving away from highly layered architecture is one of the original thoughts behind React and one of the major reasons for its popularity.

This architectural guidance suggesting MVVM with a command pattern seems like an attempt to shoehorn imperative architecture into a declarative framework. Flutter is well suited for component based architectural patterns. The complexity of the compass sample app in relation to the simplicity of its functionality should be indicative of an issue in this approach imho. The login screen is compass is a great example of added complexity without cause. A view model with a single function, a listener to monitor that functions result, this could all be highly simplified in a component based approach. But with the added complexity simple things like `Remember to [dispose](https://api.flutter.dev/flutter/foundation/ChangeNotifier/dispose.html) of the [TextEditingController](https://api.flutter.dev/flutter/widgets/TextEditingController-class.html) when it is no longer needed. This will ensure we discard any resources used by the object.` are forgotten.

**Pull request merged**
