### PR TITLE
Add design doc for ScrollBehaviors

### PR DESCRIPTION
**Pull request by Piinks**
For after the freeze. :)

Adds design doc for updating scroll behaviors.

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Comment by Piinks** [comment]
I do not have write access, so I cannot merge this myself. Looks like it's good to go!

**Comment by sfshaza2** [comment]
@Piinks, there's a conflict and it looks like a missing comma. Can you fix? (After the unfreeze, lots of folks rushed to add go links. For future reference, I wouldn't add new ones to the end of the JSON table. Do it higher up.  :) )

**Comment by Piinks** [comment]
Updated! Thanks! :)

> For future reference, I wouldn't add new ones to the end of the JSON table. Do it higher up. :) )

We should probably update the template instructions then : https://docs.google.com/document/d/1SFRO8U2toOlAaZ38dsuEU7Wm5fn41wvBCWKiwADqfmw/edit

**Review by sfshaza2 — APPROVED** [review]
LGTM!

**Pull request merged**
