### PR TITLE
Updated broken links to pub.dev closes #4538

### LINKED ISSUE #4538: link anchors to pub.dev broken
Hi,

When pub.dev did the (awsome) makeover for their website, it seems like they have removed the tab anchors with sub-routes, so `https://pub.dev/packages/http#-installing-tab-` is now `https://pub.dev/packages/http/install`.

This leaves Flutters website with a few misleading links. For example, read the first paragraph at https://flutter.dev/docs/development/packages-and-plugins/using-packages#package-versions, the last link ([url_launcher versions](https://pub.dev/packages/url_launcher#-versions-tab-)) goes to the package homepage instead of the versions.

I searched the issues and PR's but didn't find one that addresses this issue, would it be possible to contribute and fix all the broken links?

### PR DESCRIPTION
**Pull request by zvikarp**
I updated all the links, (searched for `site.pub-pkg` in the whole site to find all links to pub.dart. Also because anchors are not used, I Removed pub.dev's condition from the `tool/config/linkcheck-skip-list.txt`.

full issue description is at #4538

### CODE REVIEW

**Comment by zvikarp** [comment]
umm.. why didn't the travis build pass?

**Comment by sfshaza2** [comment]
@domesticmouse , can you take a look at this [Travis](https://travis-ci.org/github/flutter/website/jobs/721755507) error? After complaining (MANY TIMES) that it can't find the Android toolchain, it ends with the following error: (It looks like it might be caused by an issue in Abdullah's code? I didn't realize that your samples repo could break the website build.)

```
00:13 +6 -1: /home/travis/build/flutter/website/examples/codelabs/testing_codelab/step_06/test/models/favorites_test.dart: Testing App Provider Tests An item should be removed [E]
  Expected: <false>
    Actual: <true>
  
  package:test_api                 expect
  models/favorites_test.dart 28:7  main.<fn>.<fn>
```

**Comment by domesticmouse** [comment]
Ugh, I'm confused. Why do we have the same codebase tested two separate ways? According to travis, the codelabs repo is green: https://travis-ci.org/github/flutter/codelabs

@johnpryan and @filiph can you give me some guidance here?

**Comment by johnpryan** [comment]
This failure seems unrelated - I ran `./tool/build_check_deploy.sh --no-build --no-check-links` locally without any issues.

**Comment by johnpryan** [comment]
I'm attempting to merge master into this branch and seeing what Travis does. https://github.com/flutter/website/pull/4557

**Comment by johnpryan** [comment]
Re-running the Travis job

**Comment by sfshaza2** [comment]
This is, quite literally, the most colorful Travis failure I've seen yet...
Screen Shot 2020-08-31 at 11 31 14 AM

**Comment by johnpryan** [comment]
@domesticmouse I don't know what caused the failure, but I don't think we're testing these apps too differently. It looks like re-running Travis fixed it, it could have been the Flutter version, that Travis used or the version of flutter/codelabs that the `git submodules update` command grabbed at the time.

By the way, @zvikarp we need you to sign the CLA to merge this.

**Comment by sfshaza2** [comment]
I manually verified that @zvikarp has signed the CLA.

**Pull request merged**
