### PR TITLE
Consolidate the testing page with recipes from the cookbook.

### LINKED ISSUE #2178: Consolidate testing page
From https://github.com/flutter/website/issues/2165#issuecomment-452223510:
> Should we actually trim down this testing page a bit in general and link more to the cookbook? The page could describe the testing offered by flutter and the philosophy, but the examples would just link to recipes instead?

### PR DESCRIPTION
**Pull request by brianegan**
Fixes #2178. I've slightly rearranged the content as well. Feedback most welcome on the changes!
 

@chalin If you have a chance, could you please verify my `_includes` code and let me know if it can be improved? I'm bad at Jekyll :P

### CODE REVIEW

**Comment by sfshaza2** [comment]
@brianegan, I can't see it staged, but your changes certainly look fine in theory. I see you have a conflict to resolve.  FYI, @chalin's contract is up, so he's taking a break from Flutter.

**Comment by brianegan** [comment]
Ah, no problem -- thanks for the info!

I'll rebase with master and push again. Would you like me to publish a preview before merging so you can review it a bit easier?

**Comment by brianegan** [comment]
@Sfshaza For easier Review! https://brianegan-flutter-staging.firebaseapp.com/docs/testing

**Comment by sfshaza2** [comment]
The staged version looks great, @brianegan!  I saw one minor error on the second to last line in the last list. The codemagic line has the repeated text of the Bitwise line:

Codemagic CI/CD for Flutter* Flutter CI/CD with Bitrise

**Comment by brianegan** [comment]
Oh no, good catch! Dang git merging! :P

Thanks for the review! I'll wait for this to go green, then merge.

**Pull request merged**
