### PR TITLE
Test drive / VS Code: simplify instructions

### PR DESCRIPTION
**Pull request by chalin**
Context: https://github.com/flutter/website/pull/4310/files#r453503972

cc @DanTup

### CODE REVIEW

**Comment by DanTup** [comment]
LGTM!

**Comment by DanTup** [comment]
I guess I don't have enough power to be an "approving review" 😄

**Comment by chalin** [comment]
> I don't have enough power ...

@DanTup Oh! Well thanks for the thumbs up anyways. 😄

**Comment by sfshaza2** [comment]
@chalin, please fix conflicts. Thx!

**Comment by chalin** [comment]
Done (rebased).

**Pull request merged**
