### PR TITLE
More updates

### PR DESCRIPTION
**Pull request by sfshaza2**
Adding links to Chris's blog post and updating the codelabs page.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]
Looks like the link checker is not happy

**Comment by sfshaza2** [comment]
The link checker looks fine, but the stable build is broken. Typical for after a release. I just merged with main (as I know Khanh fixed the build) and we'll see how it goes this time.

**Comment by khanhnwin** [comment]
Link checker looked okay to me. Build was failing because of not-refresh code excerpts! I just refreshed it, though. Build is running again!

**Review by khanhnwin — APPROVED** [review]
Build passed! Shams, I'll leave it up to you to merge?

**Pull request merged**
