### PR TITLE
Logo colors

### PR DESCRIPTION
**Pull request by sethladd**
Staged at https://sethladd-flutter-io-staging.firebaseapp.com/

### CODE REVIEW

**Comment by sethladd** [comment]
@qchong can you please check out the staging site? thanks!

**Comment by sethladd** [comment]
Hm, need up update the code samples.

**Comment by qchong** [comment]
Thanks for the updates, Seth! The changes look good overall, esp. the code snippet formatting and logo placements. I'd really like to replace the plain 'ol "(tech preview)" text in the main landing header with a more colorful callout banner, but that's probably out of scope for this PR. LGTM but please resolve the build issues before merging.

**Comment by sethladd** [comment]
Should probably merge this Monday.

**Comment by sethladd** [comment]
Closes https://github.com/flutter/flutter/issues/3787
Closes https://github.com/flutter/flutter/issues/5156
Closes https://github.com/flutter/flutter/issues/5088
Closes https://github.com/flutter/flutter/issues/3308

**Comment by sethladd** [comment]
Closes https://github.com/flutter/flutter/issues/5152

**Pull request merged**
