### PR TITLE
Redirect .html and external image request

### LINKED ISSUE #6313: .html files are no longer forwarded
### Describe the problem

We used to forward URLs such as `https://flutter.dev/docs/cookbook/animation/page-route-animation.html` to their ".html"-less equivalents (in this case, https://flutter.dev/docs/cookbook/animation/page-route-animation).

Because this no longer happens, we're seeing a lot more 404s than before August 27. (The infrastructure was changed August 25, but due to a bug fixed in #6208, we don't have 404 info for 8/25 or 8/26.)

Maybe related: We're also seeing new 404s for pages ending in `.`. For example, the top 404 is `/go/android-plugin-migration.`, which should be https://flutter.dev/go/android-plugin-migration. 

### Expected fix

Maybe forward all `xyz.html` pages to `xyz`, and `xyz.` pages to `xyz`.

### Additional context

Of the top-10 404s from 8/27 - 9/23, **nine** end in either `.html` or `.`. The tenth one is `/images/catalog-widget-placeholder.png`. None of these was the cause of a 404 in the preceding 30 days.

### PR DESCRIPTION
**Pull request by btobin**
- Fixes #6313
- Redirects all `*.html` urls to non-html version
- Redirects externally requested `/images/catalog-widget-placeholder.png` to new route
- Does *not* fix redirecting urls ending in `.` -  this one has proved a bit trickier with firebase.json redirects (open to suggestions/recommendations)
- Adds new `make emulate` command to test hosting/redirects locally

/cc @kwalrath

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Review by domesticmouse — APPROVED** [review]

**Comment by sfshaza2** [comment]
Oops, @btobin, the build failed.

**Comment by btobin** [comment]
Figured out how to escape a `.` 👍 

- Added the `.` redirect
- Made the `.html` parsing more strict
- Bonus - found a `"` char in that same file within a url, removed that because it was a 404 - but that link was not caught by the link checker, so that link might not be used anyway.

**Comment by kwalrath** [comment]
Could someone stage this so I can test the bad 404s we were getting? (Yes, I could stage it, but it'd take a while to remember how and get it all working again.)

**Comment by btobin** [comment]
@kwalrath 

https://dash-site-dev--redirects-gmqffgk6.web.app/showcase.
https://dash-site-dev--redirects-gmqffgk6.web.app/showcase.html

**Review by kwalrath — APPROVED** [review]
Spot check shows this fixes a bunch of 404s. Thanks, @btobin!

**Pull request merged**
