### PR TITLE
Upgrade `layout-basics.md`

### PR DESCRIPTION
**Pull request by domesticmouse**
fixes: https://github.com/flutter/website/issues/7006

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by domesticmouse** [comment]
PTAL @khanhnwin

**Review by sfshaza2 — APPROVED** [review]
THANKS, @domesticmouse!!! It looks good to me, but I'll let @khanhnwin take a look.

**Review by parlough — APPROVED** [review]

**Review by RedBrogdon — APPROVED** [review]
How can we get these code snippets under test? Do we have a mechanism for that or could one be created?

**Comment by domesticmouse** [comment]
> How can we get these code snippets under test? Do we have a mechanism for that or could one be created?

This is difficult because it is an injected DartPad, so I doubt it would work with the code injector infra.

**Comment by parlough** [comment]
We track similar a similar issue at https://github.com/dart-lang/site-www/issues/2465 where Kathy proposes a potential solution. It would be nice to support some excerpt mechanism as we have more of these injected DartPads.

**Comment by RedBrogdon** [comment]
Could be something for @khanhnwin to mull over in the next few months.

**Comment by parlough** [comment]
I'm exploring some solutions now as well as it's been a pain point for me recently. If I come up with something reasonable I'll open an issue or PR on dart-pad for further discussion.

**Comment by khanhnwin** [comment]
Looks like @parlough already beat me to it! :)

**Pull request merged**
