### PR TITLE
Update FAQ with new IJ profile and release launch support

### PR DESCRIPTION
**Pull request by mit-mit**
cc @pq @devoncarew

### CODE REVIEW

**Comment by mit-mit** [comment]
NOTE: Do not merge this before https://github.com/flutter/flutter-intellij/issues/930 is fixed

**Comment by abarth** [comment]
LGTM

**Comment by pq** [comment]
Text looks good but as mentioned, we need to tackle https://github.com/flutter/flutter-intellij/issues/930 first.

**Comment by sethladd** [comment]
Should we merge this?

**Comment by mit-mit** [comment]
No, this should not be merged before https://github.com/flutter/flutter-intellij/issues/930 is closed, and looks like that will now happen with the M14 release in a few weeks.

**Comment by mit-mit** [comment]
Closing for now, will resurrect when this actually lands in IJ

**Pull request closed without merging**
