### PR TITLE
clarify "who is flutter for"

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by sethladd** [comment]
cc @maguinis

**Comment by Hixie** [comment]
Why?

**Comment by sethladd** [comment]
Because we saw evidence people were confused about the original wording. Do you see any issues with the new wording, or is it just curiosity?

**Comment by sethladd** [comment]
thanks! updated. PTAL

**Comment by Hixie** [comment]
(i was just curious, carry on!)

**Comment by maguinis** [comment]
LGTM

**Comment by sethladd** [comment]
thanks!

**Pull request merged**
