### PR TITLE
Create mock-platform-channels.md

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Review by sfshaza2 — COMMENTED** [review]
I can merge this once you remove this from draft status and add it to the index file.

Thx!

**Comment by sfshaza2** [comment]
@Hixie replied offline that it's not ready for merging.

**Comment by Hixie** [comment]
Let's wait a few days to see if https://github.com/flutter/flutter/pull/76288 gets reverted (there's a high risk of that happening), but if it sticks, this is ready...

**Comment by Hixie** [comment]
It did; new PR is https://github.com/flutter/flutter/pull/81235.

**Comment by Hixie** [comment]
I need to update this to mention that onPlatformMessage is no longer called.

**Comment by Hixie** [comment]
I should add something about tests that use `package:test` and `package:flutter/service` with `test()`.

**Comment by Hixie** [comment]
Ok I think this is ready to land!

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Pull request merged**
