### PR TITLE
Renamed packages get to pub get 

### PR DESCRIPTION
**Pull request by maheshmnj**
install new dependencies was renamed to **Pub get** from ```Packages get```
quick fix ref issue https://github.com/flutter/flutter/issues/58143 towards issue

### CODE REVIEW

**Comment by maheshmnj** [comment]
@googlebot I signed it!

**Comment by maheshmnj** [comment]
@Sfshaza thanks for the merge this was my first pull request to flutter website,I was just wondering how do you verify that my pull request is correct? do you have some kind of knowledge base or something to verify that?

**Comment by sfshaza2** [comment]
Hi, @maheshmnj! Because I knew you were right. :) I also use Android Studio. I am the (one and only) Flutter Tech Writer at Google. I have been documenting Dart and Flutter for over 6 years and have a degree in computer science from UC Berkeley. I am responsible for the Flutter website, the Flutter Medium publication, and I write Flutter codelabs. In fact, I just (tonight) finished a codelab on using a plugin for a Flutter web app, and so I knew immediately that your PR was correct.  :)

**Comment by maheshmnj** [comment]
> Hi, @maheshmnj! Because I knew you were right. :) I also use Android Studio. I am the (one and only) Flutter Tech Writer at Google. I have been documenting Dart and Flutter for over 6 years (and, before that, I documented Java for 14 years), and I have a degree in computer science from UC Berkeley. I am responsible for the Flutter website, the Flutter Medium publication, and I write Flutter codelabs. In fact, I just (tonight) finished a codelab on using a plugin for a Flutter web app, and so I knew immediately that your PR was correct.  :)

Oh I see,Thanks for taking your time to reply appreciate your work 👍

**Pull request merged**
