### PR TITLE
Add Flutter 3.27 commit-based release notes

### PR DESCRIPTION
**Pull request by itsjustkevin**
Adds release notes for Flutter 3.27.

### CODE REVIEW

**Comment by sfshaza2** [comment]
@itsjustkevin, it looks like a couple 3.27 anchors are missing from the release notes. Otherwise, lgtm

**Review by sfshaza2 — APPROVED** [review]
Once the missing anchors are fixed, lgtm.

**Comment by itsjustkevin** [comment]
@parlough I have no idea why this check is failing.

**Comment by parlough** [comment]
> @parlough I have no idea why this check is failing.

No worries, it's because I haven't updated the breaking changes page yet. I'll be wrapping that up soon and I'll update this PR.

Thanks for preparing this!

**Review by parlough — APPROVED** [review]
I pushed a few minor updates so the link fragments will work. Thanks again for the PR and handling the release!

Feel free to merge once the blog post is published :)

**Pull request merged**
