### PR TITLE
Adding Inside Flutter page for a deep dive on Flutter internals.

### PR DESCRIPTION
**Pull request by Sfshaza**
Ian and Adam, please review!

### CODE REVIEW

**Comment by Sfshaza** [comment]
No news is good news, @abarth and @Hixie?

Merging.

**Comment by Hixie** [comment]
looks like this has a few "PENDING" links.
also it looks like it's missing some of the latest changes to the source document.

**Comment by Hixie** [comment]
(incidentally, not a big deal here, but per our repo rules, please don't commit PRs that haven't been reviewed)

**Comment by Sfshaza** [comment]
Thanks, Ian. We've been a bit more lax on the dash branch since it's not
live.

I'm surprised it doesn't reflect the latest since I used the latest page as
of a 2 or 3 days ago, but I'll check.

**Pull request merged**
