### PR TITLE
default jekyll build location, default to staging server on non-maste…

### PR DESCRIPTION
**Pull request by sethladd**
…r merges, add firebase rules

### CODE REVIEW

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
lgtm

I'm having trouble parsing the travis failure. We may need to change our test dep to `any`? https://github.com/flutter/website/blob/master/pubspec.yaml#L11

**Comment by sethladd** [comment]
Yeah, pub has a bug where it won't tell you if the reason it can't download a package is because of an SDK constraint. I suspect the real issue is a SDK constraint mismatch between test and 1.16-dev.

**Comment by devoncarew** [comment]
Yeah, I just repro'ed it locally after upgrading to `1.17.0-dev.1.0`.

**Comment by sethladd** [comment]
Ah, thanks. Except, our travis script is trying to use Flutter's version of Dart.

**Comment by devoncarew** [comment]
We hit issues with `test` every time the sdk version revs.

**Comment by devoncarew** [comment]
Should build green now w/ https://github.com/flutter/website/pull/230.

**Pull request merged**
