### PR TITLE
Update tutorial for intl: 0.17.0

### PR DESCRIPTION
**Pull request by LotharieSlayer**
_Description of what this PR is changing or adding, and why:_

_Issues fixed by this PR (if any):_ Fixes #ISSUE-NUMBER

## Presubmit checklist
- [ ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ ] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by atsansone — APPROVED** [review]
LGTM % 1 question: Do we need to clarify or call out the name change?

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Comment by sfshaza2** [comment]
I'm ok with this as is. We might need a breaking change doc for it, though.

**Comment by sfshaza2** [comment]
@LotharieSlayer, can you sign the CLA? I can't land this PR without it.

**Comment by LotharieSlayer** [comment]
I just signed the CLA!

**Pull request merged**
