### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by khyati82**
Modifying security policy on flutter.dev website

_Description of what this PR is changing or adding, and why:
Slight modifications to security policy to align with security playbook

_Issues fixed by this PR (if any): None

## Presubmit checklist
- [ ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ ] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by sfshaza2 — COMMENTED** [review]
Oh, all the super duper long lines of text! It burns! Please chop to 80 chars or less, and prefer to break on phrasing. Also, we use sentence case for headers, not title case. (So, ## Supported Versions => ## Supported versions.

thx!

**Comment by khyati82** [comment]
Fixed.

**Comment by khanhnwin** [comment]
Stable build was failing due to `dart analyze` not passing. Just merged in my fix from main to resolve that!

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
I agree with @sfshaza2's request for 80 char limit on line lengths. Easier to read the source in various tools =)

**Review by khanhnwin — APPROVED** [review]

**Review by sfshaza2 — APPROVED** [review]
There are still some overly long lines but I won't sweat this for now. Thanks for updating, @khyati82!

**Pull request merged**
