### PR TITLE
Fix Icon color in `expandable-fab`

### PR DESCRIPTION
**Pull request by TahaTesser**
Link: https://docs.flutter.dev/cookbook/effects/expandable-fab#interactive-example

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by sfshaza2 — CHANGES_REQUESTED** [review]
Requesting a few changes.

**Review by domesticmouse — APPROVED** [review]

**Comment by sfshaza2** [comment]
@TahaTesser, thanks for your updates! I went to fix the conflicts myself, but they are rather long. Could you fix the conflicts? thx

**Comment by TahaTesser** [comment]
@sfshaza2 
Looks like most of the issues are already solved by another PR after merging conflict
However I noticed the wrong icon color is provided, `ColorScheme.secondary` (blue on blue)

image


Just fixed this and docs

**Comment by TahaTesser** [comment]
@sfshaza2 
Perhaps these samples should have some tests so they don't break in the future?

Similar to https://github.com/flutter/flutter/tree/master/examples/api/test/material

**Review by sfshaza2 — APPROVED** [review]
lgtm!

**Pull request merged**
