### PR TITLE
Initial style for Showcase page

### PR DESCRIPTION
**Pull request by fertolg**
- Moved shared landing styles to a new _landing-page.scss file
- Updated markup for showcase page
- Added hero element to landing shared styles for a full width block within the fixed width container
- Added basic custom styles for showcase page

_Note:_ This is just a first pass at the styles, but there’s already a lot going on, so I want to start the review.

### CODE REVIEW

**Comment by chalin** [comment]
Very nice!

One stylistic comment: I much prefer the less busy Doc page cards that look like this:

> screen shot 2018-10-09 at 03 08 28

As opposed to this:

> screen shot 2018-10-09 at 03 08 40

Could we try the Doc-page style cards?

**Comment by chalin** [comment]
This PR impacts the Sass files, so I'll go ahead and merge so that I can build on top of these changes. Followup PRs can address any subsequent issues that arise. Hopefully that's ok with you @fertolg.

**Comment by galeyang** [comment]
I believe there are more links for showcase apps, like Learn More, Download, while the entire Doc-page style cards are clickable. (I'm not sure what it looks like in the latest mockup)

**Comment by Sfshaza** [comment]
I agree with Patrice that the docs pages are much more attractive.

**Pull request merged**
