### PR TITLE
Sort redirects by source

### PR DESCRIPTION
**Pull request by kevmoo**
Makes it much easier to scan
Added whitespace between big, common sections
No other changes were made

### CODE REVIEW

**Comment by kevmoo** [comment]
Before I do https://github.com/flutter/website/issues/5498

**Review by sfshaza2 — APPROVED** [review]
LGTM. That's fine, though Ian's instructions tell the engs to just add to the end of the list.

**Comment by kevmoo** [comment]
> LGTM. That's fine, though Ian's instructions tell the engs to just add to the end of the list.

CC @Hixie 

it makes scanning the list hard, though.

I'm happy to punt on this.

**Comment by kevmoo** [comment]
@sfshaza2 – it appears I don't have keys to land this 😄

**Comment by Hixie** [comment]
Please make sure to update the instructions if this is to be the new policy.

**Comment by kevmoo** [comment]
Where are said docs?

**Comment by Hixie** [comment]
I believe http://flutter.dev/go/template mentions it, maybe something on our wiki (Chat page probably).

**Pull request merged**
