### PR TITLE
Fixed "Ensure website uses "Material Design" (capital D)"

### PR DESCRIPTION
**Pull request by charafau**
Fixes https://github.com/flutter/flutter/issues/8496

fixed:
- corrected Material Design spelling to always start from capital letters

### CODE REVIEW

**Comment by mit-mit** [comment]
Travis failure is unrelated, and fixed in https://github.com/flutter/website/pull/609

**Comment by mit-mit** [comment]
Thanks for contributing @charafau !

**Comment by charafau** [comment]
my pleasure 😄

**Comment by sethladd** [comment]
Super cool. Thank you!

**Pull request merged**
