### PR TITLE
Support for custom site-level banner

### LINKED ISSUE #1659: [dash] update the notification banner box to a more custom design
The box right now for our updates (where we have Flutter Live and Survey) is not aligned with the overall brand of the site, but it's the first thing everyone sees. Let's get a more integrated design for this such as the one on the firebase site.

### PR DESCRIPTION
**Pull request by fertolg**
- Moves the banner from the content are to the top of the site, below the nav
- Updates banner with a more branded style
- Updates JS fixed columns initializer to calculate `max-heights` correctly with the new banner

Fixes #1659

### CODE REVIEW

**Comment by fertolg** [comment]
@chalin I tried staging again, this time the deploy does start but I keep getting an unkown error 😢:

```
➜  flutter-website git:(dash-banner) ✗ tool/shared/deploy.sh --local flutter-web-staging

_site/robots.txt file contents:
-----------------------------------------------------------
User-agent: linkcheck
Disallow:

User-agent: *
Disallow: /
-----------------------------------------------------------

Deploying to Firebase project: flutter-web-staging
+ npx firebase deploy --project flutter-web-staging


┌──────────────────────────────────────────────┐
│ Update available: 6.0.1 (current: 4.0.3)     │
│ Run npm install -g firebase-tools to update. │
└──────────────────────────────────────────────┘


=== Deploying to 'flutter-web-staging'...

i  deploying hosting
i  hosting: preparing _site directory for upload...

Error: HTTP Error: 410, Unknown Error
Cleaning up:
INFO: there is no /Users/fguerrero/tmp/_robots.txt.saved file. Nothing to restore.
```

I'm going to assume I haven't setup firebase properly, but anyway if you wouldn't mind, could you stage this PR so everybody can review how the banner looks and see if we want to merge it?

**Comment by chalin** [comment]
Some of the npm package versions have changed. Rerun the `install.sh` script, that should fix it.

**Comment by chalin** [comment]
How about I let you try that, and if you still have problems, then I'll stage it for you?

**Comment by chalin** [comment]
How about I let you try that, and if you still have problems, then I'll stage it for you?

**Comment by chalin** [comment]
Generally speaking, I preferred the JS-free solution we had before. But, I'm open to hearing from key stakeholders.

**Comment by sfshaza2** [comment]
LGTM!

**Pull request merged**
