### PR TITLE
fixed flutter.dev/brand error

### PR DESCRIPTION
**Pull request by techstrix**
Added a route for the brand page which didn't work before.Showed a 404 error.The correct route for the brand page has been added.When you navigate to flutter.dev/brand it should render the appropriate brand page

### CODE REVIEW

**Comment by khanhnwin** [comment]
Hey @techstrix! Thanks for this PR! It looks like you're not currently covered under the CLA. Can you please visit https://cla.developers.google.com/ to fill it out? Once it's signed we can re-run the CLA check to make sure that it passes!

**Review by sfshaza2 — CHANGES_REQUESTED** [review]
@techstrix, thanks for this PR, but I don't believe it will work. I expect /brand/index would just go to docs.flutter.dev/brand/index. I expect that redirect to look like the following:

```
      { "source": "/brand", "destination": "https://flutter.dev/brand", "type": 301 },

```

**Comment by sfshaza2** [comment]
D'OH. I take it back. The brand page was supposed to be moved to the marketing repo, so let me follow up with that.

**Comment by sfshaza2** [comment]
OK, I chatted with the web team. For now, we're leaving the brand page here, though it will eventually move. So, once you sign the CLA, @techstrix, I can merge!

**Review by sfshaza2 — APPROVED** [review]
Once the CLA is signed, merge.

**Comment by techstrix** [comment]
Ok I signed the cla  but no changes are taking place

**Comment by techstrix** [comment]
I had to close this to fix my cla status I will reopen immediately

**Pull request closed without merging**
