### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Aldo-f**
https://github.com/flutter/samples/tree/master/experimental/desktop_photo_search 
↓ 
https://github.com/flutter/samples/tree/master/desktop_photo_search

### CODE REVIEW

**Comment by khanhnwin** [comment]
Hey @Aldo-f! Thanks for this PR! It looks like you don't have a signed CLA yet so the checks are failing for this PR. Can you please head over to [https://cla.developers.google.com/](https://cla.developers.google.com/) and fill it out? Once that's done I can re-run the checks.

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
Thanks @Aldo-f!

**Comment by Aldo-f** [comment]
You're welcome.
Hopefully next one will be a bit more helpful... 👍

**Review by sfshaza2 — COMMENTED** [review]
LGTM. thx!

**Pull request merged**
