### PR TITLE
Add libblkid in the dependencies list

### PR DESCRIPTION
**Pull request by dedesite**
On my system (Xubuntu 18.04) at least it is required

### CODE REVIEW

**Comment by dedesite** [comment]
@googlebot I signed it!

**Comment by sfshaza2** [comment]
@stuartmorgan, can you verify this?

**Comment by stuartmorgan** [comment]
That's correct:
https://github.com/flutter/flutter/blob/3a5e45404d2a79501c84334bcebd5d65df28280d/packages/flutter_tools/lib/src/base/user_messages.dart#L238
It was made an explicit dependency post-alpha and I forgot we'd need to update these instructions.

**Review by sfshaza2 — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
