### PR TITLE
Showcase redesign

### PR DESCRIPTION
**Pull request by 1Iv4N**
[b/141305122] Showcase redesign.

What's included?
- New showcase page.
- Cleanup styles and assets from the previous version.

### CODE REVIEW

**Comment by 1Iv4N** [comment]
@googlebot I signed it!

**Comment by sfshaza2** [comment]
@1Iv4N, can you provide me with the URL for a staged version of the site? If you'd rather not put it in this PR, just email or IM it to me.  Thx

**Comment by 1Iv4N** [comment]
Hi @sfshaza2 I sent an email with the information. Thanks!

**Comment by sfshaza2** [comment]
@maguinis, can you confirm that the company has signed an NDA?

**Comment by sfshaza2** [comment]
@maguinis has confirmed that all involved have signed an NDA

**Comment by sfshaza2** [comment]
LGTM!

**Pull request merged**
