### PR TITLE
Added missing alignment details in 'Styling and aligning Text' section of Web Analog topic

### LINKED ISSUE #4018: Code excerpt header boxes regression
Our specified header box titles are now missing

was:
78847846-e1f98b00-79c4-11ea-9892-c56d8a3d8146

now:
78847860-eaea5c80-79c4-11ea-8e51-269531edbd73

Seems to have been removed by https://github.com/flutter/website/pull/3773. The headers used to describe the files to edit are very useful in project setup type instructions where the user has to edit multiple files.

### PR DESCRIPTION
**Pull request by aadarshadhakalg**
Fixes   and #2088

Changes proposed in this pull request:

*  Added missing alignment details in  'Styling and aligning Text' section of Web Analog topic.

### CODE REVIEW

**Comment by aadarshadhakalg** [comment]
@googlebot I signed it!

**Comment by sfshaza2** [comment]
@aadarshadhakalg, this PR breaks the build - [the code checker is not happy](https://travis-ci.org/github/flutter/website/jobs/746712987).

**Comment by aadarshadhakalg** [comment]
Well, Yeah. I think I will only do fixes for only #2088 for now. 

The other one #4018 is causing the problem. I think I need to study more about it.

**Review by sfshaza2 — APPROVED** [review]
LGTM. Thanks for the PR!

**Pull request merged**
