### PR TITLE
State Management Options Docs Update for Bloc Package

### PR DESCRIPTION
**Pull request by felangel**
@filiph I compiled a list of resources for the bloc package. Let me know what you think?

### CODE REVIEW

**Comment by filiph** [comment]
Hi @felangel, thanks so much for the pull request!

To keep the page relatively balanced, can you select at most 2 new bullet points and add only them? Alternatively, you can delete one Bloc bullet point and replace it with another.

**Comment by felangel** [comment]
@filiph do you prefer one over the other? I feel bad about removing an existing bullet point haha

**Comment by filiph** [comment]
Ah, this is much better, thanks! 

I think that you can keep Saowen's article since you're only adding one link. Also, I'd like to start with conceptual articles (explain the pattern itself, without concrete implementation).

How about:

* Saowen's article
* Sagar's article
* Your Bloc page

This means removing the link to reddit (which I like, but it's probably the least "lasting" url in the set).

**Comment by felangel** [comment]
@filiph just applied your feedback, thanks!

**Pull request merged**
