### PR TITLE
Add go/whitelabel

### PR DESCRIPTION
**Pull request by Hixie**
Adding a design doc.

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Review by khanhnwin — APPROVED** [review]

**Comment by khanhnwin** [comment]
Thanks @Hixie!

**Review by sfshaza2 — COMMENTED** [review]
Actually, I don't approve this. Can we revert it? The term "white label" has racist origins and we should NOT use it.  https://developers.google.com/style/word-list#white-label

**Comment by sfshaza2** [comment]
cc @domesticmouse  cc @khanhnwin 

I went through this recently with Zoey who was using the term in her News blog post. After I pointed it out, she reworded it.

**Comment by domesticmouse** [comment]
@Hixie please revert. See @sfshaza2 for reasoning

**Comment by Hixie** [comment]
Looks like it's not so much that it has racist origins (looks like the origin is DJs ripping off the labels from vinyl disks), as much as people have been assigning it racial overtones by virtue of overzealously including it in lists of racial terms, but the effect is much the same in the end...

**Pull request merged**
