### PR TITLE
Add migration to VerticalAlignment guide

### PR DESCRIPTION
**Pull request by sidrao2006**
Migration guide for [flutter#67496](https://github.com/flutter/flutter/pull/67496)

### CODE REVIEW

**Review by sfshaza2 — CHANGES_REQUESTED** [review]
Two comments, @sidrao2006.

1. Can you fix the conflict in the file? 
2. The very last line in the list should NOT end with a comma. Currently, this is the last line, so adding a comma is incorrect.

**Comment by sidrao2006** [comment]
@sfshaza2 , thanks for replying 
Sorry, i messed up. I'll be able to complete it sometime in the next 24 hours.

**Review by sfshaza2 — COMMENTED** [review]
Hi, @sidrao2006! I would ask you to remove "master" from the beginning of the line, but then the line is identical to the original line. What needs to be changed?

**Comment by sidrao2006** [comment]
@Sfshaza ,
I think I have fixed the errors.
Also, I am not sure which `,` are you talking about.
Thanks

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Pull request merged**
