### PR TITLE
Other plugins support

### PR DESCRIPTION
**Pull request by NMateu**
Add bridging to GeneratedPluginRegistrant and register it in AppDelegate

### CODE REVIEW

**Comment by NMateu** [comment]
I signed it!

**Comment by mravn-google** [comment]
These changes are an improvement, but we should replace the whole section with use of `flutter create -i swift`

**Comment by mit-mit** [comment]
Thanks for contributing @NMateu !

**Comment by mit-mit** [comment]
@mravn-google tracking that issue in https://github.com/flutter/flutter/issues/11032

**Pull request merged**
