### PR TITLE
Adds new go/web-add-to-app link.

### PR DESCRIPTION
**Pull request by ditman**
_Description of what this PR is changing or adding, and why:_

This PR adds a go-link for a new design doc for the web add-to-app project.

It also alphabetizes some go links that were added at the end of the list (instructions say that they should be "added in alphabetical order".)

_Issues fixed by this PR (if any):_ 

Fixes n/a

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by ditman** [comment]
It seems that the `node` version that is attempting to run `check_link_references` is not good?

```
#19 0.991 npm ERR! notsup Not compatible with your version of node/npm: npm@9.1.1
make[1]: Leaving directory '/home/runner/work/website/website'
#19 0.991 npm ERR! notsup Required: {"node":"^14.17.0 || ^16.13.0 || >=18.0.0"}
#19 0.991 npm ERR! notsup Actual:   {"npm":"8.5.5","node":"v17.9.0"}
```

**Review by khanhnwin — APPROVED** [review]

**Comment by khanhnwin** [comment]
LGTM! Thanks @ditman!

**Comment by ditman** [comment]
Thanks for landing this so quickly @khanhnwin!

**Pull request merged**
