### PR TITLE
Update firebase config

### PR DESCRIPTION
**Pull request by Hixie**
@sethladd

### CODE REVIEW

**Comment by devoncarew** [comment]
Is this just a formatting change?

**Comment by Hixie** [comment]
It changes the format (note the extra level of indirection via 'hosting' now) and removes the `"firebase": "flutter-io-staging"` line. I built this on seth's instruction, so he should probably review it. cc @sethladd

**Comment by sethladd** [comment]
lgtm

**Comment by sethladd** [comment]
Going to merge so I can test.

**Pull request merged**
