### PR TITLE
Add shortlinks for chat and issues

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by sethladd** [comment]
cc @Hixie @Sfshaza

**Comment by Sfshaza** [comment]
These redirects look great, but are you adding links to these on the site?

Anyway, LGTM.  :)

**Comment by sethladd** [comment]
closes https://github.com/flutter/flutter/issues/8651

**Comment by sethladd** [comment]
I can update content on the website, sure! Good idea.

**Pull request merged**
