### PR TITLE
Use sidebar assets from site-shared.

### PR DESCRIPTION
**Pull request by isoos**
A follow-up to https://github.com/dart-lang/site-shared/pull/86 which moved these assets to side-shared (similar to https://github.com/dart-lang/site-www/pull/1391).

### CODE REVIEW

**Comment by isoos** [comment]
/cc @kwalrath @filiph 
I have no right to invite reviewers in this repo.

**Comment by kwalrath** [comment]
@sfshaza2 maybe you could make sure that this renders well for you by doing a clean build?

**Comment by sfshaza2** [comment]
It seems to work fine. Here is my staged version:  https://sz-flutter.firebaseapp.com/docs

However, when I run ./tool/serve.sh, I get this error about the floating_right mixin:

```
website [isoos-update_shared] $ ./tool/serve.sh
./tool/serve.sh: for details about command-line options, use --help

Cached PIDs for build and serve: 64207, 64208
+ bundle exec jekyll build --incremental --watch
+ npx superstatic --version
6.0.4
+ npx superstatic --port 5000

Superstatic started.
Visit http://localhost:5000 to view your app.
Configuration file: /Users/shaza/GoogleDrive/site/flutter/website/_config.yml
            Source: src
       Destination: /Users/shaza/GoogleDrive/site/flutter/website/_site
 Incremental build: enabled
      Generating... 
WARNING: The `float-right` mixin has been deprecated as of v4.3.0. It will be removed entirely in v5.
         on line 8 of /Users/shaza/.rvm/gems/ruby-2.4.3/gems/bootstrap-4.3.1/assets/stylesheets/bootstrap/mixins/_deprecate.scss, in `deprecate'
         from line 9 of /Users/shaza/.rvm/gems/ruby-2.4.3/gems/bootstrap-4.3.1/assets/stylesheets/bootstrap/mixins/_float.scss, in `float-right'
         from line 54 of /Users/shaza/GoogleDrive/site/flutter/website/src/_assets/css/_toc.scss
         from line 16 of /Users/shaza/GoogleDrive/site/flutter/website/src/_assets/css/main.scss

WARNING: The `float-right` mixin has been deprecated as of v4.3.0. It will be removed entirely in v5.
         on line 8 of /Users/shaza/.rvm/gems/ruby-2.4.3/gems/bootstrap-4.3.1/assets/stylesheets/bootstrap/mixins/_deprecate.scss, in `deprecate'
         from line 9 of /Users/shaza/.rvm/gems/ruby-2.4.3/gems/bootstrap-4.3.1/assets/stylesheets/bootstrap/mixins/_float.scss, in `float-right'
         from line 34 of /Users/shaza/GoogleDrive/site/flutter/website/src/_assets/css/_content.scss
         from line 17 of /Users/shaza/GoogleDrive/site/flutter/website/src/_assets/css/main.scss
```

**Comment by isoos** [comment]
> However, when I run ./tool/serve.sh, I get this error about the floating_right mixin

@sfshaza2: I'm not sure if these are related to the current PR. Could you please also check against the git head?

**Comment by sfshaza2** [comment]
I don't get this error when serving master:

./tool/serve.sh: for details about command-line options, use --help

Cached PIDs for build and serve: 70228, 70229
+ bundle exec jekyll build --incremental --watch
+ npx superstatic --version
6.0.4
+ npx superstatic --port 5000
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:5000
    at Server.setupListenHandle [as _listen2] (net.js:1270:14)
    at listenInCluster (net.js:1318:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1451:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1297:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Configuration file: /Users/shaza/GoogleDrive/site/flutter/website/_config.yml
            Source: src
       Destination: /Users/shaza/GoogleDrive/site/flutter/website/_site
 Incremental build: enabled
      Generating... 
                    done in 33.331 seconds.


But I'm fine with merging it. The sidenav looks fine.

**Comment by isoos** [comment]
The `@float-right` in `_toc.scss` is not used in practice, that could be removed. I have no idea wether the one in `_content.scss` is used. However, I still fail to see why the warning was triggered with the PR: it does not touches any of those files, nor the ones that link to those.

Maybe it is the clear build... maybe a second run won't display it? Otherwise I can't imagine a reason why the `master` branch does not show it.

**Comment by sfshaza2** [comment]
@isoos, I just did a clean build in master and, you're right. There's the mixin error.  :)

I'm merging this.

**Pull request merged**
