### PR TITLE
Remove non-existent links

### PR DESCRIPTION
**Pull request by xster**
Took out 2 links to pngs that aren't checked-in. 

Otherwise, I can't build it on firebase.

### CODE REVIEW

**Comment by xster** [comment]
@sfshaza2, did you mean to close this PR?

**Comment by xster** [comment]
It's all in https://github.com/flutter/website/pull/3004 now. @matthew-carroll, let me know if it's ok to remove these non-existent links (or maybe I failed to recover these pngs correctly?)

**Comment by matthew-carroll** [comment]
Do we know what happened to those PNGs?

**Comment by xster** [comment]
I'm not sure. But it wasn't in https://github.com/flutter/website/pull/2798/files either. Was it from a different PR?

**Comment by matthew-carroll** [comment]
It doesn't look like those other images are in there. But that's OK, I'll just add them back at some point.

**Comment by sfshaza2** [comment]
I don't know what happened to those images. I don't *think* I was
responsible for those disappearing.

**Pull request closed without merging**
