### PR TITLE
Fix flutter.dev/brand error

### PR DESCRIPTION
**Pull request by techstrix**
Removed the 404 error when you navigate to flutter.dev/brand by adding a route

### CODE REVIEW

**Comment by techstrix** [comment]
This had already been approved but I needed to fix my cla status since it wasnt  working so I closed the request.

**Comment by parlough** [comment]
Thanks for the PR, but I'm not sure this will achieve the desired affect. https://docs.flutter.dev/brand already leads to the desired page. I believe the redirects for the new https://flutter.dev are hosted in a separate (currently not public) repository and use a separate declaration of redirects.

**Comment by techstrix** [comment]
Actually this will work since if you go to flutter.dev/brand it will show the page. If you navigate there now you get a 404 error. I had submitted this before and it had been approved but had to close this since my cla was showing no. But after making a new pull request my cla status was fixed.

**Comment by domesticmouse** [comment]
Confirming that https://flutter.dev/brand is indeed 404'ing. I'm unsure why the CI build is failing. 

Any ideas @khanhnwin?

**Comment by khanhnwin** [comment]
Hey @techstrix thanks for this PR! As @parlough mentioned, flutter.dev is now hosted in a separate repo with its own `firebase.json` for redirects. We'll flag this down to be fixed in the flutter.dev repo's firebase.json.

**Pull request closed without merging**
