### PR TITLE
DevTools release notes

### PR DESCRIPTION
**Pull request by johnpryan**
Adds DevTools release notes for DevTools 2.7.0, 2.8.0, and 2.9.1.

Staged: https://flutter-website-jr-stagi-988d4.web.app/development/tools/devtools/release-notes

FYI @kenzieschmoll 

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by johnpryan** [comment]
Staged: https://flutter-website-jr-stagi-988d4.web.app/development/tools/devtools/release-notes

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Comment by sfshaza2** [comment]
Typical. Failing against the stable build after an update to 2.8.

**Comment by johnpryan** [comment]
The build was failing due to https://github.com/flutter/website/pull/6552, this includes that change now, so we'll just need to make sure that CI passes

**Pull request merged**
