### PR TITLE
Add screen reader instructions for desktop OSes

### PR DESCRIPTION
**Pull request by filiph**
Add basic instructions on using screen readers on desktop (not desktop _browsers_, but desktop).

Staged: https://flutter-website-filiph-staging.web.app/development/accessibility-and-localization/accessibility#screen-readers

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]
PTAL @cbracken

**Review by loic-sharma — APPROVED** [review]
Looks great, thanks for adding this!

**Comment by domesticmouse** [comment]
Sorry @sfshaza2, I didn't mean to land this one. Let me know if you want me to revert and set it up for you to review. Alternatively, raise a PR with required changes and I'll lgtm it.

**Comment by sfshaza2** [comment]
It's all good, @domesticmouse. Yeah, I would have made some minor tweaks, but nothing big. Postassimilation lgtm.

**Pull request merged**
