### PR TITLE
specify that intellij community is free

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by sethladd** [comment]
For https://github.com/flutter/flutter/issues/12093

cc @filiph or @mit-mit for review

**Comment by LarkAscending** [comment]
Note that the product names have changed... IntelliJ IDEA Community and IntelliJ IDEA Ultimate. No "edition".

**Comment by sethladd** [comment]
Ah, thanks!

**Comment by alexander-doroshko** [comment]
The product names have not changed. But you may use both longer and shorter variant. Even the About dialog contains both.
image

**Pull request merged**
