### PR TITLE
Add DevTools release notes 2.17.0

### PR DESCRIPTION
**Pull request by polina-c**

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Review by kenzieschmoll — COMMENTED** [review]
There were user facing changes that we should be calling out for this release. The general process for writing these release notes is to comb through the [changelog](https://github.com/flutter/devtools/blob/master/CHANGELOG.md#2170), and pull out things that are interesting to the user. Some things that should be called out for this release:
- an explanation of the new package directories feature in the inspector (pub root directories)
- an explanation of the new frame analysis feature that was enabled for the performance page (https://github.com/flutter/devtools/pull/4339)

**Comment by sfshaza2** [comment]
I'm sorry, @kenzieschmoll, I hadn't realized that you hadn't viewed it yet. (Though the release notes did seem pretty short to me.) @polina-c, can you submit another PR when ready?

**Comment by polina-c** [comment]
> I'm sorry, @kenzieschmoll, I hadn't realized that you hadn't viewed it yet. (Though the release notes did seem pretty short to me.) @polina-c, can you submit another PR when ready?

sure!

**Pull request merged**
