### PR TITLE
[wasm] revert/postpone changes targeting 3.22 release

### LINKED ISSUE #10576: [PAGE ISSUE]: 'Support for WebAssembly (Wasm)' is about 3.22 but current stable is 3.19.6
### Page URL

https://docs.flutter.dev/platform-integration/web/wasm/

### Page source

https://github.com/flutter/website/tree/main/src/content/platform-integration/web/wasm.md

### Describe the problem

Currently the wasm documentation shows "Last updated May 14, 2024". This is a date in the future. Also it show release 3.22 as current stable release. Flutter 3.22 is not in stable yet. wasm.md has been released containing wrong information.
Screenshot 2024-05-13 at 15 46 13

### Expected fix

Documentation related to 3.22 should wait until the release.

### Additional context

_No response_

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

### PR DESCRIPTION
**Pull request by gitslav**
Fixes #10576
Currently the wasm documentation shows "Last updated May 14, 2024". This is a date in the future. Also it show release 3.22 as current stable release.
Screenshot 2024-05-13 at 15 46 13

### CODE REVIEW

**Comment by gitslav** [comment]
Currently the wasm documentation shows "Last updated May 14, 2024". This is a date in the future. Also it show release 3.22 as current stable release.

**Comment by sfshaza2** [comment]
Really, this is close enough.

**Comment by gitslav** [comment]
It can confuse people like it confused me. I had to double check by running flutter upgrade and also check the releases page. Should not be the case

**Comment by domesticmouse** [comment]
If only it were as simple as updating a single version string somewhere, and having all of the various parts of the Flutter documentation and downloadable SDKs would instantly reflect the new stable version. Unfortunately, with our presence spread across multiple sites and publishing pipelines, this is not the case. 

We apologize for the temporary confusion as we progress through this process, but by this time tomorrow it should all be approaching consistent again. Thanks!

**Pull request closed without merging**
