### PR TITLE
Use code_excerpt[er|_updater] from site-shared

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
@RedBrogdon – this seems...much better, right?

Stop depending on your fork of these?

**Review by RedBrogdon — APPROVED** [review]
Nice catch. I clearly forgot step 2 of moving them to `site-shared`.

**Comment by kevmoo** [comment]
@RedBrogdon – I lack the power to squash. Please do the honors

**Comment by RedBrogdon** [comment]
I, too, lack the power. @kwalrath, what dark wizardry is this? 😄

**Pull request merged**
