### PR TITLE
Clean Up the "Persist data with SQLite" Page

### PR DESCRIPTION
**Pull request by micpap25**
Makes a bunch of fixes to the page:
* Removes typos and grammar mistakes in the first paragraph. 
* Breaks up Dart sections that misleadingly look like they are next to each other when they aren't. (From Issue #3758)
* Also adds a note to make the final example easier to arrive at by following the tutorial.
* Basically makes the final example consistent with the rest of the cookbook.

### CODE REVIEW

**Comment by sfshaza2** [comment]
Thanks for this PR, @micpap25! Overall, it looks good, however, Travis is failing and it appears to be because some of the code snippets aren't tagged with the "skip" tag. The skip tag is required for incomplete code examples or code that uses APIs that aren't yet in our latest stable channel. It tells the analyzer not to analyze that code.

**Review by sfshaza2 — CHANGES_REQUESTED** [review]
It looks good overall, but is breaking the build.

**Comment by micpap25** [comment]
Fixed! I didn't know about the skip tags, so thank you for pointing that out.

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Pull request merged**
