### PR TITLE
Update with new F.F. logo

### PR DESCRIPTION
**Pull request by mit-mit**
In support of the pub.dev redesign, updating the logo here

### CODE REVIEW

**Comment by mit-mit** [comment]
Screenshot: 
Screenshot 2020-07-08 at 15 25 34

**Comment by kwalrath** [comment]
@mit-mit can we update this right away, or would you like us to hold off until the new logo is visible on the site?

**Comment by mit-mit** [comment]
I'm fine just merging it now if @csells doesn't have any reservations?

**Comment by csells** [comment]
lgtm

**Pull request merged**
