### PR TITLE
style(flutter for react native devs): add trailing comma to code example

### PR DESCRIPTION
**Pull request by ellouzeskandercs**
_Description of what this PR is changing or adding, and why:_
In some code example on the docs for react native developers, the code was not well formatted as shown in the table below:

| Before the changes  |  After the changes |
|---|---|
| Capture d’écran 2023-10-16 à 13 08 55 |  Capture d’écran 2023-10-16 à 13 07 50 |

This PR aims to fix this issue.

_Issues fixed by this PR (if any):_ None

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by atsansone** [comment]
@ellouzeskandercs : The build is failing because the linked `.dart` files need to be updated to match. I'll see what I can do to expedite.

**Comment by ellouzeskandercs** [comment]
@atsansone thanks for the review ! :) Do you want me to change the broken .dart file (`examples/get-started/flutter-for/react_native_devs/lib/components.dart` I guess) or you can expedite without the fix ?

**Comment by atsansone** [comment]
@ellouzeskandercs : If you could change the `dart` files, that would be great. (That's what I was going to do in case you didn't know how.)

The script that tests code verifies that the example dart file and the code block match. If they don't, it throws an error.

**Comment by ellouzeskandercs** [comment]
@atsansone it should be ok now ✅ I run the "make test" command locally and it succeeded.

**Pull request merged**
