### PR TITLE
Universal link `apple-app-site-association` misses `apps` property

### LINKED ISSUE #8636: Universal link `apple-app-site-association` misses `apps` property
### Page URL

https://docs.flutter.dev/cookbook/navigation/set-up-universal-links#apple-app-site-association

### Page source

_No response_

### Describe the problem

To get Universal links working on iOS, you need to add an `apps` property to the `apple-app-site-association` file.

So, the fils should look like this : 

```json
{
  "applinks": {
      "apps": [],
      "details": [
      {
        "appID": "S8QB4VV633.com.example.deeplinkCookbook",
        "paths": ["*"]
      }
    ]
  }
}
```

### Expected fix

Maybe the website doc should be updated.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Chralu**
Fixes #8636

### CODE REVIEW

**Comment by parlough** [comment]
Hi @Chralu, before we can review this pull request, you'll need to sign the CLA as mentioned by the CLA bot: https://github.com/flutter/website/pull/8637/checks?check_run_id=13069609019

Let us know if you have any trouble. Thanks!

**Comment by Chralu** [comment]
Hi @parlough , I just accepted the CLA 👌

Let me know if anything else misses.

**Comment by atsansone** [comment]
This appears correct according to [Apple's documentation](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html).

**Review by atsansone — APPROVED** [review]

**Review by parlough — APPROVED** [review]
Thanks!

Looks like this example is using the older format, so this makes sense.

**Pull request merged**
