### PR TITLE
fixed terminal prompt typo

### PR DESCRIPTION
**Pull request by MiraMarshall**
_Description of what this PR is changing or adding, and why:_
Fixes the MacOS terminal prompt for easier copy/paste. Previously, the "$" was included in the copy/paste.  The page still looks the same. 
Screen Shot 2022-09-01 at 9 20 27 AM

_Issues fixed by this PR (if any):_
#7408 
## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by khanhnwin — APPROVED** [review]

**Comment by khanhnwin** [comment]
Sweet! Thanks @MiraMarshall!

**Comment by piedcipher** [comment]
I'm curious to know how does this fix the issue? Because in .md file, `$` can still be copied.

**Comment by MiraMarshall** [comment]
> I'm curious to know how does this fix the issue? Because in .md file, `$` can still be copied.

On the page, when the copy code button is selected for the command referenced in the issue, the '$' is no longer copied with the terminal command. This will make it easier for users who use the copy command button.

**Comment by piedcipher** [comment]
Thanks for the reply! I understood that, my question was regarding how did adding a backspace fixed the issue?! If you could please tell :sweat_smile:

**Pull request merged**
