### PR TITLE
firebase auth debugging - dont merge

### PR DESCRIPTION
**Pull request by FaisalAbid**
Running tests on travis to see why oauth token is failing

### CODE REVIEW

**Comment by FaisalAbid** [comment]
@LarkAscending  weird why did this build.. hmm

**Comment by FaisalAbid** [comment]
perhaps the PR's aren't rebased to master?

**Comment by LarkAscending** [comment]
Can't see what's different from here... Auth is sensitive to environment, and often needs testing in the wild.

**Comment by FaisalAbid** [comment]
Can we get the two PR authors to rebase from master and force push, just to make sure

**Comment by LarkAscending** [comment]
Verifying these are the steps you want:
1. git checkout master
1. git pull upstream master --rebase
1. git checkout outbound_icon
1. git rebase -i master
1. git push --force origin outbound_icon

**Comment by FaisalAbid** [comment]
Yea I think those would work, I think i do a shorthand of those steps

I usually do

git checkout outbound_icon
git fetch origin
git rebase origin/master
git push -f origin outbound_icon

**Comment by FaisalAbid** [comment]
where origin is flutter/website 

so that could be your upstream also

**Comment by LarkAscending** [comment]
Ran your steps, 20 stray commits :-)
Ran my steps, PR good now w/1 commit. googlebot happy.
Travis was not automatically kicked off, looks like.

**Pull request closed without merging**
