### PR TITLE
Update screenshots to Xcode 13

### PR DESCRIPTION
**Pull request by jmagman**
- Update screenshots to show newest version of Xcode, and iOS 9 instead of iOS 8 (see https://github.com/flutter/website/pull/6057).  Ran `npx gulp compress-images` on all updated images.
- Replace references to Xcode 11.4 (which is no longer supported) to either "Xcode" or "Xcode 11.4 and higher".
- Fix reference to `ios` to `macos` in macOS setup instructions.

______________________

Before:
macos_xcode_settings

After:
macos_xcode_settings

______________________

Before:
xcode_settings

After:
xcode_settings

______________________

Before:
xcode-account

After:
xcode-account

______________________

Before:
xcode-unique-bundle-id

After:
xcode-unique-bundle-id

______________________

Before:
ios-launchscreen-xcode

After:
ios-launchscreen-xcode

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
LGTM! Thanks, @jmagman!

**Comment by jmagman** [comment]
> * Fix reference to `ios` to `macos` in macOS setup instructions.

@sfshaza2 the `src/docs/deployment/macos.md` instructions aren't linked in the sidenav. Is that intentional? 
Screen Shot 2021-09-16 at 12 10 15 PM
https://flutter.dev/docs/deployment/macos

/cc @cbracken

**Comment by sfshaza2** [comment]
No, @jmagman, definitely not intentional! Thanks for catching that. We have "lost" several pages from the sidebar when we migrated to the dockerized version of the website. I can file a PR unless you want to? (I'm assuming not.)

**Comment by jmagman** [comment]
> No, @jmagman, definitely not intentional! Thanks for catching that. We have "lost" several pages from the sidebar when we migrated to the dockerized version of the website. I can file a PR unless you want to? (I'm assuming not.)

Created https://github.com/flutter/website/pull/6288

**Pull request merged**
