### PR TITLE
Avoid duplicate widget catalog pages

### LINKED ISSUE #1808: Avoid duplicating widget catalog pages
In https://github.com/flutter/website/issues/1801#issuecomment-443352601, @galeyang wrote:

For the current duplication, do you know if a user would see two Google search results linking to separate pages with the exact same content? This could be confusing...

Also, I found if users visit `/docs/reference/widgets/layout` from google search result and click the below link (linking to widget index), they may get lost and don't have a clear path on how to get back.
image

Does "having Widget Catalog under UI and the Widget Index under Reference" solve these potential problems?

### PR DESCRIPTION
**Pull request by chalin**
Fixes #1808

**Question**: Note the breadcrumbs for catalog subpages, shown below. Are you ok with the use of just "Catalog" for the crumb name, or would you rather it match the full catalog page title "Widget catalog"?

cc @InMatrix 

Staged, see:

- https://ng2-io.firebaseapp.com/docs/development/ui/widgets - the new canonical reference to the catalog.
- https://ng2-io.firebaseapp.com/docs/development/ui/widgets/catalog - the old URL to the catalog, that redirects to the new canonical URL.
- An example of catalog pages from under Reference being redirected:
  - https://ng2-io.firebaseapp.com/docs/reference/widgets/basics

---

## Screenshots

screen shot 2018-11-30 at 18 36 55

### Breadcrumbs for subpages

screen shot 2018-11-30 at 18 34 41

### CODE REVIEW

**Comment by InMatrix** [comment]
> Question: Note the breadcrumbs for catalog subpages, shown below. Are you ok with the use of just "Catalog" for the crumb name, or would you rather it match the full catalog page title "Widget catalog"?

Why not using "Widgets" to match the URL pattern?

**Comment by chalin** [comment]
> Why not using "Widgets" to match the URL pattern?

Good idea.

**Comment by chalin** [comment]
Done, and the staging server has been refreshed. PTAL

**Comment by chalin** [comment]
I'm confident that Shams will be ok with the removed duplication. Gale approved, Tao seems ok with the PR. Merging now.

**Comment by sfshaza2** [comment]
@chalin is mighty confident, but you're right, I'm OK with it.  :)

**Pull request merged**
