### PR TITLE
Convert cookbook examples to DartPad

### PR DESCRIPTION
**Pull request by brianegan**
I've run through the cookbook to see which recipes can make use of DartPad's new support for Flutter. 

Those that can make use of DartPad have been updated to do so! I've made 4 changes to each file:

  1. Include the JS
  2. Convert "Complete Example" text to "Interactive Example"
  3. Convert the code annotation from `dart` to `run-dardpad`
    - Added Support to the extraction tool to extract these strings as well so they can be verified for correctness
  4. Keep the sample images, but wrap them in a `noscript` tag for those who have JS disabled.

### Staging

[https://brianegan-flutter-staging.firebaseapp.com](https://brianegan-flutter-staging.firebaseapp.com)

### Updated Recipes

  - animated-container
  - opacity-animation
  - page-route-animation
  - physics-simulation
  - drawer
  - orientation
  - snackbars
  - tabs
  - themes
  - focus
  - retrieve-input
  - text-field-changes
  - validation
  - dismissible
  - handling-taps
  - ripples
  - network-image
  - basic-list
  - floating-app-bar
  - grid-lists
  - horizontal-list
  - long-lists
  - mixed-list
  - hero-animations
  - named-routes
  - navigate-with-arguments
  - navigation-basics
  - passing-data
  - returning-data

### CODE REVIEW

**Comment by sfshaza2** [comment]
I'd love to merge this, Brian, but can you fix the conflicts?

**Comment by brianegan** [comment]
Thanks, @Sfshaza :)

One note: It looks like there is currently a problem with the inject script required by Dartpad with the Flutter production environment: https://github.com/flutter/website/issues/3262

I'd recommend we hold off on merging this PR until a fix is in place.

**Comment by sfshaza2** [comment]
OK, thanks!

**Comment by sfshaza2** [comment]
Waiting for @RedBrogdon to review.

**Comment by sfshaza2** [comment]
I'm itching to merge this, but the issue @brianegan referenced is still open. From reading that issue, I'm not sure if it is a problem. Where are we on this, @legalcodes?

**Comment by legalcodes** [comment]
@sfshaza2 If we merge this now, it will fail in production. See https://github.com/flutter/website/issues/3262. @johnpryan to provide on update on ETA for a fix.

**Comment by RedBrogdon** [comment]
I have no idea how this got so lost in the flurry of activity around Interact, but it did. Sorry for that.

All of the code here looks great (which makes sense, since it was already part of the cookbook). I really only have two suggestions, both of which are about dealing with the limited width afforded the iframe on the page:

* Consider running `flutter format --line-length=60` on these to limit the width required for the editor.
* Set the split percentage in the markdown delimiter to something like 75/25 code/output wherever possible.

**Comment by RedBrogdon** [comment]
We still don't have a good solution to the inject script problem. I'm hoping to talk it through with @johnpryan tomorrow.

Your work here is essentially done, though, @brianegan. Thanks for some great new content for DartPad. Also, I'm not sure if you've noticed, but we snuck your physics animation example into the samples dropdown on [dartpad.dev](https://dartpad.dev). 😄

**Comment by johnpryan** [comment]
There's a workaround for #3262, so I think we're OK to merge this. I will follow-up with the fix.

**Comment by sfshaza2** [comment]
WOOT!!!! THANKS, @johnpryan!

**Pull request merged**
