### PR TITLE
Fix macOS deployment Codemagic CLI tools Point 13 snippet

### PR DESCRIPTION
**Pull request by VeArnold**
_Description of what this PR is changing or adding, and why:_

The snippet update assures that the right certificate is found in the case of multiple certificates. The fix was suggested in the issue marked below and was deemed to be accurate.

_Issues fixed by this PR (if any):_

[Issue 7211](https://github.com/flutter/website/issues/7211)

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
This matches https://docs.codemagic.io/yaml-code-signing/signing-macos/#packaging-the-application LGTM.

Also, I wish we didn't have a copy of these instructions and would just point to https://docs.codemagic.io/yaml-code-signing/signing-macos, so we're never out of date...

**Comment by domesticmouse** [comment]
I'd be happy to just refer to codemagic's documentation. I strongly dislike duplicating external docs.

Thoughts @sfshaza2?

**Comment by VeArnold** [comment]
> I'd be happy to just refer to codemagic's documentation. I strongly dislike duplicating external docs.
> 
> Thoughts @sfshaza2?

I think the main issue with this here is that the guide here instructs users to use Codemagic CLI tools independent of a CI/CD pipeline, while the scripts presented in Codemagic documentation are part of the `codemagic.yaml` structure, and thus perhaps a source of some confusion.

**Comment by jmagman** [comment]
> I think the main issue with this here is that the guide here instructs users to use Codemagic CLI tools independent of a CI/CD pipeline, while the scripts presented in Codemagic documentation are part of the `codemagic.yaml` structure, and thus perhaps a source of some confusion.

I can see that being confusing, and our docs interleave Codemagic and `flutter` commands.

**Comment by sfshaza2** [comment]
Yes, I agree with @jmagman. When I looked at the codemagic page a week or two ago, it was NOT an easy fix to just redirect to that page. It was quite confusing, in fact. I like the idea of referring to that page, but it has to be clear and coherent. And, yes, I'm on vacation this week.  :)

**Pull request merged**
