### PR TITLE
Misc updates to navbar and homepage

### PR DESCRIPTION
**Pull request by fertolg**
- Navbar updates:
  - Updated brand lockup
  - Adds Get Started button to homepage navbar
  - Increases hamburger icon to 28px
  - Updates social links so they are always present on navbar
- Homepage updates:
  - Embedded Youtube video plays with subtitles by default
  - Tweaked partners logo sizes and padding
  - Updates copy and some links

### CODE REVIEW

**Comment by fertolg** [comment]
@chalin: This PR includes some updates from our meeting this morning, as well as some updates Martin requested during our walkthrough today.

**Comment by fertolg** [comment]
Hmmm the build failed but the error doesn't seem to be in my changes, I think it's an issue with some .dart code?

**Comment by chalin** [comment]
> Hmmm the build failed but the error doesn't seem to be in my changes, I think it's an issue with some .dart code?

Yes. Issue details are in #1423, and a workaround submitted via #1424.

**Comment by fertolg** [comment]
During our review with Martin yesterday, he asked the get started button was shown in homepage and in showcases page because the get started button in the first content card won't be visible at load time once the hero image is in.

You are correct, the flutter logo and word mark are raster images for some reason, but the 'by Google' is a vector outline. I'll ask Daniel to see if he has the original vector outline for the flutter logo and word mark.

**Pull request merged**
