### PR TITLE
Fix to 'unsecured connection not allowed'

### PR DESCRIPTION
**Pull request by agavrel**
IOWebSocketChannel.connect('ws://echo.websocket.org'), -> IOWebSocketChannel.connect('wss://echo.websocket.org'),

### CODE REVIEW

**Comment by sfshaza2** [comment]
I'd love to merge this, @agavrel, but can you sign the CLA?

**Comment by agavrel** [comment]
I have signed it, right after my PR:

Agreement | Name | Date Signed | Manage
-- | -- | -- | --
Google Individual CLA | Antonin GAVREL | Feb 11, 2021 11:51 PST|Edit Contact Information

**Comment by agavrel** [comment]
@googlebot I signed it!

**Comment by sfshaza2** [comment]
Thanks, @agavrel!

**Pull request merged**
