### PR TITLE
TextEditingController.buildTextSpan migration guide

### PR DESCRIPTION
**Pull request by Jjagg**
Adds the migration guide for flutter/flutter#73510.

### CODE REVIEW

**Comment by Hixie** [comment]
Make sure to include the error message that users will see, so if they google the error message the guide comes up.

**Review by justinmc — APPROVED** [review]
LGTM 👍 

This is great, thanks for taking the time to write this.  I will point any Google Flutter users to this when I migrate their code.

**Comment by sfshaza2** [comment]
Kicked off the build again. It complained about the null safety check.

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Pull request merged**
