### PR TITLE
Replace hot reload gif with current VS code version

### PR DESCRIPTION
**Pull request by psenakv**
I created new (similar) GIF of Hot Reload to show the latest version of VS Code, to fix this issue on flutter/flutter#80808

### CODE REVIEW

**Comment by plexp** [comment]
@googlebot I signed it!

**Comment by werainkhatri** [comment]
Some suggestions
1. Reduce the width of the gif. There is a lot of empty space in the image, so reduce the width of the VSCode window.
2. Increase the font size of the code / zoom in.
3. Show the decrement working as well.

**Comment by plexp** [comment]
@werainkhatri Hey, thanks for suggestions. I agree with 1 & 2, but what you mean by "Show the decrement working as well."?

**Comment by werainkhatri** [comment]
> @werainkhatri Hey, thanks for suggestions. I agree with 1 & 2, but what you mean by "Show the decrement working as well."?

If you see the original image, it shows that `counter++` is changed to `counter--`, but it's not shown in working. I thought it would be great if that was demonstrated too.

**Comment by sfshaza2** [comment]
Just to be clear. Images displayed on the flutter/flutter README are stored on the flutter/website repo. I can't remember why, exactly, but there was a reason for that. This image is not used in the website repo at all. This image appears on the flutter/flutter README page under "Productive development". It is not credited as a VS code image.

For some reason, the image was stored in our repo under "Android Studio". However, if it really is a VS code image, I would like to to be stored under VS code, or under "/src/_assets/image/tools/vs-code/hot-reload.gif" instead of under ".../android-studio/hot-reload.gif".

Also, yes, please run an optimizer over the GIF, and making the font easier to read is a terrific idea!

**Review by sfshaza2 — CHANGES_REQUESTED** [review]
Please move the image location and optimize it. Thx!

**Comment by plexp** [comment]
@sfshaza2 Hey, should I leave the original image in android studio? The location is wrong, but if I move it, it will break the readme.md on flutter/flutter, if I understand correctly.

**Comment by sfshaza2** [comment]
For now, leave the old one as is. But, yes, we need a new PR on the README file to refer to the correct location. Eventually, I'll remove the old one, but there's no rush.

**Comment by sfshaza2** [comment]
I don't like that this file hasn't been moved, nor that the flutter/flutter repo hasn't been updated with the proper location, but we are about to freeze the site, so I'm going to approve it. LGTM

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Pull request merged**
