### PR TITLE
[rename fixit] Update web site to use the new names

### PR DESCRIPTION
**Pull request by abarth**
Related to https://github.com/flutter/flutter/issues/2536

### CODE REVIEW

**Comment by abarth** [comment]
@qchong @Hixie

**Comment by abarth** [comment]
Technically, we should wait on merging this pull request until we update the alpha branch.

**Comment by Hixie** [comment]
LGTM. Agreed that we should wait until we update alpha; we should probably bake trunk on Monday before we do that though.

**Comment by abarth** [comment]
There's a problem that Travis is using an older analyzer that doesn't know how we're describing dart:ui.  I guess I can fix that in another patch before landing this one.

**Pull request merged**
