### PR TITLE
remove the IDE topics category; move IDE pages up one level

### PR DESCRIPTION
**Pull request by devoncarew**
- remove the IDE topics category and move IDE pages up one level
- update redirects and url references
- fix https://github.com/flutter/website/issues/1764

### CODE REVIEW

**Comment by sfshaza2** [comment]
I thought we addressed this by auto-opening the IDE directory when opening the tab above, but this is fine, too.

**Comment by devoncarew** [comment]
> I thought we addressed this by auto-opening the IDE directory when opening the tab above, but this is fine, too.

Ah, I didn't know about that change. I think this is nice in that there's less nesting overall.

**Comment by sfshaza2** [comment]
True!

**Comment by chalin** [comment]
See #1775, _Sidenav: active-entry highlight broken by #1765 (IDEs)_

**Pull request merged**
