### PR TITLE
Updated the threading notice for platform channel responses.

### PR DESCRIPTION
**Pull request by gaaclarke**
This updates the guidelines about threading and the responses to platform channels.  Once the following PRs are on `main` all official platforms (minus web where it doesn't make sense) support thread-safe responses.

issue: https://github.com/flutter/flutter/issues/93945

Do no land until the following are on stable:
1) https://github.com/flutter/engine/pull/37689
1) https://github.com/flutter/engine/pull/37607
1) https://github.com/flutter/engine/pull/36909

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by sfshaza2** [comment]
@gaaclarke, are you ready to land this?

**Comment by gaaclarke** [comment]
@sfshaza2 it's another case of "ready to land when a feature reaches stable".  Let me know what's easiest for you.  Maybe we should have a tag for PR's like this for sorting?  That way it could be filtered out in your triage and audited when a new stable is being released?

**Comment by sfshaza2** [comment]
Yeah, I like the idea of a special label. I've added one.

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Review by atsansone — APPROVED** [review]

**Comment by Josiassejod1** [comment]
@gaaclarke if I understand the thread of work you have done in the last year, is it to prevent platform channels on windows from throwing errors similar to `MissingPluginException`?

Second after you merge this pr, when will this be ready and available to be used in projects?

**Comment by sfshaza2** [comment]
@Josiassejod1, this will be available in our next stable release. I believe it's available on the master channel now.

**Comment by gaaclarke** [comment]
> @Josiassejod1, this will be available in our next stable release. I believe it's available on the master channel now.

I think this may be on the next next stable release actually.  I may have missed the cutoff for the next one, no?

**Review by sfshaza2 — APPROVED** [review]
lgtm

@gaaclarke, does this need to wait before it can be pushed?

**Comment by sfshaza2** [comment]
Nevermind, I see the label. Yes, we wait. :D

**Comment by gaaclarke** [comment]
Yes please, when the mentioned PRs are on stable.

**Comment by parlough** [comment]
Looks like this didn't make the stable release like you expected. Converting to Draft in waiting for next one.

**Comment by sfshaza2** [comment]
@gaaclarke, where are we with this?

**Comment by gaaclarke** [comment]
> @gaaclarke, where are we with this?

Looks like this hasn't made it to a stable branch yet.

**Pull request merged**
