### PR TITLE
Add "Platform Channels in Federated Plugins"

### PR DESCRIPTION
**Pull request by stuartmorgan**

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
LGTM!

**Comment by sfshaza2** [comment]
@stuartmorgan, this is a PR to the archive branch for master. Can you update it to point to the main branch?

**Comment by stuartmorgan** [comment]
> @stuartmorgan, this is a PR to the archive branch for master.

@gspencergoog Can you update the template? The instructions there link to `master`, which redirects to `archived-master`, which I didn't notice while making the PR; it should be pointing to `main` now.

**Comment by stuartmorgan** [comment]
> Can you update it to point to the main branch?

Done.

**Comment by gspencergoog** [comment]
> Can you update the template? The instructions there link to master, which redirects to archived-master, which I didn't notice while making the PR; it should be pointing to main now.

Sure thing. Thanks for pointing it out.

**Comment by sfshaza2** [comment]
Yes, Stuart, thanks for pointing that out!

**Pull request merged**
