### PR TITLE
Update firebase.json

### PR DESCRIPTION
**Pull request by okrad**
Added reference to the design doc for Custom Tabs support proposal in the url_launcher plugin.

### CODE REVIEW

**Review by sfshaza2 — CHANGES_REQUESTED** [review]
Hi, @okrad! Thanks for your PR, but there are a couple issues. First, can you shorten the URL to:  https://docs.google.com/document/d/1GvsmPQz6aKixNUphL10XmSOL7M6nOH7W1jYwNp0LwnA
Also, it's failing the CI build because the LAST line should not have a comma. (Oh, that pesky pesky JSON formatting.)
Finally, I am sure this is conflicting with a PR I just merged that also updated this page so, can you:

- Pull the latest changes and merge with your copy of the repo
- Shorten the URL
- Remove that last comma

And, an FYI, all of Google has tomorrow (Friday) off, so I may not get to it until Monday.  :D

**Comment by okrad** [comment]
Hi @sfshaza2, thank you, sorry for the comma!
Seems ok now?

**Review by sfshaza2 — APPROVED** [review]
Fixed the conflict (which would have broken the build again). LGTM

**Review by sfshaza2 — COMMENTED** [review]
This has some issues, so I'm closing this and replacing it with PR https://github.com/flutter/website/pull/5560.

**Pull request closed without merging**
