### PR TITLE
Add Learning to Fly to videos page

### PR DESCRIPTION
**Pull request by parlough**
_Description of what this PR is changing or adding, and why:_ Learning to Fly is a great series as it follows along a pretty natural learning progression. It would be a great addition to the page :D

I just used the description from the first video but am open to suggestions.

_Issues fixed by this PR (if any):_ N/A

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]
/cc @khanhnwin

**Comment by khanhnwin** [comment]
Thanks @parlough!! :)

**Comment by sfshaza2** [comment]
@khanhnwin, will there be more Boring episodes of Learning to Fly? It's a bit confusing.

@domesticmouse, @khanhnwin, can you let me review textual PRs before approving and merging? I would have tweaked the text here, as "learn alongside her" is a tad cringeworthy. I've been feeling this way for some time now.  :)

**Comment by parlough** [comment]
I originally used the description of the video, but taking a closer look, it doesn't fit too well with the other playlist descriptions. If you have any suggestions, I'd be happy to make those adjustments :)

**Comment by khanhnwin** [comment]
Noted @sfshaza2 !

**Pull request merged**
