### PR TITLE
Update docs.flutter.io to point to api.flutter.dev.

### PR DESCRIPTION
**Pull request by kf6gpe**
As part of the .dev migration, we are moving our API documentation to the .dev domain too, and at the same time as we do so, we're renaming docs.flutter.* to api.flutter.* to adhere to the convention set by the dart folks.

This PR performs the necessary rename in the config. This should not be merged until after the first time we post a stable version of the API docs (e.g., 1.0.0 or greater) to the the appropriate Firebase project (docs-flutter-dev). The code is in place to do that push when we next update stable.

### CODE REVIEW

**Comment by gspencergoog** [comment]
Looks like you might need to rebase onto master again, but this LGTM.

**Comment by sfshaza2** [comment]
Where are we on this, @kf6gpe?

**Comment by kf6gpe** [comment]
Oh! Totally forgot to close this issue. It's been done for a while with a
firebase redirect. Just tested to confirm, too.

Thank you!!

**Comment by kf6gpe** [comment]
(This was done in Firebase. No need for the attached PR.)

**Comment by sfshaza2** [comment]
Thx!

**Pull request closed without merging**
