### PR TITLE
Main channel

### PR DESCRIPTION
**Pull request by mit-mit**
_Description of what this PR is changing or adding, and why:_
Change the public name of the development channel from `master` to `main`

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by atsansone — APPROVED** [review]

**Comment by mit-mit** [comment]
Sorry, I forgot that we're not ready to do this for FF. So I'm going to close this out for now.

**Review by gspencergoog — APPROVED** [review]
LGTM

**Review by johnpryan — APPROVED** [review]

**Review by timsneath — CHANGES_REQUESTED** [review]
Hmm -- before we do this I want to see an LGTM from Godofredo or someone in engprod. I know there are potentially other subtle side-effects of this change. The website is the least of our worries, I think.

**Comment by sfshaza2** [comment]
Followup questions:
- I see that the flutter/flutter repo is still using master. When does this change occur?
- In some of our breaking changes pages, we refer to the master API channel using "master-api.flutter.dev". Is this also changing at this time?

**Comment by godofredoc** [comment]
Created https://github.com/flutter/flutter/issues/121564 to start identifying the requirements to deprecate the master branch in flutter/flutter.

**Pull request closed without merging**
