### PR TITLE
Provide better comments and filenames for link references check

### LINKED ISSUE #6377: Document python script
### Describe the problem

Due to some crossed wires, in PR https://github.com/flutter/website/pull/6374, changes were made to the python script. We had agreed not to make infrastructure changes at the moment. 

Also, the new script has zero documentation. If we want to keep it intact, it needs some docs.

@AlexV525, can you provide more info?  @btobin, can you weigh in on these changes? Should we revert them, or is it sufficient to document them?

thx

### Expected fix

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AlexV525**
Improves readability of the link references check by adding comments and renaming files.

Resolves #6377 .

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by sfshaza2** [comment]
We are getting close to another website freeze and @btobin hasn't had time to review these changes. I may have to just close this PR as we get closer to freeze. It can be revisited later.

**Comment by domesticmouse** [comment]
FYI @khanhnwin

**Comment by RedBrogdon** [comment]
If I'm reading this right, it's adding documentation and clarity to a test that already exists, so we should go ahead and land it.

**Review by RedBrogdon — APPROVED** [review]

**Review by khanhnwin — APPROVED** [review]

**Review by sfshaza2 — APPROVED** [review]
lgtm!!!

**Pull request merged**
