### PR TITLE
Add ldps21 as author

### PR DESCRIPTION
**Pull request by ldps21**
_Description of what this PR is changing or adding, and why:_
Adding myself in the AUTHORS file

_Issues fixed by this PR (if any):_

_PRs or commits this PR depends on (if any):_

## Presubmit checklist

- [ ] This PR is marked as draft with an explanation if not meant to land until a future stable release.
- [X] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [X] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [X] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by sfshaza2 — COMMENTED** [review]
Hi Luis! We generally don't keep this page very up to data but, can I ask what justification you have for being added as an author?

**Comment by sfshaza2** [comment]
Actually, @ldps21, I'm going to close this PR. Please leave further comments on this PR if you still want to discuss.

**Comment by ldps21** [comment]
@sfshaza2 Hi! I just thought it was the regular process once you made a contribution to the website.

I figured it was like that just like the author page in the other flutter project. If you don't keep this page up to date on that there is no problem.

**Comment by sfshaza2** [comment]
Yeah, not really. We should probably get rid of that page. Note that my name is not on that list and I am the lead tech writer for Flutter and "owner" of docs.flutter.dev. I've been here at Google for over 10 years - I was hired to document Dart (and before that, I documented Java at Sun and Oracle for 14 years), and then was asked to document Flutter. I've written MANY pages on this site.  ;)

**Pull request closed without merging**
