### PR TITLE
remove wacky JS fixing sidenav scrolling

### PR DESCRIPTION
**Pull request by sethladd**
Now the nav stays visible, even on a laptop.

I tested on desktop and laptop, wide and narrow screens.

### CODE REVIEW

**Comment by sethladd** [comment]
@mit-mit ptal

**Comment by mit-mit** [comment]
I can't tell the difference, but I'm also not entirely sure what issue I should be looking for. Can you elaborate?

I thought it was this flickering issue when clicking items, but that doesn't seem to be fixed:
flicker

**Comment by sethladd** [comment]
If you're on a laptop, a macbook 13 inch, for example, the side nav would have scrolled out of view. It would not have stayed in place.

With this patch, the left nav stays in place even on a laptop (unless you're on mobile, it will scroll then).

**Comment by sethladd** [comment]
re: flickering, we're going to fix that by simply removing all the javascript from the left nav :) But that's a separate patch

**Comment by sethladd** [comment]
TBR= @mit-mit

**Pull request merged**
