### PR TITLE
Add go link to Updating Material 3 Sliders doc.

### PR DESCRIPTION
**Pull request by TahaTesser**
Adds a go-link to " Updating Material 3 Sliders " design doc for flutter web.

## Presubmit checklist

- [ ] This PR is marked as draft with an explanation if not meant to land until a future stable release.
- [ ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ ] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by TahaTesser** [comment]
> I can't seem to access the doc, whether I'm signed in or not. Can you make sure the link is one that's open for commenting for anyone with the link? Thanks!

Apologies, made the doc public. Thanks!

**Comment by parlough** [comment]
> Apologies, made the doc public. Thanks!

Thanks @TahaTesser, I'm able to access it now! But I can't seem to leave comments. Can you change it from viewing to commenting/suggesting?

**Comment by TahaTesser** [comment]
> > Apologies, made the doc public. Thanks!
> 
> Thanks @TahaTesser, I'm able to access it now! But I can't seem to leave comments. Can you change it from viewing to commenting/suggesting?

Done

**Review by parlough — APPROVED** [review]
Thanks! I'm now able to view and suggest changes to the doc :)

**Pull request merged**
