### PR TITLE
Add a terminology section to the docs style guide

### PR DESCRIPTION
**Pull request by abarth**
Fixes https://github.com/flutter/flutter/issues/4761

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM

**Comment by sethladd** [comment]
Can you add this to https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo too?

See also https://github.com/flutter/flutter/issues/5826

**Comment by abarth** [comment]
Oh, we have two copies of the style guide...  Will fix.

**Comment by sethladd** [comment]
> we have two copies of the style guide

Sorry about that. Temporarily...

**Pull request merged**
