### PR TITLE
Fixing broken border radius example

### PR DESCRIPTION
**Pull request by RedBrogdon**
Fixes some breakages in the example code caused by the shift to Flutter 2.5. Highlights include:

* Removal of `accentColor` and `buttonColor` references.
* Removal of a widget test in one example that was directly using path_provider to modify the underlying file system.
* Updates of code using `ShortcutManager`'s `handleKeypress` method, which lost an optional param.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
More theming issues:

```
=> Example: examples/cookbook/design/themes
+ cd examples/cookbook/design/themes
+ flutter packages get
Running "flutter pub get" in themes...                             882ms
+ flutter analyze .
Analyzing themes...                                             

   info • 'accentColor' is deprecated and shouldn't be used. Use colorScheme.secondary instead. For more information, consult the migration guide at https://flutter.dev/docs/release/breaking-changes/theme-data-accent-properties#migration-guide. This feature was deprecated after v2.3.0-0.1.pre. • lib/theme.dart:8:7 • deprecated_member_use
   info • 'accentColor' is deprecated and shouldn't be used. No longer used by the framework, please remove any reference to it. For more information, consult the migration guide at https://flutter.dev/docs/release/breaking-changes/theme-data-accent-properties#migration-guide. This feature was deprecated after v2.3.0-0.1.pre. • lib/theme.dart:21:38 • deprecated_member_use
```

Is this code being pulled in from the flutter codelabs repo?

**Comment by hrishikesh-kadam** [comment]
@domesticmouse This PR is just a commit away to pass the CI.
Required patch - https://github.com/hrishikesh-kadam/flutter-website/commit/80787ea788f4d0dce4c5bb237b9fc8b524962ac5

**Comment by hrishikesh-kadam** [comment]
@RedBrogdon @domesticmouse I am too working on making the CI pass as I have another PR to be submitted.
Please refer to this branch https://github.com/hrishikesh-kadam/flutter-website/commits/make-test-pass to save your time.

**Comment by RedBrogdon** [comment]
> Is this code being pulled in from the `flutter/codelabs` repo?

I don't believe so. The page has been around in the cookbook since at least 2018, so I'd guess it's something Brian Egan wrote a while back.

> @RedBrogdon @domesticmouse I am too working on making the CI pass as I have another PR to be submitted.
Please refer to this branch https://github.com/hrishikesh-kadam/flutter-website/commits/make-test-pass to save your time.

Thanks for letting me know you're working on it. I think part of the issue here is that accentColor *used* to be a convenient ThemeData property to use when demonstrating how to change one aspect of a theme. We can certainly unbreak the code by switching the code to use secondaryColor, but it makes the examples needlessly harder to understand.

I'm mostly done with a change that will ditch accentColor/secondaryColor entirely and use a different property to illustrate the principle. My schedule willing, I should have this PR updated with that change today.

**Review by sfshaza2 — COMMENTED** [review]
I'm happy to LGTM and merge this, @RedBrogdon, but it sounds like I should wait.

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
@sfshaza2 I'll land this once the tests go green

**Comment by domesticmouse** [comment]
Landing with link issues because this PR doesn't impact the failures.

**Pull request merged**
