### PR TITLE
Add Flutter macOS build and release guide

### PR DESCRIPTION
**Pull request by craastad**

### CODE REVIEW

**Comment by timsneath** [comment]
I _love_ this -- thank you so much for your submission!

**Comment by domesticmouse** [comment]
Hey @craastad, can you please sign the CLA? We need that before we can merge this PR =)

**Comment by craastad** [comment]
@googlebot I signed it!

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
After this lands, we will need to amend the content of /desktop. 

Is it worth pulling out a Windows page with similar content structure?

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Pull request merged**
