### PR TITLE
Update codelabs and snippets

### PR DESCRIPTION
**Pull request by domesticmouse**
_Description of what this PR is changing or adding, and why:_

_Issues fixed by this PR (if any):_

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by domesticmouse** [comment]
Does the delta on this look correct @khanhnwin?

**Comment by khanhnwin** [comment]
Oops I just pulled this in on! https://github.com/flutter/website/pull/7347

**Comment by domesticmouse** [comment]
> Oops I just pulled this in on! #7347

Yup, you need this for #7347, I was just making sure it looked sane.

**Comment by domesticmouse** [comment]
@khanhnwin do you want to lgtm and land this PR?

**Comment by khanhnwin** [comment]
Landed!

**Pull request merged**
