### PR TITLE
Add go link for codelab

### PR DESCRIPTION
**Pull request by Piinks**
This adds a go link for the sliver codelab

### CODE REVIEW

**Review by johnpryan — APPROVED** [review]

**Comment by sfshaza2** [comment]
OK, I know I'm late to the game here. But I really dislike calling these
new things "codelabs". How do we distinguish these from our other codelabs?
Can we call them workshops instead?

**Comment by Piinks** [comment]
All of the new dartpad UI uses 'codelab', would it be confusing to mix terms?

**Comment by sfshaza2** [comment]
I know. I wish I had been involved in that decision. I truly don't like it.

**Comment by Piinks** [comment]
Is it ok to merge this then? I am using it for a rehearsal.

**Comment by sfshaza2** [comment]
I haven't checked, but Andrew just submitted a similar PR. Are they
different?

**Comment by Piinks** [comment]
https://github.com/flutter/website/pull/5709 looks the same, and does not use the offending terminology. Closing.

**Comment by sfshaza2** [comment]
OK, I just landed @RedBrogdon's similar PR, but they are different. All 3 of his links to go the high level dartpad page and your link went to your workshop page. You might want to re-open and update this PR?

**Comment by Piinks** [comment]
Per the description in #5709 Andrew said he would be adding the proper links later. I will leave that to him.

**Pull request closed without merging**
