### PR TITLE
Some cleanup of the assets page.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by Sfshaza** [comment]
Hey! This afternoon the API docs changed and the ScrollSimulation class was removed (and replaced with two classes). It was hanging me up, so I created a PR that Adam approved. I've merged it, so if you get the latest, your submit should work.

**Comment by eseidelGoogle** [comment]
@Hixie looks like this is waiting merge?

**Comment by Hixie** [comment]
Travis says:
```
- _site/tutorials/layout/index.html
  *  External link https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/buttons_demo.dart failed: 404 No error
  *  External link https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/cards_demo.dart failed: 404 No error
  *  External link https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/grid_list_demo.dart failed: 404 No error
htmlproofer 3.4.0 | Error:  HTML-Proofer found 3 failures!
```

**Comment by sethladd** [comment]
Build is green now.

**Pull request merged**
