### PR TITLE
Typography images

### PR DESCRIPTION
**Pull request by sfshaza2**
I need these images for the new typography page. I have to put them in a separate PR so that they are on the live website, or the build will fail when I push the typography PR.

### CODE REVIEW

**Comment by sfshaza2** [comment]
@khanhnwin, ARGH. Can you back OUT the changes to the splash screen and typography file? This PR should ONLY be images.

**Comment by sfshaza2** [comment]
(I'd ask Parker, but his computer is broken)

**Comment by sfshaza2** [comment]
Thanks, @khanhnwin!

**Comment by khanhnwin** [comment]
Done @sfshaza2 - should be good to land whenever build turns green!

**Review by khanhnwin — APPROVED** [review]

**Pull request merged**
