### PR TITLE
Fix links to Visual Studio 2019

### PR DESCRIPTION
**Pull request by ashellunts**
Existing links lead to Visual Studio 2022

## Presubmit checklist
- [x ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x ] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by parlough** [comment]
It does seem VS 2022 is currently only [supported on the `master` branch](https://github.com/flutter/flutter/issues/85922#issuecomment-979483961) so it makes sense to keep a 2019 link here for now, but I'm not sure it's a good idea to have a link which automatically downloads a file. Users tend to dislike this behavior.

Is there a different link which presents the option to download it?

**Comment by ashellunts** [comment]
> It does seem VS 2022 is currently only [supported on the `master` branch](https://github.com/flutter/flutter/issues/85922#issuecomment-979483961) so it makes sense to keep a 2019 link here for now, but I'm not sure it's a good idea to have a link which automatically downloads a file. This can be hostile to users.
> 
> Is there a different link which presents the option to download it?

I think it does not exist for community edition. There is one for professional edition but that requires MS login and it should be licensed.

**Review by sfshaza2 — COMMENTED** [review]
Thanks for this PR, @ashellunts. This updated link automatically downloads Visual Studio 2019, rather than goes to a page that lets you choose. Also, the updated link gives you no indication. I am inclined to reject this. Why do you think this is preferable, @ashellunts?

**Comment by ashellunts** [comment]
With current link one gets VS 2012 that does not work with latest release
version. So I thought having link to VS2019 is a good idea. Unfortunately
there is no better link.

Shams Zakhour (ignore Sfshaza) ***@***.***> schrieb am Do.,
2. Dez. 2021, 19:49:

**Comment by domesticmouse** [comment]
Raise a bug against me to add some verbiage describing how to navigate the page to get VS 2019.

**Comment by ashellunts** [comment]
> Raise a bug against me to add some verbiage describing how to navigate the page to get VS 2019.

https://github.com/flutter/website/issues/6525

**Comment by sfshaza2** [comment]
Thanks, @ashellunts! I'm closing this PR.

**Pull request closed without merging**
