### PR TITLE
New breaking change: Network Policy on iOS and Android

### PR DESCRIPTION
**Pull request by mehmetf**

### CODE REVIEW

**Comment by mehmetf** [comment]
@Sfshaza please take another look. The release info is updated.

**Comment by sfshaza2** [comment]
@mehmetf, I'm happy to approve this, but can you fix the conflict in the index file?

**Comment by mehmetf** [comment]
Conflict resolved.

**Comment by vamsi452** [comment]
How to fix issue with iOS app crashing at flutter engine 

5   Flutter                             0x000000010a949967 +[FlutterDartProject domainNetworkPolicy:] + 352
Screen Shot 2020-09-11 at 7 12 24 AM

**Comment by mehmetf** [comment]
This is being tracked at https://github.com/flutter/flutter/issues/65580

**Pull request merged**
