### PR TITLE
Update URL strategies page

### PR DESCRIPTION
**Pull request by johnpryan**
This updates the URL strategies page.

When [1980492](https://github.com/flutter/flutter/commit/1980492) lands in stable, we can simplify some of the steps:

````
By default, Flutter uses HashUrlStrategy.
To change to PathUrlStrategy, use the setPathUrlStategy() function before calling runApp(): 

```dart
import 'package:flutter/material.dart';
import 'package:flutter_web_plugins/flutter_web_plugins.dart';

void main() {
  usePathUrlStrategy();
  runApp(const MyApp());
}
```

This method is a no-op on non-web platforms.
````

cc: @mdebbar

### CODE REVIEW

**Review by sfshaza2 — COMMENTED** [review]
Also, the file itself will need to be moved. At any rate, I'll look at this once we've landed the updated website.

**Comment by sfshaza2** [comment]
I am out next week, but let me know when you plan to take it out of draft, @johnpryan.

**Comment by johnpryan** [comment]
Staged: https://flutter-website-jr-stagi-988d4.web.app/development/platform-integration/web-url-strategies/

**Comment by johnpryan** [comment]
https://github.com/flutter/flutter/commit/1980492 isn't in the stable channel yet, so I'll take this out of draft.

**Comment by domesticmouse** [comment]
> [flutter/flutter@1980492](https://github.com/flutter/flutter/commit/1980492) isn't in the stable channel yet, so I'll take this out of draft.

I'm confused. You've marked this PR as ready for review (by removing from draft) yet the body of this comment indicates that this feature isn't shipped yet. By my understanding this PR should be marked draft until the feature is in stable, yeah?

**Comment by johnpryan** [comment]
This version is accurate for the stable channel. When https://github.com/flutter/flutter/commit/1980492 lands in stable these docs can be simplified, since conditional imports won't be needed anymore.

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
@johnpryan is this good to land?

**Comment by johnpryan** [comment]
Oops, I didn't realize there was already a https://docs.flutter.dev/development/ui/navigation/url-strategies page. Let me see if I can combine these two docs...

**Comment by johnpryan** [comment]
Ready for another look

**Pull request merged**
