### PR TITLE
Fixed type: '&lt;' text to '<' in github URL

### PR DESCRIPTION
**Pull request by Tapaswi846580**
Fixed typo: ‘ &lt; ’  text to ‘<‘ in github URL

### CODE REVIEW

**Comment by Tapaswi846580** [comment]
@googlebot I signed it!

**Comment by Tapaswi846580** [comment]
@googlebot I fixed it.

**Comment by Tapaswi846580** [comment]
@googlebot I fixed it.

**Comment by Tapaswi846580** [comment]
@googlebot I consent.

**Comment by Tapaswi-AksharMine** [comment]
@googlebot I consent.

**Comment by Tapaswi846580** [comment]
@googlebot I consent.

**Review by sfshaza2 — APPROVED** [review]
Hm. That is very interesting! LGTM

**Pull request merged**
