### PR TITLE
Add "Conditionally listen on InheritedWidgets" design doc

### PR DESCRIPTION
**Pull request by rrousselGit**
_Description of what this PR is changing or adding, and why:_

_Issues fixed by this PR (if any):_

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by parlough — CHANGES_REQUESTED** [review]
Thanks for working on this design doc and sharing! For design doc redirects, we start them with `/go` by contention. You can find similar links nearby at:

https://github.com/flutter/website/blob/962a7de30db91f2aed1d16a513f63b03750d6c7d/firebase.json#L407-L409

**Comment by rrousselGit** [comment]
Ah I knew something felt weird! Done

**Review by parlough — APPROVED** [review]
Thank you!

**Pull request merged**
