### PR TITLE
Rename Accessibility & localization to Accessibility & internationalization

### PR DESCRIPTION
**Pull request by RoleWong**
…ionalization

This PR updates the directory name from "Accessibility & Localization" to "Accessibility & Internationalization" for better consistency with the document titles within the directory.

Currently, the directory contains two documents: "Accessibility" and "Internationalization". The term "Localization" in the directory name does not accurately reflect the content of the "Internationalization" document. By updating the directory name, we can ensure that both document titles are represented consistently in the directory name.

With this change, developers browsing the documentation will have a clearer understanding of the content covered in this directory.

_Issues fixed by this PR (if any):_

## Presubmit checklist

- [yes ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ yes ] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [yes  ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by atsansone** [comment]
@RoleWong : We appreciate the change, but could you provide 4 more changes?

1. Review and accept the Google CLA.
2. Update the firebase.json redirect file so we don't generate any 404 errors.
3. Update the _config.yml with the updated paths.
4. Update the src/_data/sidenav.yml with the updated paths.

**Comment by domesticmouse** [comment]
Build failed, but I can't see why from the logs. @parlough can you spot the failure in the CI output?

**Comment by atsansone** [comment]
@domesticmouse : Links were changed without redirects. That caused the failures.

**Comment by domesticmouse** [comment]
CLA failure. That's never good.

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
Please add redirects to turn the CI green before landing

**Comment by parlough** [comment]
Hi! Thanks so much for the contribution and for signing the CLA!

As the others said, you'll need to update a few locations:

1. Update the links to the category and pages in the sidenav - https://github.com/flutter/website/blob/389fa7126a4aa8374e1bdd1a62b21c12f06b0d6f/src/_data/sidenav.yml#L246-L252

2. Update the existing throughout the site referencing the old destination:

   1. `{{site.url}}/ui/accessibility-and-localization/internationalization` -> `{{site.url}}/ui/accessibility-and-internationalization/internationalization`
   2. `{{site.url}}/ui/accessibility-and-localization/internationalization` -> `{{site.url}}/ui/accessibility-and-internationalization/accessibility`
  
3. Add redirects for these three links to the `firebase.json`. This is especially important so external links to the old pages continue to work.

Let me know if you have any issues with those steps. We'd also be happy to finish them if that's easier for you. Thanks again :)

**Review by parlough — APPROVED** [review]
Thank you for making all of those adjustments! Looks good to me :) 

I updated the last few remaining links.

**Pull request merged**
