### PR TITLE
Add recent WotW videos to docs

### PR DESCRIPTION
**Pull request by khanhnwin**
_Description of what this PR is changing or adding, and why:_ Adding a bunch of the recent Widget of the Week videos to some related docs pages. Also added a class to CSS that makes videos fill the content width.

All videos added available on staging site: https://yenkhanh-flutter.web.app/

_Issues fixed by this PR (if any):_

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
lgtm. But I noticed that, within the cookbook files, the videos were added without context?

**Comment by khanhnwin** [comment]
For the cookbook files, I added the videos immediately after the widgets/packages were introduced in the tutorial and considered that the context. Should I add an additional blurb?

**Comment by sfshaza2** [comment]
I'd like to see it staged.

**Comment by khanhnwin** [comment]
The staged PR is here: https://yenkhanh-flutter.web.app/

If you want, I can also add the blurb(s) and stage that as well!

**Comment by sfshaza2** [comment]
Yes, please! Since it was merged, I could see it live. But I would like blurbs added.

**Comment by khanhnwin** [comment]
Done! #7410

**Pull request merged**
