### PR TITLE
Adding a _code directory.

### PR DESCRIPTION
**Pull request by Sfshaza**
@sethladd, here's a simple HelloWorld app.

### CODE REVIEW

**Comment by sethladd** [comment]
Oh, wow. Are we certain we want the entire app? I thought we just needed the app's .dart file here?

**Comment by Sfshaza** [comment]
Sure, we can do that, though all of them are called main.dart. Maybe retain the directory name and have main.dart under? (Sans lib directory.)

**Comment by sethladd** [comment]
Makes sense!

**Comment by Sfshaza** [comment]
Seth agreed (offline) that we'll use a directory name and it will contain main.dart. I'm closing this PR.

**Pull request closed without merging**
