### PR TITLE
added Udemy course for the german Flutter Community

### PR DESCRIPTION
**Pull request by OpenSphereSoftware**
Hi my name is Max Berktold. I'm a Flutter freelancer and Udemy lecturer out of passion. I would like to include my Flutter course here. I hope I can help the community with it. I am already helping hundreds of people there to start professional app development with flutter. At the same time, I'm building a German flutter community.
Thanks for the work and this wonderful framework!

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
lgtm! But please sign the CLA!

**Comment by OpenSphereSoftware** [comment]
@sfshaza2 
Thanks for the quick processing. 
Sorry never before contributed to google. I signed now a CLA on official Website.
What are the next steps?

**Comment by OpenSphereSoftware** [comment]
I understand that perfectly.Thank you !
I have activated email privacy on github. (It could be because of it) Nevertheless, PR's should hang together with my account. 
Today I signed a CLA with the mail that is stored on Github and just did it again.

Bildschirmfoto 2021-12-16 um 13 44 03

**Comment by domesticmouse** [comment]
Hi @OpenSphereSoftware, we also need a CLA for your @MBP-von-Max.fritz.box email address, because that is the email address baked into this PR. 

You can see the issue details at https://github.com/flutter/website/pull/6556/checks?check_run_id=4555025817

**Comment by OpenSphereSoftware** [comment]
This is an auto applied email. I cannot sign a cla for that. 

I just checket the git log etc. It seems so that somehow my environment variables were messed up. (git config was not working to set the author email)
I now did this manually but this will not effect previous commits. ( set to the mail i habe signed cla )

So how do we do? I dont want to waste your time anymor :) 

Should i close this one and reopen another one?

Best regards
Max

**Comment by domesticmouse** [comment]
Opening a new PR with the right email is probably the easiest path forward.

**Comment by OpenSphereSoftware** [comment]
@domesticmouse   closing it.  new one is already open :). Hoping it works now.  I checked the logs and it seems good now. 
https://github.com/flutter/website/pull/6586

**Pull request closed without merging**
