### PR TITLE
Update widgets.json

### PR DESCRIPTION
**Pull request by fxsalazar**
Delete redundant `GridView`, `ListView` elements.

### CODE REVIEW

**Comment by fxsalazar** [comment]
I signed it!

**Comment by sfshaza2** [comment]
It still seems to think you haven't signed the CLA, @fxsalazar.

**Comment by fxsalazar** [comment]
🤔  but I did. I went and updated my username. is it good now @sfshaza2 ?

**Comment by sfshaza2** [comment]
Yes, indeedy!  Thanks for this PR!

**Pull request merged**
