### PR TITLE
Link to article for GetIt state management

### PR DESCRIPTION
**Pull request by suragch**
This article has been published for a little over a month now and since I've gotten a positive response from it I'm submitting it here.

Full disclosure: this is a link to my own Medium article. I've used the friend link, though, so no one should be blocked.

The article could go in the General Overview section, but since I do use GetIt package, I've put it under the GetIt section.

### CODE REVIEW

**Comment by piedcipher** [comment]
Type in the PR title: `GitIt`.

`GetIt` :heavy_check_mark:

**Comment by sfshaza2** [comment]
I defer to @filiph.

**Comment by filiph** [comment]
LGTM!

**Comment by illuminated-shade** [comment]
@NathanAndrewTurnerIlluminati

**Pull request merged**
