### PR TITLE
Add instructions to download iOS Simulator

### PR DESCRIPTION
**Pull request by vashworth**
Adds instructions to download iOS Simulator. Starting with Xcode 15, the iOS Simulator is no longer downloaded and installed with Xcode and must be done separately.

Part 1 of https://github.com/flutter/flutter/issues/129558

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by parlough** [comment]
@vashworth Did you intend for this to be a draft or is it ready for review? It sounds like this would be relevant even now.

**Comment by vashworth** [comment]
> @vashworth Did you intend for this to be a draft or is it ready for review? It sounds like this would be relevant even now.

Yes I intentionally left it as a draft, I was planning to add it closer to when Xcode 15 officially releases (probably September).

**Review by atsansone — APPROVED** [review]

**Comment by vashworth** [comment]
@atsansone @parlough This is ready to be merged in now

**Review by parlough — APPROVED** [review]
Thanks!

**Pull request merged**
