### PR TITLE
Add 3 more cupertino widgets to the catalog

### PR DESCRIPTION
**Pull request by xster**
Fixes https://github.com/flutter/flutter/issues/21699
Fixes https://github.com/flutter/flutter/issues/21550

### CODE REVIEW

**Comment by Sfshaza** [comment]
@xster, would you mind submitting two PRs? We aren't, in general, doing anything to the master branch unless it's a P0. We are working on the new site, on the dash branch.

**Comment by xster** [comment]
Hi Shams. I'm not too sure what you meant. Did you mean submit the same PR on top of both the master branch and the dash branch?

**Comment by xster** [comment]
Here's the other PR for the dash branch https://github.com/flutter/website/pull/1313

**Comment by Sfshaza** [comment]
Thanks!

**Comment by Sfshaza** [comment]
@matthew-carroll, I know you're swamped, but can you give this a quick review? It looks OK to me.

**Pull request merged**
