### PR TITLE
Remove extra text when copy example code

### LINKED ISSUE #3850: 'Windows install' page issue
Page URL: https://flutter.dev/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description of issue:

Hello, when clicking the "Copy code"-button from the git line, the part "C:\src>git" get's copied as well, which we don't want to paste into cmd of course.

### PR DESCRIPTION
**Pull request by Nishikoh**
Remove extra text when copy example code. 
Fix #3850

### CODE REVIEW

**Comment by sfshaza2** [comment]
@kwalrath, can you stage and test this?

**Comment by kwalrath** [comment]
Staged: https://kw-flutter-1.firebaseapp.com/docs/get-started/install/windows

**Comment by kwalrath** [comment]
This seems low risk, and the Mac/Linux copy still works, so I'm going to merge it.

**Comment by kwalrath** [comment]
Thank you very much, @Nishikoh, for the bug fix!

**Pull request merged**
