### PR TITLE
Updating the editor.md file

### PR DESCRIPTION
**Pull request by albertodev01**
_Description of what this PR is changing or adding, and why:_ Updated recommended version of JetBrains IDEs

_Issues fixed by this PR (if any):_ https://github.com/flutter/website/issues/6843

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]
PTAL @sfshaza2

**Review by sfshaza2 — COMMENTED** [review]
Is this the latest? There was an update to the IntelliJ docs that was sent out today and the numbers here seem to be different. @stevemessick, can you comment?

**Comment by stevemessick** [comment]
Those version numbers are correct today. However, this is the last release we are doing that will support Arctic Fox (2020.3). Rather than use version numbers, would it be acceptable to say "latest stable" instead? We (and JetBrains and Android Studio) encourage users to update frequently. This file will need to be updated at least annually, otherwise.

**Comment by sfshaza2** [comment]
Thanks, @stevemessick! @albertodev01, how do you feel about Steve's suggested change?

**Comment by sfshaza2** [comment]
I'm going to go ahead and land this PR. We can revisit the "latest stable" suggestion in future.

**Pull request merged**
