### PR TITLE
Add `FlutterDebugger` to sidenav

### PR DESCRIPTION
**Pull request by lijy91**

### CODE REVIEW

**Comment by lijy91** [comment]
I signed it!

**Comment by sfshaza2** [comment]
Hi, @lijy91! Thanks for this PR. We keep a tight limit on the side navigation menu, so I can't accept this PR. But, what about adding your debugging tool info to the /docs/testing/debugging page? Maybe add a section for third party debugging. This approach will scale as other tools come online.

**Comment by lijy91** [comment]
@sfshaza2 Can you add this part?

**Comment by sfshaza2** [comment]
Sure, @lijy91, but I can't get to it immediately.

**Comment by lijy91** [comment]
@sfshaza2 If you have any news, please let me know.

**Pull request closed without merging**
