### PR TITLE
updated status of multiple flutters

### PR DESCRIPTION
**Pull request by gaaclarke**
Updated multiple flutters documentation to reflect the state of the project.
fixes https://github.com/flutter/flutter/issues/96234

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by gaaclarke** [comment]
cc @timsneath @xster

**Comment by timsneath** [comment]
Shift focus of article from 1.x->2.x to a 2.x world

**Comment by timsneath** [comment]
Shift article

**Comment by timsneath** [comment]
This looks great! I've made some further edits to shift the focus of the article somewhat. When it was originally written, it explained how things had changed from 1.x to 2.0. Now that 2.0 and above has >99% usage share, it makes sense to describe the feature in its own right, rather than as a change.

Accordingly, I added a paragraph up front to expand on the scenario, as well as removing the number of instances of "In Flutter 2.0.0". I also moved the aside around JIT compilation lower down.

**Comment by gaaclarke** [comment]
@timsneath LGTM, thanks.

**Review by domesticmouse — APPROVED** [review]

**Pull request merged**
