### PR TITLE
fix minor typos

### PR DESCRIPTION
**Pull request by mohamedhayibor**
Remove extra "o" in "toools".

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
@mohamedhayibor We'll need you to sign the CLA before we can land your patch.

**Comment by mit-mit** [comment]
Hi @mohamedhayibor did you have a chance to sign the CLA? We unfortunately cannot take the PR before that has happened.

**Comment by mohamedhayibor** [comment]
Sorry for the delayed response. I totally missed the notification. I signed the agreement back in Nov. 4th. Is it the right one? Let me know if I need to sign it again.
screen shot 2016-11-14 at 11 13 12 am

**Pull request merged**
