### PR TITLE
docs: Add links for developer support.

### PR DESCRIPTION
**Pull request by qchong**
Fixes https://github.com/flutter/flutter/issues/4862

@sethladd ptal

Staged preview: https://flutter-io-staging-69a8a.firebaseapp.com/

### CODE REVIEW

**Comment by sethladd** [comment]
lgtm

thanks!

**Comment by qchong** [comment]
I signed it.

On Mon, Jul 11, 2016 at 11:25 AM, googlebot <notifications@github.com>
wrote:

> Thanks for your pull request. It looks like this may be your first
> contribution to a Google open source project. Before we can look at your
> pull request, you'll need to sign a Contributor License Agreement (CLA).
>
> 📝 *Please visit https://cla.developers.google.com/
> <https://cla.developers.google.com/> to sign.*
>
> Once you've signed, please reply here (e.g. I signed it!) and we'll
> verify. Thanks.
> ------------------------------
>
>    - If you've already signed a CLA, it's possible we don't have your
>    GitHub username or you're using a different email address. Check your
>    existing CLA data <https://cla.developers.google.com/clas> and verify
>    that your email is set on your git commits
>    <https://help.github.com/articles/setting-your-email-in-git/>.
>    - If you signed the CLA as a corporation, please let us know the
>    company's name.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/flutter/website/pull/255#issuecomment-231821255>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFtXZSJ6AO7Ua-dtL4Sdgo5oFFzn8eJpks5qUoqJgaJpZM4JJpJd>
> .
>



-- 

Quddus Chong | Technical Writer - Turquoise | quddusc@google.com

**Comment by qchong** [comment]
@sethladd I believe I've resolved the issues that Analyzer was previously encountering. Can you PTAL? Also, not sure why the CLA check is failing. Is there some other configuration change I need to make?

**Comment by sethladd** [comment]
lgtm thanks!

**Pull request merged**
