### PR TITLE
Remove codelabs.flutter-io.cn

### PR DESCRIPTION
**Pull request by AmosHuKe**
_Description of what this PR is changing or adding, and why:_

**[codelabs.flutter-io.cn](https://codelabs.flutter-io.cn)** site will be shut down in the near future ([internal discussions](https://github.com/cfug)).
We are now using **[codelabs.developers.google.cn](https://codelabs.developers.google.cn)**.

## Presubmit checklist

- [x] This PR is marked as draft with an explanation if not meant to land until a future stable release.
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by sfshaza2 — COMMENTED** [review]
Why remove this? The page is still there. I can't read it, but it's still there. Is it no longer being maintained?

**Comment by parlough** [comment]
> Why remove this? The page is still there. I can't read it, but it's still there. Is it no longer being maintained?

I'm assuming they won't be, instead relying on the translations hosted on the codelabs website (and maybe gelocation-based redirects from google.com to google.cn?).

@AmosHuKe Will Chinese network users need to specifically go to the google.cn version or will the google.com codelab links work?

**Comment by AmosHuKe** [comment]
@sfshaza2 @parlough 

> but it's still there. Is it no longer being maintained?

Yes~ we have decided in internal discussions to shtu down **codelabs.flutter-io.cn** in the near future...
The site has not been maintained for a long time, therefore, all new codelabs do not work.
**codelabs.developers.google.cn** already does the same thing, and better!

> (and maybe gelocation-based redirects from google.com to google.cn?)
> Will Chinese network users need to specifically go to the google.cn version or will the google.com codelab links work?

**google.com** does not have geolocation-based redirects, Chinese network users must specifically go to the **google.cn** version.
Currently, flutter.cn will replace **codelabs.flutter-io.cn** with **codelabs.developers.google.cn**.

**Comment by AmosHuKe** [comment]
Eh.. maybe instead of removing the whole notification, I should just replace **codelabs.flutter-io.cn** with **codelabs.developers.google.cn**.
Do I need to add some Chinese notifications in there?

**Review by parlough — APPROVED** [review]
Thanks for the update and the clarifications @AmosHuKe!

I think it's fine to remove it, someone within China that can't access the main site will likely be reading this from `flutter.cn` which will have the new link. For other potential use cases, I can't imagine using `google.cn` over `google.com` will help.

If we get reports from this page that developers are having trouble accessing the codelabs, we can revisit adding a note back.

**Comment by sfshaza2** [comment]
Thanks for your clarification, @AmosHuKe!

**Pull request merged**
