### PR TITLE
Fix linkchecker hang

### PR DESCRIPTION
**Pull request by mit-mit**
Move link checker config to a Rakefile to make it more maintainable.

Extend that config to skip httpbin.com, as that site appears to make the checker hang.

### CODE REVIEW

**Comment by sethladd** [comment]
lgtm

(curious why we need to run this through rake?)

**Comment by mit-mit** [comment]
> lgtm

Let's see if travis passes this time first :-)

> (curious why we need to run this through rake?)

It was getting pretty unwieldy to pass all the config parameters through the command line, and with rake they are in a nicely formatted Rakefile (see the new file in the PR)

**Comment by mit-mit** [comment]
Woot, it's passing!

**Comment by sethladd** [comment]
Nice!

**Pull request merged**
