### PR TITLE
Introduce profile mode in Get Started

### PR DESCRIPTION
**Pull request by liyuqian**
Fixes https://github.com/flutter/flutter/issues/31439

### CODE REVIEW

**Comment by liyuqian** [comment]
Ping...

**Comment by sfshaza2** [comment]
@liyuqian, @justinmc, I looked at this PR last week. I didn't accept because I had a number of issues with it. I'll have to fix it in another PR.

**Comment by justinmc** [comment]
@Sfshaza Whoops sorry to jump the gun on my review.  If you need a quick review on that follow up PR let me know.

**Comment by liyuqian** [comment]
Oops, I'm sorry too. Please let me if there's anything that I can help write or review.

**Pull request merged**
