### PR TITLE
chore: Updated getting started codelab

### PR DESCRIPTION
**Pull request by albertodev01**
_Description of what this PR is changing or adding, and why:_

We have updated the excerpts, now the website page needs to be updated too

_Issues fixed by this PR (if any):_

Follow up for https://github.com/flutter/codelabs/pull/265

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by albertodev01** [comment]
I am following the advices in the README but I'm getting some weird errors when I try to run the `refresh-code-excerpts.sh` tool. Can you confirm that CI is failing because the code in the markdown file is not matching the one in the Dart files? @domesticmouse 

I thought that updating the code files in the [other PR](https://github.com/flutter/codelabs/pull/265) would have been enough

**Comment by domesticmouse** [comment]
I wound up reverting your other PR in https://github.com/flutter/codelabs/pull/271 because it broke the website build. We need to do a co-ordinated push of PRs across both repositories. Given that our timezones do not align, I'd suggest chatting with @khanhnwin about how to push this forward.

**Comment by khanhnwin** [comment]
Hey @albertodev01 - It does look like the build is failing due to the out of date code excerpts. What error are you getting when you run `refresh-code-excerpts.sh`? Thanks!

**Comment by albertodev01** [comment]
@khanhnwin I am getting this error

> FileSystemException: Creation of temporary directory failed, path = 'C:\Users\AlbertoMiola\Desktop\website\tmp' (OS Error: The system cannot find the path specified.
, errno = 3)

While I'm googling for a solution, I'm also trying to manually fix the examples to see if I can make the CI happy!

**Comment by khanhnwin** [comment]
Hey @albertodev01! Hmm you shouldn't have to create a new directory. I notice that you're on Windows based on the path `'C:\Users\AlbertoMiola\Desktop\website\tmp' (OS Error: The system cannot find the path specified.
, errno = 3)` My apologies, I've got exactly 0 experience running shell scripts on Windows. I wonder if there's a difference there that may be the problem?

**Comment by albertodev01** [comment]
So, I have created [this](https://github.com/flutter/codelabs/pull/279) PR in the `codelabs` repo.

What should I do next? 🙂  @domesticmouse @khanhnwin 

---

Do I need to run the `refresh-code-excerptssh` **after** you're merged the PR in `codelabs`?

**Comment by albertodev01** [comment]
I will give it a try but I have to admit that this is a bit complicated!

**Comment by sfshaza2** [comment]
@albertodev01, can you address the conflicts? Thanks for hanging in there!

**Pull request closed without merging**
