### PR TITLE
Correct spelling of Xcode in integration test instructions

### PR DESCRIPTION
**Pull request by jmagman**
Introduced in #5954.

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
LGTM. thanks for keeping us honest!

**Comment by jmagman** [comment]
> LGTM. thanks for keeping us honest!

I couldn't find how https://github.com/flutter/website/blob/master/.spelling is used or if it's used, but there doesn't seem to be a way in that kind of config file to make suggestions XCode->Xcode, it seems you can only add exceptions?

**Comment by johnpryan** [comment]
I think `.spelling` was added by accident in https://github.com/flutter/website/commit/2714d9f2e575ffd683b736744a0e1a5812c0abde - it doesn't look like any of our site infrastructure uses it

**Comment by johnpryan** [comment]
I filed an issue for the `spelling`. file: https://github.com/flutter/website/issues/6109

**Pull request merged**
