### PR TITLE
Remove the survey link on 07/22/2018

### PR DESCRIPTION
**Pull request by InMatrix**
The survey will close on 07/22/2018.

### CODE REVIEW

**Comment by InMatrix** [comment]
Please review but do not merge. I'll do it on Sunday evening. Thanks!

**Comment by Sfshaza** [comment]
LGTM, @InMatrix. However, the build failed because you need to log in to Firebase. They do this occasionally.  Here's the note from the build:

```
⚠  Your CLI authentication needs to be updated to take advantage of new features.
⚠  Please run firebase login --reauth
```
I restarted the build, so hopefully it will just work.

**Comment by Sfshaza** [comment]
I've kicked off the build twice and it's still not happy. Maybe it wants YOU, Tao, to re-authorize. There also seems to be a problem with the Dart 2 constraints, but that didn't kill the build.

**Comment by InMatrix** [comment]
I actually created this PR using the Github file editor, instead of from a local repo. I'm not sure running `firebase login` will make a difference here. Since this PR is very straight forward, can we ignore the build issue?

**Comment by Sfshaza** [comment]
Sure, that's another way to go. LOL.

**Pull request merged**
