### PR TITLE
[SwiftUI guide] Fix alignment for CupertinoApp widget

### PR DESCRIPTION
**Pull request by minikin**
- Fix alignment for the CupertinoApp widget

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by domesticmouse — COMMENTED** [review]
Given the `docregion` tag, I suspect this is sourced from somewhere else that will also need to be updated. 

FYI @khanhnwin

**Comment by minikin** [comment]
@domesticmouse there are a few more such alignment issues that need to be fixed. It's easy to spot them [here](https://docs.flutter.dev/get-started/flutter-for/ios-devs?tab=swiftui).

**Comment by khanhnwin** [comment]
thanks @minikin! I'm reviewing this now. 

Running it through dartformat gets it back into it's original state, which as you point out doesn't look right!

**Comment by sfshaza2** [comment]
@minikin, we are freezing the website by end of day today. As this PR won't pass the build, we can't land it. I will be closing it. After the website is reopened, you can re-open the PR, but the build must be fixed before we can land. Thx!

**Pull request closed without merging**
