### PR TITLE
[Material] Updating copy mentioning Material

### PR DESCRIPTION
**Pull request by willlarche**
Corrects capitalization and renames common name of material library to Material Components.

*Help me make sure the places where I changed code for the site are still correct. I believe they are.

### CODE REVIEW

**Comment by sethladd** [comment]
rslgtm

@HansMuller want to take a look?

**Comment by HansMuller** [comment]
...looking

**Comment by HansMuller** [comment]
I don't think it's a good idea to replace references to "iOS" with "Apple-flavor" just yet. There are hundreds of references to "iOS" in the Flutter repo, and we should be consistent.

**Comment by willlarche** [comment]
Do you want that done first? I don't mind doing that repo first.

**Comment by HansMuller** [comment]
It would be simpler to leave the half-dozen iOS-Apple changes out of this PR.

**Comment by willlarche** [comment]
PTAL

**Comment by HansMuller** [comment]
LGTM

**Pull request merged**
