### PR TITLE
replace IOWebSocketChannel with WebSocketChannel in Cookbook Example for WebSockets

### LINKED ISSUE #5813: 'Work with WebSockets' page issue
Page URL: https://flutter.dev/docs/cookbook/networking/web-sockets.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/web-sockets.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

For targeting web platform, `HtmlWebSocketChannel.connect` needs to be used, `IOWebSocketChannel.connect` won't work.

### PR DESCRIPTION
**Pull request by piedcipher**
Fixes #5813

### CODE REVIEW

**Comment by piedcipher** [comment]
why does it still shows "Starting workflow run"

**Comment by piedcipher** [comment]
Github-actions is having some issues. 

https://www.githubstatus.com/

**Comment by sfshaza2** [comment]
Yeah, @piedcipher, you can't just change the code in the markdown page. This page uses code excerpts, which has a more involved setup to analyze and verify code.

**Comment by piedcipher** [comment]
I might be wrong but workflow has not started yet because of the outage in Github Action.

**Comment by piedcipher** [comment]
https://twitter.com/githubstatus/status/1394574950401519616?s=20

**Comment by piedcipher** [comment]
Recent commits of the Master branch of flutter/website show a :yellow_circle: yellow circle.

https://github.com/flutter/website/commit/f7bc8d72d642d9035e66b7974d9eaa6e7bae28f7
https://github.com/flutter/website/commit/db9fe4e87cd5a06087304fa0d408469497fcc470
https://github.com/flutter/website/commit/9e3630e981e37c9821e4fe0d9e3298ab0bc9fb76

**Comment by tirth-stasis** [comment]
All green :green_circle: 

Let me know if `code excerpts` is wrong or anything that I'm missing here. Yesterday one of failure with GitHub-actions was from GitHub itself due to an outage.

**Comment by piedcipher** [comment]
All green :green_circle: 

Let me know if `code excerpts` is wrong or anything that I'm missing here. Yesterday one of failure with GitHub-actions was from GitHub itself due to an outage.

**Comment by sfshaza2** [comment]
Yes, @piedcipher, that GitHub outage was brutal, especially as it happened while I was trying to publish all kinds of new stuff on the website for the 2.2 release. At any rate, this PR seems good. The build is happy. I will land it. By the way, I am out next week, so not much (if anything) happens on the website until I return.  Thx!

**Pull request merged**
