### PR TITLE
Fix search icon cursor pointer

### LINKED ISSUE #9329: "Add Cursor Pointer for Search Icon on Website"
### Describe the problem

I noticed that the cursor pointer is missing when hovering over the search icon on our website. This issue makes it difficult for users to identify that the search icon is clickable

### Expected fix

To fix this problem, we should add the CSS class that makes elements appear as clickable links or buttons when users hover over them. This will provide visual feedback to users that the search icon is interactive.

### Additional context

This issue affects the user experience on our website, especially when users attempt to search for content. By adding the cursor pointer, we can enhance usability and guide users to engage with the search functionality more effectively.

### PR DESCRIPTION
**Pull request by priyanshuchaudhary53**
Fixes #9329

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by atsansone — CHANGES_REQUESTED** [review]
There's a tiny spot between the magnifying glass and the X logo where the old cursor appears. To see this for yourself, run `bundle exec jekyll s -l -B -P 4001` to see this at localhost:4001. I'm not sure how to fix it, but I hope you can once you stage it.

**Review by domesticmouse — APPROVED** [review]

**Comment by sfshaza2** [comment]
@parlough, any idea why this keeps failing? We've run "gcbrun" multiple times.

**Comment by sfshaza2** [comment]
Hi, @priyanshuchaudhary53! Thanks for this PR, but we are going to be doing more work on the website infrastructure and aren't finding this to be a big problem. I'm closing this, but thx.

**Pull request closed without merging**
