### PR TITLE
Revert "Drop empty page"

### PR DESCRIPTION
**Pull request by khanhnwin**
Reverts flutter/website#6648

### CODE REVIEW

**Comment by domesticmouse** [comment]
I'm curious why you are reverting?

**Review by domesticmouse — APPROVED** [review]

**Comment by khanhnwin** [comment]
Chatted with Shams about it - it looked like `ui/advanced` was linking to http://0.0.0.0:4002/development/ui/animations/#sidenav-3-1-7 when I had it in staging to review. Left a comment on the original PR for your, was that the intended behavior?

**Comment by domesticmouse** [comment]
@khanhnwin I was attempting to close out an issue where people were landing on an empty page. See https://github.com/flutter/website/issues/6565 for details

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Pull request merged**
