### PR TITLE
Fix IDs on widget catalog pages

### PR DESCRIPTION
**Pull request by parlough**
Since these are header elements, we should make sure their IDs can be properly used as a URI fragment by using the same slugify function as elsewhere on the site.

### CODE REVIEW

**Comment by sfshaza2** [comment]
OOOhhhh. 18 missing anchors!

**Review by sfshaza2 — APPROVED** [review]
lgtm, once the missing anchors are fixed...

**Comment by domesticmouse** [comment]
Looks like Sluggify is breaking the anchor targets. Do not want.

**Pull request merged**
