### PR TITLE
Add `/to/web-html-renderer-deprecation` redirect

### PR DESCRIPTION
**Pull request by kevmoo**
See also
https://github.com/flutter/flutter/issues/145954
https://github.com/flutter/flutter/issues/154878
https://github.com/flutter/flutter/issues/154879

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @ditman

**Review by parlough — COMMENTED** [review]
Is this to link to from tools and warning messages? If so, can this be made a `/to/` tooling redirect? That will also help differentiate it from the design doc at [/go/deprecate-html-renderer](https://flutter.dev/go/deprecate-html-renderer).

**Comment by kevmoo** [comment]
Oh! Okay!

@ditman – hold the phone!

**Review by parlough — APPROVED** [review]
Thanks :D

**Comment by ditman** [comment]
Updated https://github.com/flutter/engine/pull/55709 to match this!

**Pull request merged**
