### PR TITLE
Update universal links page

### LINKED ISSUE #10488: Update file format for apple-app-site-association in "Set up universal links for iOS" guide
### Steps to reproduce

The **proposed apple-app-site-association** 
[file is incorrect](https://docs.flutter.dev/cookbook/navigation/set-up-universal-links#apple-app-site-association) :

`{
  "applinks": {
      "apps": [],
      "details": [
      {
        "appID": "S8QB4VV633.com.example.deeplinkCookbook",
        "paths": ["*"]
      }
    ]
  }
}`

### Corrected association file

**Since iOS 14, additional features have been introduced. The correct file structure follows:**

`{
    "applinks": {
        "apps": [],
        "details": [
            {
                "appIDs": [
                    "S8QB4VV633.com.example.deeplinkCookbook"
                ],
                "paths": [
                    "*"
                ],
                "components": [
                    {"/": "/*"}
                ]
            }
        ]
    },
    "webcredentials": {
        "apps": [
            "S8QB4VV633.com.example.deeplinkCookbook"
        ]
    }
}`

### Expected results

App link offers redirection into the app.

### Actual results

No redirection is offered.

### Code sample

{
  "applinks": {
      "apps": [],
      "details": [
      {
        "appID": "S8QB4VV633.com.example.deeplinkCookbook",
        "paths": ["*"]
      }
    ]
  }
}

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
sudo swcutil dl -d <domain> --verbose
SWCErrorDomain 7 {
	Line: "275",
	Function: "-[SWCDownloader URLSession:dataTask:didReceiveResponse:completionHandler:]",
	NSDebugDescription: "SWCERR00401 Bad JSON content -- {"cause":"invalid character ':' after top-level value"}",
	NSUnderlyingError: "Error Domain=HTTP Code=404 "(null)" UserInfo={Line=275, Function=-[SWCDownloader URLSession:dataTask:didReceiveResponse:completionHandler:]}"
}
```

```console
sudo swcutil dl -d <domain with corrected file> --verbose
{
    applinks =     {
        apps =         (
        );
        details =         (
                        {
                appIDs =                 (
                    "team.app.id"
                );
                components =                 (
                                        {
                        "/" = "/*";
                    }
                );
                paths =                 (
                    "*"
                );
            }
        );
    };
    webcredentials =     {
        apps =         (
            "team.app.id"
        );
    };
}
```

</details>

### Flutter Doctor output

Not needed.

### PR DESCRIPTION
**Pull request by atsansone**
Fixes #10488

### CODE REVIEW

**Comment by sfshaza2** [comment]
@johnpryan, can you review?

**Review by johnpryan — APPROVED** [review]

**Comment by sfshaza2** [comment]
I've asked @johnpryan to review this. He said he can get to it by EOD today.

**Comment by sfshaza2** [comment]
Thanks, @johnpryan!

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Pull request merged**
