### PR TITLE
Adds optimizations to Docker Build

### PR DESCRIPTION
**Pull request by btobin**
Followup resolutions from merged infra [PR](https://github.com/flutter/website/pull/7580) comments, plus additional optimizations:

- Removes `firebase-tools` and `superstatic` package.json installs. Neither are required any longer, and installing them slows down docker builds. Updates outdated comment in link check config. Updates package-lock.json after local setup.
- Removes comments about host user because they were confusing, and it’s not really important for this usage. 
- Updates naming of `FLUTTER_BUILD_BRANCH` env var for clarity
- Removes comment referencing —null-safety flag
- Removes unnecessary docker compose Firebase env vars
- Removes comments regarding TODO future usage of SHA installs for Flutter/Node as this would increase maintenance cost of the Dockerfile. If we still feel it’s worth documenting, we can file a separate issue for clarity on that potential future upgrade, similar to [what’s being done in the Dart website](https://github.com/dart-lang/site-www/blob/main/Dockerfile#L33)

@khanhnwin @johnpryan I'll add a reference to the appropriate comment(s) in the above PR. 

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by sfshaza2** [comment]
@khanhnwin, can you review?

**Comment by ditman** [comment]
@btobin it seems that the node+firebase-tools combo installed by the Dockerfile has started blowing up? I've just noticed a couple of PRs broken because of it:

https://github.com/flutter/website/issues/7741

**Review by khanhnwin — APPROVED** [review]

**Comment by khanhnwin** [comment]
Thanks Brian! LGTM.

@domesticmouse @sfshaza2 let's wait for #7742 to land before we merge this one?

**Comment by domesticmouse** [comment]
Sgtm!

**Comment by khanhnwin** [comment]
@btobin John was able to put in the fix with #7742!

**Comment by btobin** [comment]
@khanhnwin Okay, awesome - that works as well. Great to check it regardless, and more stable to lock it. I think in this case that the problem really was that we are upgrading npm to the latest version, and it clashed because of the recent LTS bump to 18. 

I'll remove that and also update the build.yml file so it's consistent with those new versions, then submit another PR. 

Thanks!

**Pull request merged**
