### PR TITLE
Added screen reader accessibility improvements to home page

### PR DESCRIPTION
**Pull request by tBoccinfuso**

### CODE REVIEW

**Comment by tBoccinfuso** [comment]
I have signed the CLA.

**Comment by sfshaza2** [comment]
Thanks for this PR, @tBoccinfuso!  I'd like to accept it but there is a conflict. We have two options: you fix the PR or I can create a new PR and apply your fixes, then close this one. Which do you prefer?

**Comment by tBoccinfuso** [comment]
@chalin Reason for closing? If I put something that was wrong I would love to know for future reference.

**Comment by chalin** [comment]
I was scratching my head for this, because I really don't recall closing this PR. I think that GitHub closed it because I deleted the `dash` branch over which you created this PR. (The `dash` branch was merged into `master` yesterday, and then was deleted to avoid folks creating PRs over a deprecated branch). Sorry for the confusion. Feel free to reopen over master.

**Comment by sfshaza2** [comment]
I also wondered about that, @chalin. Of course, we are now back to using master, rather than dash. @chalin, did you hear from the accessibility folk on these edits?

**Comment by chalin** [comment]
@c-machado, @fertolg - can you comment on this PR?

(@tBoccinfuso - if/once we get the thumbs up, might you be willing to create a new PR over master? I can't reopen this one because it is over the deleted `dash` branch.)

**Pull request closed without merging**
