### PR TITLE
Using Country / Region.

### PR DESCRIPTION
**Pull request by chenglu**
Hi team:

Here we should use "Country / Region" ;-)

cc/ @InMatrix @sfshaza2 

Thanks!

### CODE REVIEW

**Comment by InMatrix** [comment]
I support this change. The wording "Country/Region" is consistent with internal guidelines.

**Comment by InMatrix** [comment]
Cc: @jaydchang

**Comment by jaydchang** [comment]
@InMatrix I agree as well the label should be Country / Region

**Review by sfshaza2 — APPROVED** [review]
Hiiiiii, Luke!!!!!!!!!!  LGTM!

**Pull request merged**
