### PR TITLE
Signal that it's OK to create this file if it doesn't exist

### PR DESCRIPTION
**Pull request by sethladd**
Ideally, we would automate these steps somehow. Until we have a more automated process, we can reassure our new users that it's OK to create this file if it doesn't exist.

This is a temp fix, an installer script/app would make for a better long-term fix.

### CODE REVIEW

**Comment by sethladd** [comment]
Closes https://github.com/flutter/flutter/issues/8770

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by mit-mit** [comment]
LGTM

**Comment by sethladd** [comment]
One build succeeded, the other timed out linkchecking.

**Pull request merged**
