### PR TITLE
Drop empty page

### PR DESCRIPTION
**Pull request by domesticmouse**
_Description of what this PR is changing or adding, and why:_ Empty Advanced UI renders as empty page. Deleting the page should, in theory, fix the issue. I think.

_Issues fixed by this PR (if any):_ https://github.com/flutter/website/issues/6565

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by domesticmouse** [comment]
> The build is failing because the linkchecker fails on development/ui/advanced now. If we remove those references, that should resolve our issue?

I'm guessing the TOC still thinks `ui/advanced` is a valid page, because looking at `tos/index.md` the body text doesn't reference `ui/advanced` at all.

**Comment by domesticmouse** [comment]
PTAL @khanhnwin

**Comment by khanhnwin** [comment]
Hmm I just tried to stage the site locally and now "Advanced UI" is a link to: `http://0.0.0.0:4002/development/ui/animations/#sidenav-3-1-7` I don't think that's what we're trying to go for, is it?

**Review by sfshaza2 — APPROVED** [review]
/development/ui is pretty empty, too.

lgtm

**Pull request merged**
