### PR TITLE
Fix broken url in plugin-api-migration.md

### PR DESCRIPTION
**Pull request by saintmalik**
## Summary 

Easy navigation and easy reading for others

### CODE REVIEW

**Review by sfshaza2 — COMMENTED** [review]
Hi, @saintmalik. This is not correct syntax for links. The actual link is defined at the end of the file.

```
[Flutter plugin]: {{site.pub}}/flutter.dev/packages
```

And the second bracket should remain empty. Also, the link currently goes to the Flutter packages on pub.dev, rather than ALL packages on pub.dev.

**Comment by saintmalik** [comment]
> Hi, @saintmalik. This is not correct syntax for links. The actual link is defined at the end of the file.
> 
> ```
> [Flutter plugin]: {{site.pub}}/flutter.dev/packages
> ```
> 
> And the second bracket should remain empty. Also, the link currently goes to the Flutter packages on pub.dev, rather than ALL packages on pub.dev.

Sorry looks like I made a mistake, I will commit the correct changes now, but the link actually leads to a 404 and it doesn't point to  the Flutter packages on pub.dev,

**Comment by saintmalik** [comment]
> Hi, @saintmalik. This is not correct syntax for links. The actual link is defined at the end of the file.
> 
> ```
> [Flutter plugin]: {{site.pub}}/flutter.dev/packages
> ```
> 
> And the second bracket should remain empty. Also, the link currently goes to the Flutter packages on pub.dev, rather than ALL packages on pub.dev.

I have fixed it, before the link does to https://pub.dev/flutter.dev/packages but now it should be going to https://pub.dev/flutter/packages, I removed the ".dev"

**Review by kwalrath — APPROVED** [review]

**Comment by saintmalik** [comment]
@sfshaza2 can you review please

**Pull request merged**
