### PR TITLE
Rename material.md to material-design.md

### PR DESCRIPTION
**Pull request by jasimameen**
Renamed "Material" to "Material Design" in the left navigation

Fixes:  #8297 

## Presubmit checklist
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).

### CODE REVIEW

**Comment by khanhnwin** [comment]
Thanks @jasimameen! I'm wondering if it would be sufficient to change just the item title in the [sidenav](https://github.com/flutter/website/blob/fbf0b813fbb256f309b5e8abda810e1500c0fd24/src/_data/sidenav.yml#L80) instead of renaming the entire file? WDYT @sfshaza2?

**Comment by sfshaza2** [comment]
Yes, there's no need to move the file. Just change the name of the page in the src/_data/sidenav file and the title in the target page.

**Comment by jasimameen** [comment]
thanks for pointing it out. I have updated both.

**Review by sfshaza2 — APPROVED** [review]
lgtm!

**Pull request merged**
