### PR TITLE
Fix typo in jobs/ecosystem.html

### PR DESCRIPTION
**Pull request by st-den**

### CODE REVIEW

**Comment by st-den** [comment]
@googlebot I signed it!

**Review by sfshaza2 — COMMENTED** [review]
Thanks for the PR, @st-den! But the original text is not incorrect. Closing.

**Comment by st-den** [comment]
Oh, I'm sorry then 😅 Haven't seen such a phrase before somehow, TIL!

**Comment by sfshaza2** [comment]
:)

**Pull request closed without merging**
