### PR TITLE
Eliminate `CRLF` from the copied `flutter` directory for Docker build

### PR DESCRIPTION
**Pull request by AlexV525**
Force eliminate `CRLF` from the copied `flutter` directory.

_Issues fixed (partially) by this PR (if any)_:
- https://github.com/flutter/website/issues/6443#issuecomment-971186295
- https://github.com/flutter/website/issues/8272#issuecomment-1432645530

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by atsansone** [comment]
@AlexV525 : I like this change. Did it work on your machine?

**Comment by parlough** [comment]
I haven't had access to a Windows setup for a while, but I'll work on getting something set up this weekend.

Thanks for staying on top of this Alex! Would you mind adding a comment to explain the line? I think it might be easy to forget why it's there in the future.

**Comment by AlexV525** [comment]
> Would you mind adding a comment to explain the line? I think it might be easy to forget why it's there in the future.

Oh, I just place the command as an ENV: `REPLACE_CRLF`, is it self-explaining enough?

**Comment by AlexV525** [comment]
Nah, it not actually working since my clone is already in `LF`.

**Comment by AlexV525** [comment]
Thanks for the ChatGPT, the command is now working.

**Comment by AlexV525** [comment]
Notice that this only resolves a single part of the whole setup process.

**Comment by AlexV525** [comment]
Alternatively, we can always clone the flutter repo rather than copying.

**Comment by AlexV525** [comment]
> Alternatively, we can always clone the flutter repo rather than copying.

I'd perfer this after some experiments. Will submit a separate PR for it. And you guys can decide which to take.

**Comment by AlexV525** [comment]
See #9307

**Comment by AlexV525** [comment]
Closing in favor of #9307.

**Pull request closed without merging**
