### PR TITLE
Flutter logo on Github Dark Mode is affected

### PR DESCRIPTION
**Pull request by mkiisoft**
## Description:

- With the latest update over Github, flutter-lockup.png logo gets affected by Dark Mode

## Screenshot:

Logo Dark Mode

## Solutions:

Added a white background/jpg file to fix the issue

flutter-lockup-bg

## Notes:

flutter/flutter uses flutter-lockup.png file from flutter/website, a PR over flutter/flutter will be required to update and fix the issue.

## Discussion:

Github Community: https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981

### CODE REVIEW

**Comment by mkiisoft** [comment]
@googlebot I signed it!

**Comment by jamesblasco** [comment]
It would be interesting to also keep an eye on this issue
https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981
So in the future we could use a more appropriate image for dark mode

**Comment by mkiisoft** [comment]
@jamesblasco Yes, I tried to see if there's something like that. Thanks for that link! Will keep following for reference/update as is a way better solution.

**Comment by YazeedAlKhalaf** [comment]
I believe it would look better if you round the corners of the image like this:
flutter_logo_rounded_corners

**Review by sfshaza2 — APPROVED** [review]
Thanks for this PR! LGTM

**Comment by mkiisoft** [comment]
Thanks @sfshaza2 we also need https://github.com/flutter/flutter/pull/72016 to be merged in order to fix the Dark Mode issue. (we need a CI test to be retest)

**Pull request merged**
