### PR TITLE
Move "Automatic platform adaptations" page to Adaptive design section in Left Nav

### PR DESCRIPTION
**Pull request by droidbg**
_Issues fixed by this PR :_ #11442 
This PR moves the `Automatic platform adaptations` page to section `Adaptive & responsive design` in nav bar and closes the above issue. 

## Presubmit checklist

- [X] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [X] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [X] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
Thanks, @droidbg! Though we also need to set up a redirect. I'll do that in a new PR.

**Comment by droidbg** [comment]
Hi @sfshaza2, I have now added the redirect. Could you pls review this PR again.

**Review by sfshaza2 — APPROVED** [review]
lgtm.  Thanks, @droidbg!

**Pull request merged**
