### PR TITLE
chore: Removed old book version and added new one

### PR DESCRIPTION
**Pull request by albertodev01**
_Description of what this PR is changing or adding, and why:_ I have published a new version of my book and deprecated the old one

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by parlough — CHANGES_REQUESTED** [review]
Cool! Thanks for updating this and for the hard work on the new book. A few things:

1. The Amazon link doesn't seem to be working. Is it perhaps the wrong link or is it just not posted yet?
2. Can you move it back to the old location? We try to keep this list in alphabetical order.

**Comment by albertodev01** [comment]
Thank you for your feedback @parlough

**Review by parlough — APPROVED** [review]
Thanks for updating this! I'm excited for readers to get hands on your new book.

**Review by parlough — APPROVED** [review]
Thanks for updating this! I'm excited for readers to get their hands on your new book.

**Pull request merged**
