### PR TITLE
Pin dependencies by hash.

### PR DESCRIPTION
**Pull request by godofredoc**
Turns out that pinning by version is still considered a bad practice.
Updating npm pins to use hash.

## Presubmit checklist
- [X] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [X] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [X] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by sfshaza2** [comment]
@godofredoc, when the build failed on this PR last week, I re-ran the scripts. It still seems to be broken. Can you take a look?

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Comment by godofredoc** [comment]
> lgtm
Sorry for my late reply. Pinning Node dependencies is more challenging than expected. I'll probably land only some of them at a time.

**Comment by godofredoc** [comment]
Abandoning this PR until we get some guidance from the scorecards team: https://github.com/ossf/scorecard/issues/1754

**Pull request closed without merging**
