### PR TITLE
Update links

### PR DESCRIPTION
**Pull request by AmosHuKe**
_Description of what this PR is changing or adding, and why:_ 

Update links based on `_config.yml`

_Issues fixed by this PR (if any):_ none

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by AlexV525** [comment]
Long time ago I was thinking if we can add checks to make sure we can reuse the variable for link definition as much as possible, instead of absolute links. Does it sound valid?

**Review by sfshaza2 — APPROVED** [review]
Yowza, @AmosHuKe. lgtm

**Review by parlough — APPROVED** [review]
Thanks for this!

**Pull request merged**
