### PR TITLE
Update simple.md

### PR DESCRIPTION
**Pull request by ebukaodini**
Fixing this issue 'Simple app state management' page issue #5858
Description of issue: Please update the provider: ^4.3.3 to provider: ^5.0.0. I had Null-safety dependency issue using the former.

### CODE REVIEW

**Comment by ebukaodini** [comment]
> @googlebot I signed it!

**Comment by filiph** [comment]
Hi @ebukaodini, thanks for the change!

We need to make sure that all the code is migrated, too. All code excerpts on flutter.dev is checked in CI. The code shown in the state management section is found here: https://github.com/flutter/website/blob/master/examples/state_mgmt/simple/. Are you able to update all that? If not, no problem, I can do that myself, but it might take some time.

More about the testing of code excerpts: https://github.com/dart-lang/site-shared/blob/master/doc/code-excerpts.md.

**Review by sfshaza2 — CHANGES_REQUESTED** [review]
Filip requested some changes.

**Comment by sfshaza2** [comment]
The [pubspec](https://github.com/flutter/website/blob/master/examples/state_mgmt/simple/pubspec.yaml) for the example is already updated. LGTM

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Pull request merged**
