### PR TITLE
Adding binder to state management options

### PR DESCRIPTION
**Pull request by letsar**
Changes proposed in this pull request:

*  Adding binder in state management options page

### CODE REVIEW

**Review by sfshaza2 — COMMENTED** [review]
Can you take a look, @filiph?

**Comment by sfshaza2** [comment]
@letsar, this will have to sit a bit because @filip is OOO for awhile.

**Comment by letsar** [comment]
No problem, I hope he's ok.

**Review by filiph — APPROVED** [review]
LGTM, thanks! (And sorry for the delay!)

**Pull request merged**
