### PR TITLE
Remove links to old “First app” codelab

### PR DESCRIPTION
**Pull request by filiph**
A pass through flutter/website to weed out links to the old "First Flutter app" codelab (part 1 and 2).

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
lgtm!

**Review by parlough — APPROVED** [review]

**Review by domesticmouse — APPROVED** [review]

**Comment by parlough** [comment]
@filiph Did you intend to close instead of merge this?

**Comment by filiph** [comment]
Gah! I though it's been merged and deleted my branch! Thanks for catching this.

**Comment by parlough** [comment]
Thanks :)

**Pull request merged**
