### PR TITLE
Add /go/publish-on-homebrew

### PR DESCRIPTION
**Pull request by Hari-07**
Add "/go/publish-to-homebrew"

_Description of what this PR is changing or adding, and why:_

_Issues fixed by this PR (if any):_

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Comment by atsansone** [comment]
@Hari-07 : Before we can merge this, we had a question. Is the linked doc a design doc (a proposed change) or a tutorial (here's how to package Flutter in Homebrew)? If it's the former, great! You may want to clarify the writing toward that end. If it's the latter, we may ask to change the doc to a design doc so we can get feedback from the community on that proposal.

**Comment by Hari-07** [comment]
It's a design doc, I was told in hackers-release channel on discord to write a design doc when I mentioned this work, I've linked it there too

**Review by sfshaza2 — APPROVED** [review]
I've scanned the proposed doc and it's definitely not a tutorial. I'm ok with it, as is. @atsansone, we generally don't vet the content of design docs, that's left for the Flutter community. We primarily make sure that they'll open in an incognito window (without requiring a Google login), and that they don't break the build.  I'm lgtm for this.

**Pull request merged**
