### PR TITLE
Update firebase.json for a new doc.

### PR DESCRIPTION
**Pull request by zanderso**
Points flutter.dev/go/opengl-on-ios at https://docs.google.com/document/d/1kvrb6HeTRN4noAKO82o6x-Ii61PW-BQ-8s9YNtLgosM

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Comment by zanderso** [comment]
@sfshaza2 How can I find out why the checks failed?

**Comment by zanderso** [comment]
Ah, it was an internal GitHub actions error. I pushed another commit, and the re-run succeeded.

**Comment by sfshaza2** [comment]
Yeah, GitHub actions can be flaky.

**Pull request merged**
