### PR TITLE
Update platforms.yml to reflect 3.22 android api support updates

### PR DESCRIPTION
**Pull request by reidbaker**
Documented here but the website it wrong. 
https://docs.flutter.dev/release/breaking-changes/android-kitkat-deprecation 

The primary driver of this deprecration was that the NDK needed to be updated to a version that didn't support those older api levels.

## Presubmit checklist

- [x] This PR is marked as draft with an explanation if not meant to land until a future stable release.
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by gmackall — APPROVED** [review]
LGTM (I've double checked we are indeed using NDK 26 which [doesn't support 19/20](https://developer.android.com/ndk/downloads/revision_history))

**Comment by reidbaker** [comment]
https://flutter-docs-prod--pr10908-2024-07-16-support-andorid-njq9r2bb.web.app/reference/supported-platforms

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Comment by sfshaza2** [comment]
@parlough, the build is breaking, can you look into it?

**Review by zanderso — APPROVED** [review]

**Review by atsansone — APPROVED** [review]

**Review by parlough — APPROVED** [review]

**Pull request merged**
