### PR TITLE
change to JPG for master screenshot of lakes, saving lots of space

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by sethladd** [comment]
I don't know how to update this PR with my work email. I did set my global email on my machine, I expect the next PR I push will have the correct email. If someone knows how to retroactively set the email for a commit.

**Comment by sethladd** [comment]
For those following along, this is what I did: `git commit --amend --author="Seth Ladd <sethladd@google.com>"`

**Comment by sethladd** [comment]
Closes https://github.com/flutter/flutter/issues/8655

**Comment by mit-mit** [comment]
Looks like there is a broken link:

```
- _site/tutorials/interactive/index.html
  *  internal image images/lakes.jpg does not exist (line 460)
htmlproofer 3.4.0 | Error:  HTML-Proofer found 1 failure!
```

**Comment by sethladd** [comment]
Thanks, I was indeed missing an image.

Yay for link checking!!!

**Comment by mit-mit** [comment]
LGTM!

**Comment by sethladd** [comment]
Thanks!

**Pull request merged**
