### PR TITLE
Update to RP2

### PR DESCRIPTION
**Pull request by Hixie**
TBR=@timsneath

### CODE REVIEW

**Comment by Hixie** [comment]
cc @chalin do I have to do anything special to make this deploy?

**Comment by mit-mit** [comment]
@Hixie thanks for doing this while I was sleeping!

**Comment by mit-mit** [comment]
Change LGTM

**Comment by chalin** [comment]
> @chalin do I have to do anything special to make this deploy?

Travis autodeploys after every successful build, so it is live now.

**Pull request merged**
