### PR TITLE
docs: update incomplete code example step 4

### PR DESCRIPTION
**Pull request by Zerotask**
_Description of what this PR is changing or adding, and why:_
The code example now shows a complete example of using the ListView.builder().

_Issues fixed by this PR (if any):_ #7253

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by parlough** [comment]
Thanks for the pull request, nice catch! We'll need to update the code fragment where this excerpt comes from to include the closing parenthesis and semicolon. I made a pull request here: https://github.com/flutter/codelabs/pull/957

Once that is merged we can update the codelabs submodule and refresh these excerpts.

**Comment by parlough** [comment]
Now that https://github.com/flutter/codelabs/pull/957 is merged, the codelabs submodule can be updated the and the [code excerpts refreshed](https://github.com/flutter/website#refreshing-code-excerpts). If you need help or would like me to do it instead, let me know. Thanks!

**Comment by Zerotask** [comment]
@parlough I updated the PR although cla/google is failing. I updated the branch with a different PC(with a different git user.email). I can't add this email address as an alternative for my private google account with which I signed the CLA.

**Comment by domesticmouse** [comment]
We can't land this PR without a CLA. Do you want to recreate this PR with your other account? 

This might be useful: https://stackoverflow.com/questions/44204514/how-to-change-the-author-of-a-commit-in-github

**Pull request closed without merging**
