### PR TITLE
Don't use system libffi for ffi gem

### PR DESCRIPTION
**Pull request by parlough**
Fixes ffi issue when running `make up`.

@atsansone Can you try this locally by pruning (`docker system prune -a`), then `make setup`, and then `make up` to verify it works for you?

### CODE REVIEW

**Comment by sfshaza2** [comment]
Have you staged this yourself, @parlough? If so, I'm happy to approve/land.

**Comment by parlough** [comment]
Just checking in @atsansone. Is serving with `make up` working for you without this change now?

**Comment by johnpryan** [comment]
I am seeing this error on my machine:

```
make up
docker-compose up site
[+] Running 1/0
 ⠿ Container website-site-1  Created                                       0.0s
Attaching to website-site-1
website-site-1  | bundle exec jekyll serve \
website-site-1  | 	--host 0.0.0.0 \
website-site-1  | 	--port 4002 \
website-site-1  | 	--config _config.yml,_config_dev.yml \
website-site-1  | 	--livereload \
website-site-1  | 	--livereload_port 37530 \
website-site-1  | 	--incremental \
website-site-1  | 	--trace
website-site-1  | Configuration file: /app/_config.yml
website-site-1  | Configuration file: /app/_config_dev.yml
website-site-1  |             Source: /app/src
website-site-1  |        Destination: /app/_site
website-site-1  |  Incremental build: enabled
website-site-1  |       Generating... 
website-site-1  |                     done in 15.335 seconds.
website-site-1  | bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
website-site-1  | <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': libffi.so.7: cannot open shared object file: No such file or directory - /usr/local/bundle/gems/ffi-1.15.5/lib/ffi_c.so (LoadError)
website-site-1  | 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
website-site-1  | 	from /usr/local/bundle/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <top (required)>'
website-site-1  | 	from /usr/local/bundle/gems/ffi-1.15.5/lib/ffi.rb:2:in `<top (required)>'
website-site-1  | 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
website-site-1  | 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
website-site-1  | 	from /usr/local/bundle/gems/rb-inotify-0.10.1/lib/rb-inotify/native.rb:1:in `<top (required)>'
website-site-1  | 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
website-site-1  | 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
website-site-1  | 	from /usr/local/bundle/gems/rb-inotify-0.10.1/lib/rb-inotify.rb:2:in `<top (required)>'
website-site-1  | 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
website-site-1  | 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/adapter/linux.rb:28:in `_configure'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/adapter/base.rb:47:in `block in configure'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/adapter/base.rb:42:in `each'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/adapter/base.rb:42:in `configure'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/adapter/base.rb:66:in `start'
website-site-1  | 	from /usr/local/lib/ruby/3.2.0/forwardable.rb:240:in `start'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/listener.rb:71:in `block in <class:Listener>'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/fsm.rb:124:in `instance_eval'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/fsm.rb:124:in `call'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/fsm.rb:105:in `transition_with_callbacks!'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/fsm.rb:72:in `transition'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/listener.rb:92:in `start'
website-site-1  | 	from /usr/local/bundle/gems/jekyll-watch-2.2.1/lib/jekyll/watcher.rb:26:in `watch'
website-site-1  | 	from /usr/local/bundle/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:77:in `watch'
website-site-1  | 	from /usr/local/bundle/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:43:in `process'
website-site-1  | 	from /usr/local/bundle/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
website-site-1  | 	from /usr/local/bundle/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
website-site-1  | 	from /usr/local/bundle/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
website-site-1  | 	from /usr/local/bundle/gems/jekyll-4.3.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
website-site-1  | 	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
website-site-1  | 	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
website-site-1  | 	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
website-site-1  | 	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
website-site-1  | 	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
website-site-1  | 	from /usr/local/bundle/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
website-site-1  | 	from /usr/local/bundle/bin/jekyll:25:in `load'
website-site-1  | 	from /usr/local/bundle/bin/jekyll:25:in `<top (required)>'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:58:in `load'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:58:in `kernel_load'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:23:in `run'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli.rb:492:in `exec'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli.rb:34:in `dispatch'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli.rb:28:in `start'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/exe/bundle:37:in `block in <top (required)>'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/exe/bundle:29:in `<top (required)>'
website-site-1  | 	from /usr/local/bundle/bin/bundle:25:in `load'
website-site-1  | 	from /usr/local/bundle/bin/bundle:25:in `<main>'
website-site-1  | <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- 3.2/ffi_c (LoadError)
website-site-1  | 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
website-site-1  | 	from /usr/local/bundle/gems/ffi-1.15.5/lib/ffi.rb:3:in `<top (required)>'
website-site-1  | 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
website-site-1  | 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
website-site-1  | 	from /usr/local/bundle/gems/rb-inotify-0.10.1/lib/rb-inotify/native.rb:1:in `<top (required)>'
website-site-1  | 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
website-site-1  | 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
website-site-1  | 	from /usr/local/bundle/gems/rb-inotify-0.10.1/lib/rb-inotify.rb:2:in `<top (required)>'
website-site-1  | 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
website-site-1  | 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/adapter/linux.rb:28:in `_configure'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/adapter/base.rb:47:in `block in configure'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/adapter/base.rb:42:in `each'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/adapter/base.rb:42:in `configure'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/adapter/base.rb:66:in `start'
website-site-1  | 	from /usr/local/lib/ruby/3.2.0/forwardable.rb:240:in `start'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/listener.rb:71:in `block in <class:Listener>'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/fsm.rb:124:in `instance_eval'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/fsm.rb:124:in `call'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/fsm.rb:105:in `transition_with_callbacks!'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/fsm.rb:72:in `transition'
website-site-1  | 	from /usr/local/bundle/gems/listen-3.8.0/lib/listen/listener.rb:92:in `start'
website-site-1  | 	from /usr/local/bundle/gems/jekyll-watch-2.2.1/lib/jekyll/watcher.rb:26:in `watch'
website-site-1  | 	from /usr/local/bundle/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:77:in `watch'
website-site-1  | 	from /usr/local/bundle/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:43:in `process'
website-site-1  | 	from /usr/local/bundle/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
website-site-1  | 	from /usr/local/bundle/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
website-site-1  | 	from /usr/local/bundle/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
website-site-1  | 	from /usr/local/bundle/gems/jekyll-4.3.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
website-site-1  | 	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
website-site-1  | 	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
website-site-1  | 	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
website-site-1  | 	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
website-site-1  | 	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
website-site-1  | 	from /usr/local/bundle/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
website-site-1  | 	from /usr/local/bundle/bin/jekyll:25:in `load'
website-site-1  | 	from /usr/local/bundle/bin/jekyll:25:in `<top (required)>'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:58:in `load'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:58:in `kernel_load'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:23:in `run'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli.rb:492:in `exec'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli.rb:34:in `dispatch'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli.rb:28:in `start'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/exe/bundle:37:in `block in <top (required)>'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.4.15/exe/bundle:29:in `<top (required)>'
website-site-1  | 	from /usr/local/bundle/bin/bundle:25:in `load'
website-site-1  | 	from /usr/local/bundle/bin/bundle:25:in `<main>'
website-site-1  | make: *** [Makefile:72: serve] Error 1
```

**Comment by parlough** [comment]
@johnpryan That's with this change or without? On arm64 or x64?

**Comment by johnpryan** [comment]
I am using this branch on arm64

**Comment by johnpryan** [comment]
I found [this page](https://gitlab.com/gitlab-org/gitlab-development-kit/-/merge_requests/3061) has some information, so I'm going to try adding `gem uninstall ffi` to see if that helps.

**Comment by johnpryan** [comment]
I'm still seeing an error, but I'm not sure why...

```
website-site-1  | bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
website-site-1  | <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': libcrypto.so.1.1: cannot open shared object file: No such file or directory - /usr/local/bundle/gems/eventmachine-1.2.7/lib/rubyeventmachine.so (LoadError)
```

**Comment by parlough** [comment]
It's been a challenge for me to debug, since I haven't had issues with or without any of these changes.

I just pushed an alternative solution that forces bundle to use its installed versions of gems. Hopefully that works so we can avoid having to uninstall a bunch of system gems.

**Comment by johnpryan** [comment]
I'm still seeing a `require': libcrypto.so.1.1: cannot open shared object file: No such file or directory` error, so I suspect the issue with`libffi` is fixed.

**Pull request closed without merging**
