### PR TITLE
s/alpha/dev/

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
cc @tvolkert @mit-mit @sethladd @mjohnsullivan

**Comment by Hixie** [comment]
We'll also have to update the codelabs.

**Comment by mit-mit** [comment]
There are a few more missing:
https://github.com/flutter/website/blob/master/_includes/header.html#L9
https://github.com/flutter/website/blob/master/setup.md
https://github.com/flutter/website/blob/master/index.md (x2)

**Comment by mit-mit** [comment]
@tvolkert ah, yes of course, they can wait until beta is ready

**Pull request merged**
