### PR TITLE
docs: Support for overriding endorsed plugin implementations

### PR DESCRIPTION
**Pull request by Gustl22**
DRAFT: It should may land only after the next major release, when functionality is available in stable.

_Description of what this PR is changing or adding, and why:_

It is now possible to override native or Dart endorsed plugin implementations. This should be reflected in the docs.

_Issues fixed by this PR (if any):_

flutter/flutter#80374, flutter/flutter#59657, flutter/flutter#137040
See also: https://github.com/flutter/flutter/issues/80374#issuecomment-1141565904

_PRs or commits this PR depends on (if any):_

https://github.com/flutter/flutter/commit/d55a5f96c117725c134099b78deb7af431a93902

## Presubmit checklist

- [x] This PR is marked as draft with an explanation if not meant to land until a future stable release.
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by sfshaza2** [comment]
@Gustl22, any reason we can't take this out of draft form and land it? (After a proper review, that is.)

**Comment by Gustl22** [comment]
@sfshaza2 in the issue description it says in the checklist: 
_This PR is marked as draft with an explanation if not meant to land until a future stable release._

And I wrote: _DRAFT: It should may land only after the next major release, when functionality is available in stable._

I don't know the process. But if this doc is merged and published before the actual feature is released in stable, it may confused some people as it's not available yet.

**Comment by sfshaza2** [comment]
Hi, @Gustl22! Yes, that is the general process. But we have multiple things pulling on us. For one, we don't really like stinky old PRs that sit and sit and sit. The next stable release is quite a ways off. So, sometimes, we add a note that something is coming in a particular release. And, yes, then we must later go clean that up.

I really do thank you for keeping our docs up to date!

**Comment by Gustl22** [comment]
> For one, we don't really like stinky old PRs that sit and sit and sit. 

I agree, but I also have to say that I waited more than a month for some reviews, so its not always the fault of the PR author, if a PR gets old and stinky (whereas for Flutter internal reviews in 90% it takes only a few days). And I often notice in stale PRs that the author then got other priorities, because the waiting period was so long.
I don't want to complain, but in some cases it's not that fun to contribute.

> Yes, that is the general process.

So do I need to take any action here (marking as ready)? If yes you may want to change the PR default description on how such cases should be handled in the future. In my opinion I just did, what was stated there.

**Comment by sfshaza2** [comment]
Hi, @Gustl22! My apologies. I was not (and do not) blame you! I really appreciate your efforts in keeping our docs up to date. I added the labels that I did in order to mark the PR as ready to merge for the next stable release. That way, I don't keep re-reviewing it to see what is needed.

I'm sorry that contributing to our docs is not fun. I would love to make it more fun, esp because, at the current moment, I am the only writer supporting both Dart and Flutter.  :)

thx!

**Comment by chunhtai** [comment]
update: the required feature has not reached stable yet

**Comment by sfshaza2** [comment]
I'm going to land this as the "quiet" launch for 3.27 happened yesterday.

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Comment by Gustl22** [comment]
Cool, thank you for your patience :)

**Pull request merged**
