### PR TITLE
Add linting to `examples/animation`

### PR DESCRIPTION
**Pull request by domesticmouse**
Enforcing lint checking on the sample code in `examples/animation`. @khanhnwin this is going to require patching all the snippets, can you add that into this PR?

This should fix https://github.com/flutter/website/issues/6575 when completed. =)

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by khanhnwin** [comment]
Sorry missed this one! Patching it now.

**Comment by domesticmouse** [comment]
Thanks @khanhnwin!

**Review by khanhnwin — APPROVED** [review]

**Comment by khanhnwin** [comment]
No problem :) Tests passed - LGTM. Good to land?

**Comment by domesticmouse** [comment]
Landed =)

**Pull request merged**
