### PR TITLE
minor bug

### PR DESCRIPTION
**Pull request by alvinkonda**

### CODE REVIEW

**Comment by filiph** [comment]
Hi @alvinkonda, thanks for catching this. To merge this, I'll need you to sign the CLA and reply here.

**Comment by alvinkonda** [comment]
I signet it!

**Comment by alvinkonda** [comment]
I signed it!

**Comment by alvinkonda** [comment]
Btw, only love for Flutter

**Comment by xster** [comment]
Thanks for your contribution

**Pull request merged**
