### PR TITLE
Added Flutter Launcher Icons to Adding a Launcher Icon

### PR DESCRIPTION
**Pull request by MarkOSullivan94**

### CODE REVIEW

**Comment by Sfshaza** [comment]
After talking with @Hixie, I'm going to take a slightly different approach. But not this week.  :)

**Comment by Hixie** [comment]
@Sfshaza So should we close this PR?

**Comment by MarkOSullivan94** [comment]
Okay @Sfshaza. Let me know if you need anything from me!

**Comment by Sfshaza** [comment]
@MarkOSullivan94, here's the thought. Rather than linking at the end, I can see linking up front, with something like:

To add launch icons to your app, you might want to check out the [launcher package](). But if you want to do it manually, here's how:

<and then describe the process>

Let me know what you think.

**Comment by MarkOSullivan94** [comment]
That sounds good to me!

**Comment by Sfshaza** [comment]
Mark, can you update the PR?  Thanks!

**Comment by MarkOSullivan94** [comment]
Will do! In work just now but will get round to this during my lunch / this evening.

**Comment by Sfshaza** [comment]
No rush! And thanks! It's 3am here, so I'm crazy.

**Comment by Sfshaza** [comment]
Excellent! LGTM

**Comment by Sfshaza** [comment]
Thanks, @MarkOSullivan94!

**Pull request merged**
