### PR TITLE
Suggested name convention for "short-title" property.

### PR DESCRIPTION
**Pull request by theyashjani**
_Description of what this PR is changing or adding, and why:_

_Issues fixed by this PR (if any):_

## Presubmit checklist
- [ ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ ] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by domesticmouse** [comment]
This is as intended. It's the short title, after all.

**Comment by theyashjani** [comment]
@domesticmouse i agree with short-title but it is too short, user should know he is in which page...

**Comment by domesticmouse** [comment]
PTAL @sfshaza2 

Also @theyashjani you'll need to sign the CLA

**Comment by theyashjani** [comment]
@domesticmouse and "a11y & i18n" is not justifying its working, the name should be instead Accessibility & Internationalization rather alphanumeric.

**Comment by theyashjani** [comment]
@sfshaza2 please review!

**Comment by domesticmouse** [comment]
@theyashjani You still have yet to sign the CLA. Without it this PR will not land.

**Comment by theyashjani** [comment]
unable to sign CLA due to the issue mentioned below 
The following contributors were found for this pull request:

✅ https://github.com/flutter/website/commit/62eb2a6c957513a8f1c65879415f14d3a32986c4 Author: @theyashjani <54172910+theyashjani​@users.noreply.github.com>, <proc*******or4​@gmail.com>
❌ https://github.com/flutter/website/commit/7238be6da521219ce37a7f955811902a1c3922c9 Author: <yash.*********crew​@gmail.com>

(Only the first commit for a unique contributor is listed.)

**Comment by theyashjani** [comment]
@domesticmouse should i close this request and make a fresh Pull Request?

**Comment by domesticmouse** [comment]
> @domesticmouse should i close this request and make a fresh Pull Request?

Yup

**Pull request closed without merging**
