### PR TITLE
Update firebase.json

### PR DESCRIPTION
**Pull request by Calamity210**

### CODE REVIEW

**Review by sfshaza2 — CHANGES_REQUESTED** [review]
This mostly looks good except the Doc must be shared publicly and I had to request access. When it's open to anyone, let me know and I can land this PR.

**Comment by sfshaza2** [comment]
Thanks for making it public! LGTM

**Comment by Calamity210** [comment]
I actually had only allowed your request, I've updated it to allow anyone with the link to be a commenter @sfshaza2

**Comment by mono0926** [comment]
I cannot access https://docs.google.com/document/d/12Jet1gW2B_QFxig5B4K7f_lrpGhkbjR3LYpsKd4ZtJs/edit?usp=sharing

**Comment by Calamity210** [comment]
> I cannot access to https://docs.google.com/document/d/12Jet1gW2B_QFxig5B4K7f_lrpGhkbjR3LYpsKd4ZtJs/edit?usp=sharing

Thats weird, can you try [this link](https://docs.google.com/document/d/12Jet1gW2B_QFxig5B4K7f_lrpGhkbjR3LYpsKd4ZtJs/edit?usp=sharing&resourcekey=0-CfFoZ-0oqWPtz2WH0Jj0aw)

**Comment by mono0926** [comment]
@Calamity210 

Thanks, succeeded to access to 
https://docs.google.com/document/d/12Jet1gW2B_QFxig5B4K7f_lrpGhkbjR3LYpsKd4ZtJs/edit?resourcekey=0-CfFoZ-0oqWPtz2WH0Jj0aw

**Comment by Calamity210** [comment]
Sounds good, ill update the link in the commit in a bit.

**Pull request merged**
