### PR TITLE
Add a /go/ondirtycallbacks RFC.

### PR DESCRIPTION
**Pull request by jwise**
Per the RFC procedure, I've added a /go/ link to refer to my OnLayoutCallback / OnPaintCallback RFC.

### CODE REVIEW

**Review by sfshaza2 — COMMENTED** [review]
@jwise, this PR looks fine, but can you sign the CLA?

**Comment by jwise** [comment]
@googlebot I signed it!

**Comment by jwise** [comment]
Ok, I signed an individual CLA, too, and transferred copyright of this change from Accelerated Tech to myself personally (to the extent that this is eligible for copyright, anyway...).

@googlebot I signed it!

**Comment by jwise** [comment]
@sfshaza2 Looks like we should be good to go this time.

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Pull request merged**
