### PR TITLE
Enable DartPad on flutter.dev for Safari users

### PR DESCRIPTION
**Pull request by legalcodes**
Staged: https://jt-flutter-website-5.firebaseapp.com/

Note: seeing a left-border issue, and still seeing the DartPad Safari warning:

Screen Shot 2020-03-25 at 8 54 35 PM

### CODE REVIEW

**Comment by sfshaza2** [comment]
@johnpryan  approved.

**Comment by johnpryan** [comment]
By the way, we deployed the latest version of DartPad yesterday (with the safari warning removed)

**Comment by sfshaza2** [comment]
Great!!

**Comment by sfshaza2** [comment]
Ping, @legalcodes. Can we merge?

**Comment by legalcodes** [comment]
I think we shouldn't merge until we resolve the left-border issue. I haven't debugged yet, but here's what I'm seeing (in Safari only):

Screen Shot 2020-04-02 at 9 30 37 AM

**Comment by johnpryan** [comment]
For what it's worth, I'm not seeing a left border issue in Safari

Screen Shot 2020-04-02 at 10 13 15 AM

**Comment by legalcodes** [comment]
OK, thanks for checking! I'm consistently still seeing this issue, but I'd like to merge this, then revisit this if other users bring it up. Does that sound good?

**Comment by johnpryan** [comment]
SGTM

**Pull request merged**
