### PR TITLE
Update ci_post_clone.sh for new xcloud_cloud variable

### PR DESCRIPTION
**Pull request by esodot**
Update deprecated ENV variable

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by parlough** [comment]
Thanks for the PR!

Do you have a link to relevant Xcode docs for this change? Or when the new replacement was introduced?

**Comment by esodot** [comment]
the var documentation (no CI_WORKSPACE anymore)
https://developer.apple.com/documentation/xcode/environment-variable-reference

The xcode clode run pipeline already warns that the CI_WORKSPACE env is deprecated.

**Comment by domesticmouse** [comment]
I'm starting to wonder if we should push documenting using Xcode cloud out of our docs, as I don't know anyone on the team who actively uses this, and thus we aren't in a good position to verify if it works or not. 

/cc @RedBrogdon should we invest time and money in confirming Flutter builds in Xcode's cloud build?

**Review by domesticmouse — APPROVED** [review]
LGTM for this change, modulo @RedBrogdon's choices around verifying Xcode cloud.

**Review by parlough — APPROVED** [review]
Thank you!

I pushed a commit updating the excerpt verified against this file as well.

**Pull request merged**
