### PR TITLE
Add a design doc link for doc on AGP, KGP, Java, and Gradle version support

### PR DESCRIPTION
**Pull request by gmackall**
Adds a link to https://docs.google.com/document/d/1qeeM5QG-jiafttSgvc7yvC19IDRggFFZQTktBVxL6sI/edit?resourcekey=0-HLEAiBOMxAlQxDs-mEeffw.

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by parlough — APPROVED** [review]
Thank you for the design doc and adding the go link!

Is there an issue tracking this discussion/work on flutter/flutter yet? If so, please add a link to the doc as I couldn't find one. Thanks :)

**Comment by gmackall** [comment]
> Thank you for the design doc and adding the go link!
> 
> Is there an issue tracking this discussion/work on flutter/flutter yet? If so, please add a link to the doc as I couldn't find one. Thanks :)

Just filed https://github.com/flutter/flutter/issues/140913! Wanted to make sure I could land the link at the same time so the link in the issue was real

**Review by domesticmouse — APPROVED** [review]

**Comment by gmackall** [comment]
Also is there an autosubmit label or similar for this repo? Or should I just land once the tests finish?

**Comment by parlough** [comment]
Thanks for the issue @gmackall!

We don't have the autosubmit bot configured for this repo yet. Feel free to merge once tests pass and things look good, or we will make sure it gets merged :)

**Pull request merged**
