### PR TITLE
Refresh code excerpts

### PR DESCRIPTION
**Pull request by chalin**
(While testing the new versions of the code-excerpt tools, which should work the same under macOS and Linux.)

### CODE REVIEW

**Comment by chalin** [comment]
While this PR does cleanup all of the code-refresh errors, the one OS-specific code diff difference remains (sigh). I'll have to dig further to try to resolve this, but it might be a while before I have the time. @legalcodes do you want to merge this PR anyways (since it eliminates all of the errors by disabling code-excerpt instructions that have invalid file paths)?

**Comment by legalcodes** [comment]
Makes sense @chalin, this is super helpful. Thank you! 👍

**Comment by xster** [comment]
I think this PR removed all the header boxes for the code snippets that used to show the files that the snippet took place in. Was that intended?

**Comment by xster** [comment]
e.g.

before:
Screen Shot 2020-04-08 at 6 14 50 PM

after:
Screen Shot 2020-04-08 at 6 14 55 PM

**Comment by sfshaza2** [comment]
Ack! @xster, @legalcodes and @chalin no longer work on/with our team. Can you help with this? Or delegate to some front-end sort of eng?

**Comment by aadarshadhakalg** [comment]
> Ack! @xster, @legalcodes and @chalin no longer work on/with our team. Can you help with this? Or delegate to some front-end sort of eng?

Well, hope its done with this  #5026 pull request

**Pull request merged**
