### PR TITLE
Redirect style guide to Flutter wiki

### PR DESCRIPTION
**Pull request by abarth**
The wiki is the canonical copy of the style guide.

Fixes https://github.com/flutter/flutter/issues/5826

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie @sethladd

**Comment by sethladd** [comment]
Thanks! Can I suggest we use the firebase rules?

https://github.com/flutter/website/blob/master/firebase.json#L10

**Comment by abarth** [comment]
Sure!

**Comment by abarth** [comment]
Done.  PTAL.

**Comment by sethladd** [comment]
lgtm

thanks!

**Pull request merged**
