### PR TITLE
updating provider package version number

### PR DESCRIPTION
**Pull request by siddhant-dev**
n/a

### CODE REVIEW

**Comment by siddhant-dev** [comment]
@googlebot I signed it

Thanks & Regards,
Siddhant Jaiswal

**Review by sfshaza2 — COMMENTED** [review]
@filiph, this updates the package to null safety. Should we merge or wait?

**Comment by filiph** [comment]
Hi @siddhant-dev, have you tried running the app with the change? Just checking. We have a system in which all code on the site is continuously tested. See here: https://github.com/flutter/website/blob/master/examples/state_mgmt/simple/pubspec.yaml and [here](https://github.com/flutter/website/blob/master/examples/README.md). If you want to land this, you'll have to change the source as well.

@sfshaza2 I think this actually doesn't migrate to null safety. provider 4.3.3 is the last version before 5.0.0 (which is null safe).

**Comment by sfshaza2** [comment]
I'd like to get confirmation on this PR in the next 15 hours, or I will close it. Thx

**Comment by siddhant-dev** [comment]
Hi @filiph 

Thanks for helping. I have updated the pubsec.yaml file for expample/simple project and ran the commands mentioned in README file. All are green and good to go. 

Hi @sfshaza2 
I can confirm all test cases have been cleared. 

Thanks 
Sid

**Pull request merged**
