### PR TITLE
Add more widget test debug tips

### PR DESCRIPTION
**Pull request by xster**

### CODE REVIEW

**Comment by Hixie** [comment]
You may also want to link to the debugging doc.

Also a hint we should list here is that you can `flutter run` a test to see it on the device, and tap things on the screen to get finders for those things. (That's broken right now but I'm fixing it so don't worry about it being broken.)

**Comment by Hixie** [comment]
LGTM

**Comment by xster** [comment]
@Hixie, are you referring to https://flutter.io/debugging? Seems like it's a bit too live debug focused for this use case

**Comment by xster** [comment]
Ummm seems like I can't rebase branches on the flutter user :S

The travis issue is fixed in https://github.com/flutter/website/pull/749. Going to submit and monitor.

**Pull request merged**
