### PR TITLE
Add extra verification for firebase.json

### PR DESCRIPTION
**Pull request by parlough**
Reintroduces a derivative of tooling I introduced before the new architecture that will provide some extra, specific feedback if any problems are introduced in the `firebase.json`. Primarily checks the sources and destinations of redirects.

Closes https://github.com/flutter/website/issues/3383

### CODE REVIEW

**Comment by sfshaza2** [comment]
@craiglabenz

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Comment by sfshaza2** [comment]
@craiglabenz  This one needs DRE approval

**Review by craiglabenz — APPROVED** [review]
Nice, LGTM!

**Review by atsansone — APPROVED** [review]

**Pull request merged**
