### PR TITLE
Adding getx as a state management option

### PR DESCRIPTION
**Pull request by eduardoflorence**
Changes proposed in this pull request:

* Adds the [GetX](https://pub.dev/packages/get) package as an option among state managers.
* **Currently GetX is the second most liked package on pub.dev**
* For newer developers, GetX can help simplify work with Flutter
* As a package user, I can attest that this package has greatly improved my productivity with Flutter

### CODE REVIEW

**Comment by ram231** [comment]
Hi @eduardoflorence, are you aware of the (merged)PR here? https://github.com/flutter/website/pull/4981 
From @filiph 
> It looks like the package author makes some pretty wild claims* on social media. Removing the links, at least until we can verify that these claims are true.

> *) The claims are about the package's official support from Google and/or usage by Google Product Managers — neither of which I'm aware of. I'd also like to verify the claims about performance (currently, they are backed only by a benchmark written by the author).

**Comment by eduardoflorence** [comment]
Hi @ram231, I am aware. The author made modifications to the package readme today to make it clear that it was an individual benchmark test. I invite you to observe the changes in:
https://github.com/jonataslaw/getx/commit/244bea2d51b329e1traitf7a6f8b04bc96ac2548a1#diff-8af7464e14809e004854865f47e6758531ee94a22045326ac43fabff2f11ebad

**Comment by ram231** [comment]
Quote from the documentation here: https://github.com/jonataslaw/getx/commit/244bea2d51b329e1bd8f7a6f8b04bc96ac2548a1
> _Granular control_: most state managers are based on ChangeNotifier. ChangeNotifier will notify all widgets that depend on it when notifyListeners is called. If you have 40 widgets on one screen, which have a variable of your ChangeNotifier class, when you update one, all of them will be rebuilt.

I still don't know if this claim is true or not.

**Comment by aloisdeniel** [comment]
It is false, other solutions encourage you to filter rebuilds (Provider's Selector, bloc's select, redux Consumer, ...).

**Comment by filiph** [comment]
Thanks for the PR, @eduardoflorence. I understand it is frustrating to see the package you love removed from the options page here on flutter.dev.

I will leave this PR open and revisit it in a few weeks from now. Here's my rationale:

1. There needs to be some cool off period. If a package that we promote on flutter.dev claims misleading things in the README, it's not enough if the authors just quickly remove those things and suddenly everything's fine. Past behavior is the best predictor of future behavior. Trust needs to be earned.
2. GetX is still alive and well on pub.dev. We're only talking about a page on flutter.dev here.

Separately, I'd like to address a comment from @stefandevo I got this morning:

> @filiph so you are now checking ALL social media from ALL authors here to check whether they made some kind of claim? There are authors on this page that also falsely accused other persons on social media about X and Y. Pretty disappointed in this community about this specific case. So is there a page where we can post all harsh statements from somebody about Flutter too? (just kidding of course).

We're not actively checking social media. But we do need to take issues raised by the community seriously. If there's _any_ package featured on flutter.dev that is making misleading or false claims, or whose authors are harassing anyone, please report them by filing a bug here and cc me.

**Comment by filiph** [comment]
Hi, as promised, I'm getting back to this. I haven't heard any new reports about boastful or misleading messaging from GetX in the past month. In my book, GetX can get back on the `options/` page. I will merge this PR. Welcome back!

As I said before, if there's _any_ package featured on flutter.dev that is making misleading or false claims, or whose authors are harassing anyone, please report them by filing a bug here and cc me.

**Pull request merged**
