### PR TITLE
Fixing title and superscripts

### PR DESCRIPTION
**Pull request by sfshaza2**
As it says

### CODE REVIEW

**Review by atsansone — CHANGES_REQUESTED** [review]
This may not have been an error with the Markdown other than there was no space between the footnote and the link next to it. Consider fixing that instead of a full rewrite with HTML. We're trying to remove inline HTML as we find it as it isn't proper markdown.

See [Markdown Guide](https://www.markdownguide.org/extended-syntax/#footnotes) and [GitHub Markdown Guide](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#footnotes).

**Comment by sfshaza2** [comment]
@atsansone, please remove the "request changes" tag. We've discussed this.

**Review by domesticmouse — APPROVED** [review]

**Comment by atsansone** [comment]
> @atsansone, please remove the "request changes" tag. We've discussed this.

Yes, but this should be checked to see why the normal footnotes don't work. I'd prefer not to push this through when it may have been another issue, like spacing.

@parlough : This appears to be an issue with how 11ty handles footnotes. Its preprocessor goes Markdown -> Liquid -> HTML. This can be changed or the [`markdown-it-footnote` npm package](https://www.npmjs.com/package/markdown-it-footnote) can be installed.

**Comment by sfshaza2** [comment]
@parlough, I defer to however you want to fix this. But the page is pretty messed up currently.

**Comment by sfshaza2** [comment]
I created issue https://github.com/flutter/website/issues/10919

**Review by parlough — APPROVED** [review]
Thanks for the fix and for waiting @sfshaza2!

I updated the PR to enable the Markdown renderer to support the footnote syntax.

**Review by atsansone — APPROVED** [review]
Perfect! Thanks @parlough

**Pull request merged**
