### PR TITLE
Automated link checks in Travis

### PR DESCRIPTION
**Pull request by mit-mit**
**NOTE**: This should not be merged prior to fixing the currently 18 broken links we have, see https://github.com/flutter/flutter/issues/7306#issuecomment-269614000 (I don't personally know the framework history myself to be able to fix them).

### CODE REVIEW

**Comment by mit-mit** [comment]
@Hixie @abarth @sethladd automated link checking in Travis as discussed in https://github.com/flutter/website/pull/340.

Question: The current config here checks links in all job types (PRs, pushes, Cron, and API). Do we want to exclude any of those (e.g. pushes)?

**Comment by mit-mit** [comment]
@sethladd any news on someone in the framework team fixing the broken links in https://github.com/flutter/flutter/issues/7306#issuecomment-269614000 ?

**Comment by sethladd** [comment]
Sorry, no change, but I suspect it's because it wasn't on the radar sufficiently.

I moved it up to https://github.com/flutter/flutter/issues/7480

Thanks for the ping.

**Comment by LarkAscending** [comment]
Errors addressed, pls run link checker and LMK if any remain...

**Comment by mit-mit** [comment]
Still seeing 10 failures; updated list added in https://github.com/flutter/flutter/issues/7480

Full travis output: https://travis-ci.org/flutter/website/builds/189512172

**Comment by mit-mit** [comment]
Yay, link checker is now passing!

@Hixie @abarth @sethladd can I get a LGTM to submit this?

**Comment by abarth** [comment]
Mission accomplished

**Pull request merged**
