### PR TITLE
Update hello world example to match current behavior

### PR DESCRIPTION
**Pull request by mattrenquist**
The current hello world example does not run. Adding 'textDirection' to match the code in examples/hello_world/lib/main.dart fixes the bug and allows the code to run. The website documentation should be updated to match the current code.

### CODE REVIEW

**Comment by mattrenquist** [comment]
Signed the CLA on 10:30 PST 9/17/2017.

**Comment by Hixie** [comment]
Can you add a space after the comma?

**Comment by Hixie** [comment]
The Travis failure is because we're requiring the use of dartfmt, but here dartfmt is making the code uglier by wrapping in a poor way. We should probably exclude this file from dartfmt verification.

cc @sethladd

**Comment by mattrenquist** [comment]
Added the space. Thanks.

**Comment by Hixie** [comment]
or maybe we can tell dartfmt to accept longer lines? iirc @mit-mit solved our most recent issue with Travis in this repo, maybe he has a quick way to address this one too. :-)

**Comment by mit-mit** [comment]
`dartfmt` can be passed a `--line-length` argument to specify a longer wrapping length than it's default of 80. But we invoke `dartfmt` in a [single location](https://github.com/flutter/website/blob/master/tool/travis.sh#L41) for all formating checks, so would need to make that change globally.

**Comment by mit-mit** [comment]
@Hixie @sethladd did you figure out how we want to handle this formatting issue?

**Comment by Hixie** [comment]
I have no particular opinion on how to solve this. I don't think dartfmt can handle this code in a good way. I'd be fine with excluding this file, changing the line width globally (assuming it doesn't make anything else worse), not using dartfmt at all, or any other similar solution.

**Comment by Sfshaza** [comment]
A longer-than-80-char line length means that code can wrap and look bad when displayed inside a web page.

**Comment by sethladd** [comment]
Or, add trailing commas to the snippet, reformat it with dartfmt

**Comment by Hixie** [comment]
@sethladd or @Sfshaza, can one of you update this to be wrapped as the Web site expects and then land this? Thanks!

**Comment by mit-mit** [comment]
I suggest we just add some trailing commas and auto-format, which would give us:

```
import 'package:flutter/material.dart';

void main() {
  runApp(
    new Center(
      child: new Text(
        'Hello, world!',
        textDirection: TextDirection.ltr,
      ),
    ),
  );
}
```

**Comment by sethladd** [comment]
formatting lgtm

**Comment by mit-mit** [comment]
Pushed that change to this PR

**Comment by mit-mit** [comment]
Travis is happy now, merging.

@mattrenquist thanks for contributing, and sorry for being so slow with this PR.

**Comment by mattrenquist** [comment]
No worries. Glad I could help out even a little. Thanks.

**Pull request merged**
