### PR TITLE
Update parallax-scrolling.md

### PR DESCRIPTION
**Pull request by afradahsan**
#10138 

In the Parallax scrolling page, in one of the code, there are some unwanted brackets as mentioned in the docs.
I just fixed that and is creating the request.

### CODE REVIEW

**Comment by afradahsan** [comment]
Some checks were not successful
 -test / Check excerpts and run tests (Stable channel, stable, false) (pull_request)
 -flutter-website-staging (flutter-docs-prod)

Is there something that i should resolve from my side?

**Comment by domesticmouse** [comment]
This change requires changing the related sample. As the related sample compiles, maybe the issue is a better excerpt could be found? Or maybe the sample need refactoring?

**Comment by sfshaza2** [comment]
@afradahsan, until you can fix the broken code excerpt, we can't land this.

**Comment by sfshaza2** [comment]
Superceded by https://github.com/flutter/website/pull/10180. Thanks for filing, @afradahsan. Closing.

**Pull request closed without merging**
