### PR TITLE
Removed duplicate search and ToC blocks for GAR

### LINKED ISSUE #9707: Fix duplication of in-page ToC
a11y script found duplicate ID for the in-page ToC. The ToC is rendered twice: on [lines 42-45](https://github.com/flutter/website/blob/main/src/_layouts/default.html#L42-L45) for desktop layout and [lines 20-23](https://github.com/flutter/website/blob/main/src/_layouts/default.html#L20-L23) for mobile layout. This raises a [WCAG F77 error](https://squizlabs.github.io/HTML_CodeSniffer/Standards/WCAG2/#sc4_1_1) on pages with in-page ToCs.  This causes issues with accessibility technology. This should be fixed.

### LINKED ISSUE #9708: Fix duplication of side navigation
a11y script found duplicate left navigation data. This code exists in [lines 38-40](https://github.com/flutter/website/blob/main/src/_includes/header.html#L38-L40) header.html and [line 17](https://github.com/flutter/website/blob/main/src/_layouts/default.html#L17) of default.html. This raises multiple [WCAG F77 errors](https://squizlabs.github.io/HTML_CodeSniffer/Standards/WCAG2/#sc4_1_1).  This causes issues with accessibility technology. These lines should be hidden.

```html
          <div class="site-sidebar site-sidebar--header d-md-none">
            {% include_cached sidenav-level-1.html nav=site.data.sidenav page_url_path=route %}
          </div>
```

### PR DESCRIPTION
**Pull request by atsansone**
Removes hidden ToC and search form. Fixes #9707 Fixes #9708

Staged site  https://tony-flutter-site.web.app

### CODE REVIEW

**Review by parlough — CHANGES_REQUESTED** [review]
I don't think this is the solution for those issues. This PR removes the table of contents from all pages as well as the mobile/narrow screen sidenav.

**Comment by parlough** [comment]
Feel free to assign the issues to me if you'd prefer I work on them as I have explored a few fixes to these issues before. Or we can discuss them further.

**Comment by atsansone** [comment]
Yeah, the inline ToC needs to be restored. The other changes don't appear to have adversely affected anything.

**Comment by atsansone** [comment]
Per @parlough , closing for other change.

**Pull request closed without merging**
