### PR TITLE
Update libimobiledevice installation instructions

### PR DESCRIPTION
**Pull request by tvolkert**
HEAD libimobiledevice depends on HEAD usbmuxd.

https://github.com/flutter/flutter/issues/22595

### CODE REVIEW

**Comment by tvolkert** [comment]
@Sfshaza is updating `master` the right thing to do?  Should I be also (or instead) updating the `dash` branch?

**Comment by chalin** [comment]
Yes, `master` is now the right branch to target (`dash` is going away).

**Comment by chalin** [comment]
I think that there should be a note linking back to https://github.com/flutter/flutter/issues/22595 and pointing out that this is a temporary workaround.

**Comment by sfshaza2** [comment]
Yes, @tvolkert!  We've deleted the dash branch today, once we pushed it to master.

**Pull request merged**
