### PR TITLE
Prepare DevTools release notes for version 2.39.0

### PR DESCRIPTION
**Pull request by elliette**

### CODE REVIEW

**Comment by elliette** [comment]
Hi @parlough @Sfshaza - have you seen this failure before on the flutter-website-staging action? Thanks!

```
Step #1: [11ty] Eleventy Fatal Error (CLI):
Step #1: [11ty] The requested module 'liquidjs' does not provide an export named 'default' (via SyntaxError)
Step #1: [11ty] 
Step #1: [11ty] Original error stack trace: file:///workspace/node_modules/@11ty/eleventy/src/Engines/Liquid.js:2
Step #1: [11ty] import liquidLib, { Tokenizer, evalToken } from "liquidjs";
Step #1: [11ty]        ^^^^^^^^^
Step #1: [11ty] SyntaxError: The requested module 'liquidjs' does not provide an export named 'default'
Step #1: [11ty]     at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
Step #1: [11ty]     at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
Step #1: [11ty]     at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
Step #1: [11ty]     at async /workspace/node_modules/@11ty/eleventy/cmd.cjs:57:24
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/flutter-dev-230821/firebase-ghcli" failed: step exited with non-zero status: 1
```

**Comment by sfshaza2** [comment]
@elliette, no, I haven't but I'm confident the @parlough knows what is going on. I am manually forcing a CI build, and we'll see if that fixes it.

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Pull request merged**
