### PR TITLE
Add Korean translations

### PR DESCRIPTION
**Pull request by thankee**
Add Korean translations

Changes proposed in this pull request:

*  Add Korean translations

### CODE REVIEW

**Comment by sfshaza2** [comment]
Hi, @thankee! Thanks for your translations, but you have filed this again the wrong repo. This is the English-language Flutter website.  @chenglu, can you advise @thankee? Closing

**Comment by sfshaza2** [comment]
Actually, my mistake. @chenglu manages the Chinese-language Flutter site. I'm not sure who manages the Korean-language site.

**Comment by chenglu** [comment]
Hi @sfshaza2 and @thankee,

I did some research, PR [#4555](https://github.com/flutter/website/pull/4555) shown that Michael(@micpap25) might be the right person to reach out to, and the repo [micpap25/website](https://github.com/micpap25/website) might be the correct repo to contribute the Korean language translations.

I also saw some of the Korean-language PRs or Issues filed to the main repo (flutter/website), that is because the localization site maintainers did not update the config.yml file. So I also filed a PR https://github.com/micpap25/website/pull/2 to fix the Korean-language site (if this is the right site).

Wish it helps, and please let me know if you have further questions!

Thanks,
-Luke

**Comment by micpap25** [comment]
Hi @chenglu , 
Thank you for your research, however I don't maintain the Korean site. #4555 was me resolving a request to add the Korean site to the footer. I think the best person to reach out to might be the creator of that issue, @techhtml, or possibly @brojo .

**Comment by chenglu** [comment]
Great thanks to @micpap25, I think you did point out the right person ;-) 
Good job!

**Comment by sfshaza2** [comment]
Thanks so much, @chenglu and @micpap25! I really appreciate you tracking this down!

**Pull request closed without merging**
