### PR TITLE
Make it clear full Xcode is required

### PR DESCRIPTION
**Pull request by AdrianDAlessandro**
_Description of what this PR is changing or adding, and why:_
This adds a small detail to the website docs to explain that the entire Xcode is required for macOS development and not just the Xcode Command-line tools (which is usually adequate)

_Issues fixed by this PR (if any):_
NA

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by domesticmouse** [comment]
Please sign the CLA, we can't land this PR without it.

**Comment by AdrianDAlessandro** [comment]
> Please sign the CLA, we can't land this PR without it.

Done. All tests are passing now.

**Comment by domesticmouse** [comment]
PTAL @sfshaza2

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Pull request merged**
