### PR TITLE
added AnimatedList widget in catalog

### LINKED ISSUE #5198: 'Animation and motion widgets' page issue
Page URL: https://flutter.dev/docs/development/ui/widgets/animation.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/widgets/animation.md

Description of issue:

AnimatedListState is being shown rather than AnimatedList itself.

### PR DESCRIPTION
**Pull request by piedcipher**
_Description of what this PR is changing or adding, and why:_ Added [`AnimatedList`](https://api.flutter.dev/flutter/widgets/AnimatedList-class.html) widget to [Widget Catalog](https://docs.flutter.dev/development/ui/widgets/animation).

_Issues fixed by this PR (if any):_ Fixes #5198

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by piedcipher** [comment]
I don't seem understand why CI is failing?! Can anyone please help?

**Comment by piedcipher** [comment]
I think failure is due to #7548

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Comment by piedcipher** [comment]
cool, thanks for the review! How can I fix the CI error? It's due to this commit https://github.com/flutter/website/pull/7548/commits/c3a1f2d37eb81895d4378b47174e36d63223c6ee

**Comment by piedcipher** [comment]
https://github.com/flutter/website/pull/7562#issuecomment-1252104327

Cooool

**Review by domesticmouse — APPROVED** [review]

**Pull request merged**
