### PR TITLE
Replaced detail page screenshot

### LINKED ISSUE #9094: Update the last screenshot on the 'Set up app links for Android' page
### Page URL

https://docs.flutter.dev/cookbook/navigation/set-up-app-links/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/navigation/set-up-app-links.md

### Problem

The last screenshot of this page should be displaying Details screen not Home screen

### PR DESCRIPTION
**Pull request by atsansone**
Fixes #9094

### CODE REVIEW

**Review by chunhtai — APPROVED** [review]
LGTM

**Review by parlough — CHANGES_REQUESTED** [review]
I'm assuming you intended to replace the already existing PNG file instead adding a new jpg? `set-up-universal-links-simulator-deeplinked.png`

**Review by parlough — CHANGES_REQUESTED** [review]
Sorry I didn't notice this in the first review, but also looks like you meant to replace `/assets/images/docs/cookbook/set-up-app-links-emulator-deeplinked.png` instead. 

The image you replaced is for iOS universal links, but the issue (and your screenshot) is for the Android app links page.

**Review by parlough — APPROVED** [review]
Thanks!

**Pull request merged**
