### PR TITLE
Add a link to the Flutter for web developers guide

### PR DESCRIPTION
**Pull request by AmosHuKe**
_Description of what this PR is changing or adding, and why:_
Add a link to the Flutter for web developers guide.

image

_Issues fixed by this PR (if any):_
None.

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Comment by domesticmouse** [comment]
Shams, the content at `/get-started/install` is not really an introduction to Flutter for web developers. It's how to get started using Flutter for the web.

I'd argue we probably need to think about what content we would give a developer coming from the web to Flutter, but "install these tools" is probably not it.

**Pull request merged**
