### PR TITLE
Update firebase.json

### PR DESCRIPTION
**Pull request by Calamity210**
Corrects link for /go/material-banner-updates.

(Tested this link by accessing it in incognito mode)

### CODE REVIEW

**Comment by sfshaza2** [comment]
Hi, @Calamity210! Hmm. The problem lies with the doc itself. I will make sure to test by opening the docs in incognito mode in future. Is it possible for you to change permissions to make it available to everyone?

**Comment by Calamity210** [comment]
@sfshaza2 are you unable to access it with the link I've updated it to in this PR? I've given everyone commenter permissions already.

**Comment by sfshaza2** [comment]
Yes, I can, but I'm not sure about sharing this particular version of the link. Let me ask around.

**Comment by Calamity210** [comment]
ah. I'd assume it's fine though, a couple of the [links](https://flutter.dev/go/deprecation-statustransitionwidget) already point to links of a similar format.

**Comment by sfshaza2** [comment]
You're right. With your addition, the "resourcekey" qualifier is used in TEN of the URLs. I don't like it, but I'll accept it. :)

**Comment by sfshaza2** [comment]
LGTM

**Pull request merged**
