### PR TITLE
Update deprecated method use

### PR DESCRIPTION
**Pull request by lenartowski**
`builder` method for `ChangeNotifierProvider` class is deprecated in favor of `create`

### CODE REVIEW

**Comment by lenartowski** [comment]
@googlebot I signed it!

**Comment by lenartowski** [comment]
> CLAs look good, thanks!
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fflutter%2Fwebsite%2Fpull%2F3484) for more info**.

You're welcome mr Bot!

**Comment by sfshaza2** [comment]
@filiph, this looks good to me, but can you confirm?

**Comment by sfshaza2** [comment]
Thanks for that review, @filiph!  @lenartowski, are you up for these changes?

**Comment by lenartowski** [comment]
@filiph , @sfshaza2 thanks for input and instructions! Yes, I will do those changes and issue new PR

**Comment by lenartowski** [comment]
@filiph I updated PR with changes in places that you pointed. I tried to run `./tool/refresh-code-excerpts.sh` script but it resulted in error:
`tool/shared/env-set.sh: No such file or directory`
it points to `site-shared/env-set.sh` file which does not exist in repository, can you help me how should I fix this?

**Comment by sfshaza2** [comment]
@lenartowski, when you cloned the repo, did you also run `git submodule update --init --remote`? Once you retrieve this submodule, you should have the necessary scripts. It's explained in the README file for the repo.

**Comment by lenartowski** [comment]
@sfshaza2 thanks, that was it, I should have read instructions more carefully 🙄 

I updated PR with changes in .md files produced by `./tool/refresh-code-excerpts.sh` script. Does that look ok? Some changes are kinda unexpected for me, like the one in `src/docs/get-started/codelab.md` file.

**Comment by lenartowski** [comment]
Hi @sfshaza2 and @filiph , can you confirm that my change are sufficient?

**Comment by sfshaza2** [comment]
Hi, @lenartowski, I haven't had a chance to look at this yet, and @filiph is winging his way to way to [Flutter Europe](https://fluttereurope.dev/). Also, Monday (tomorrow) is a holiday in the U.S. I will take a closer look when I get a chance.

**Comment by sfshaza2** [comment]
Filip asked for changes, which is still reflected in his review. But you did make the changes, so I'm going to go ahead and merge it. :D

**Comment by lenartowski** [comment]
Cool, thank you both for guidance! I just became an OSS contributor 💪 😄

**Pull request merged**
