### PR TITLE
Migration of "internationalization" examples to null safety

### PR DESCRIPTION
**Pull request by miquelbeltran**
In this PR I migrate the small projects inside the internationalization folder in the examples to null safety.

Most code changes are due to the fact that `Localizations.of<..>` returns a nullable type. I decided to use the "bang operator" to force it to not being nullable, since the original code wasn't taking care of null cases, but also IMO a null value in localizations would mean a bug in code, so failing silently would be counterproductive. I want to hear your opinion on this :)

To test the code, I run the examples as a Flutter web app, as there were no tests in the files.

@sfshaza2 @RedBrogdon

### CODE REVIEW

**Comment by miquelbeltran** [comment]
Saw the warning, working on it. Somehow it did not appear here locally. sorry!

**Comment by domesticmouse** [comment]
Can you please bring this PR up to date with master? It's Github Actions is currently pinned to an old version of Flutter, which is why the tests are failing.

**Review by domesticmouse — APPROVED** [review]
LGTM, once tests pass

**Comment by sfshaza2** [comment]
Thanks, @domesticmouse!

**Pull request merged**
