### PR TITLE
adding linux dependency

### PR DESCRIPTION
**Pull request by rodrigobastosv**
I was getting error running my project with flutter linux. Very similar error to this one https://github.com/flutter/flutter/issues/71557.

This answer within the same thread solved my issue https://github.com/flutter/flutter/issues/71557#issuecomment-753606037

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by domesticmouse** [comment]
I'm curious which version of Flutter you are running? Looking at the `linux/CMakeLists.txt` file generated by Flutter 2.8.1 contains no references to lzma. I have vague recollections that we deleted it reasonably recently.

**Comment by rodrigobastosv** [comment]
Hi @domesticmouse , that's strange, i'm running Flutter 2.8.1.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on Ubuntu 20.04.2 LTS 5.11.0-43-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] VS Code
[✓] Connected device (2 available)

• No issues found!
```

**Comment by domesticmouse** [comment]
Additional context, I ran up a new Flutter Linux desktop app in a freshly created Ubuntu 20.04.3 LTS under WSL2 (Win11) and it works fine with the instructions as is.

I'm curious what Linux distribution and version you are running. We may need to add a note or call out about `liblzma` might be required or some such.

**Comment by rodrigobastosv** [comment]
I'm running a fresh Ubuntu 20.04.1. Not under WSL2

**Comment by domesticmouse** [comment]
Do you want to modify your PR to add `liblzma` as a might be required addition?

**Comment by rodrigobastosv** [comment]
Just added!

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
Looks like there is a broken link: https://github.com/flutter/website/runs/4930640177?check_suite_focus=true#step:5:11

**Comment by rodrigobastosv** [comment]
Fixed!

**Comment by domesticmouse** [comment]
PTAL @sfshaza2

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Pull request merged**
