### PR TITLE
Accessibility

### PR DESCRIPTION
**Pull request by tBoccinfuso**
New PR with same changes, last one seemed to be closed when master was changed.

### CODE REVIEW

**Comment by tBoccinfuso** [comment]
@chalin Opened a new PR for the accessibility changes.

**Comment by sfshaza2** [comment]
@fertolg, can either you or @c-machado weigh in?

**Comment by chalin** [comment]
A few remarks:

- @c-machado does it really add value to have some sections labelled in this way?
  - For example, there is no element in the carousel that can get a focus, so maybe this ARIA lable isn't useful.

If we do decide to add some labels, here are some more questions:

- @c-machado: do we need `role="contentinfo"`?
- Not all `section` elements have a label:
  - The section containing the CTA doesn't have a label but it probably should.
  - Again, I'm unsure that the carousel should have a label.
- The text for some labels might need revision - @sfshaza2 maybe you'd like to take a look at that?

**Comment by sfshaza2** [comment]
@fertolg, I don't see to have @c-machado's email. Can you ping and ask her to look at this?

**Comment by sfshaza2** [comment]
I am closing this PR. We can reopen if we get more definitive info on making the page more accessible. (See Patrice's (@chalin) questions above.

**Pull request closed without merging**
