### PR TITLE
Corrected the code snippet of NativeViewFactory

### PR DESCRIPTION
**Pull request by Roshan13046**
Fixes #71662 (moved to this repo) so, fixes https://github.com/flutter/website/pull/5129

### CODE REVIEW

**Review by sfshaza2 — COMMENTED** [review]
@blasten, this looks good to me. Can you confirm?

**Review by blasten — APPROVED** [review]
LGTM

**Comment by Roshan13046** [comment]
> LGTM

Thanks! This was my first merged open source contribution to flutter Repo.

**Comment by blasten** [comment]
Awesome! Thanks for the contribution

**Pull request merged**
