### PR TITLE
macOS setup instructions in macOS install page

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/website/issues/5755

### CODE REVIEW

**Comment by TahaTesser** [comment]
@sfshaza2 
Can you please review this? Thanks

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Comment by tesserx** [comment]
@sfshaza2 Thanks so much for the reviews!

**Comment by TahaTesser** [comment]
@sfshaza2 Thanks so much for the reviews!

**Pull request merged**
