### PR TITLE
Update android-setup.md

### PR DESCRIPTION
**Pull request by mit-mit**
Fixes https://github.com/flutter/flutter/issues/13071

### CODE REVIEW

**Comment by xster** [comment]
I think we'd want to keep both instructions. Oreo is just 0.3% of the market share :S

**Comment by LarkAscending** [comment]
Yes, the DAC site uses this wording (and an extra step);

> 2. (Only on Android 8.0 or higher) Select System.

Any objections if we just link to the [Android page](https://developer.android.com/studio/debug/dev-options.html) for dev mode/debugging instead?

**Comment by mit-mit** [comment]
Updated to refer to Android docs, PTAL

**Comment by mit-mit** [comment]
@LarkAscending @xster can you take another look, please?

**Comment by xster** [comment]
LG

**Pull request merged**
