### PR TITLE
Revert "Revert "Remove DevTools survey metadata json and add redirect.""

### PR DESCRIPTION
**Pull request by kenzieschmoll**
Reverts flutter/website#9941 (which is a reland of https://github.com/flutter/website/pull/9935). The CORS issue has been fixed (see https://github.com/flutter/uxr/issues/128 and https://github.com/flutter/uxr/pull/130).

### CODE REVIEW

**Comment by parlough** [comment]
This was confirmed to work with the new cors configuration on the direct URL?

**Review by parlough — APPROVED** [review]

**Comment by kenzieschmoll** [comment]
Let's hold off on landing this. I have confirmed that the cloud storage request succeeds locally, but I'm not sure if the redirect works as expected.

**Comment by parlough** [comment]
@kenzieschmoll Could you test the redirect on the staged site https://flutter-docs-prod--pr9942-revert-9941-revert-9935-dt-s-bv28paoo.web.app/f/dart-devtools-survey-metadata.json to see if that works within DevTools?

**Comment by kenzieschmoll** [comment]
Even without this PR landed, https://docs.flutter.dev/f/dart-devtools-survey-metadata.json is redirecting to https://storage.googleapis.com/flutter-uxr/surveys/devtools-survey-metadata.json. @parlough any idea why that might be?

**Comment by parlough** [comment]
Looks like https://github.com/flutter/website/commit/cd092156e45d302396c06d739660055891c20da1 accidentally relanded your commit and added it back. 

I'm not at a computer to undo it right now, so if it's causing issues, mind updating this PR or opening a new one? Otherwise I can get to it later. Thank you :)

**Comment by kenzieschmoll** [comment]
@parlough addressed in https://github.com/flutter/website/pull/9954. I won't have time to confirm the behavior in this PR works as expected for a couple of weeks (holiday OOO). We can either close this PR an I'll re-open later or I'll pick this back up in January.

**Comment by parlough** [comment]
Sounds good. There's no issue having this here and in the cloud storage bucket, so I'm happy to push this off to later. Going to close for now to make things easier to track.

Have a nice holiday!! @kenzieschmoll ☃️

**Pull request closed without merging**
