### PR TITLE
Small typo Avator => Avatar

### PR DESCRIPTION
**Pull request by smblee**
Very small typo i found while reading the documentation

### CODE REVIEW

**Comment by smblee** [comment]
I signed it!

**Comment by Sfshaza** [comment]
@smblee, can you resolve the conflicts?

**Comment by Sfshaza** [comment]
Forcing a merge as this is just one word that was misspelled.

**Comment by Sfshaza** [comment]
It wouldn't let me force it, probably because so much has changed.

Addressed this bug in PR https://github.com/flutter/website/pull/1191

**Pull request closed without merging**
