### PR TITLE
Do some rejiggering of the url_strategies page

### PR DESCRIPTION
**Pull request by sfshaza2**
This PR replaces another [that I closed](https://github.com/flutter/website/pull/5663). It changes the page to more closely follow the [Google Documentation Developer guidelines](https://developers.google.com/style). It also fixes the formatting of the definition list.

### CODE REVIEW

**Review by johnpryan — APPROVED** [review]

**Comment by hrishikesh-kadam** [comment]
@Sfshaza The list still requires proper indentation to reflect correct numbering. [Reference](https://github.com/dart-lang/site-shared/blob/master/doc/markdown.md#do-properly-indent-markdown-lists).

**Comment by sfshaza2** [comment]
You are so correct, @hrishikesh-kadam! Unfortunately, a numbered list in markdown is not very robust. I'll fix it.

**Comment by hrishikesh-kadam** [comment]
The incorrect reflection of the ordering of numbers on the web page was my first intention to fix the formatting in #5663.
The rest of the fixing (rather suggestions) was just to make the doc look better.

**Comment by sfshaza2** [comment]
Ah! I didn't realize that. The original PR just said "fix the formatting". :). By the way, my current GitHub handle is sfshaza2.

**Comment by hrishikesh-kadam** [comment]
Ohh! Sorry I missed that 2 at the last.
I did mention at the very first line [here](https://github.com/flutter/website/pull/5663#issue-620004223), but no issues, after all my intention was to make the doc look flawless.

**Comment by sfshaza2** [comment]
I truly appreciate that, @hrishikesh-kadam!!! I really do.

**Pull request merged**
