### PR TITLE
Adds workshop links

### PR DESCRIPTION
**Pull request by RedBrogdon**
Adds three redirect links for workshops. Right now they just point to DartPad so we can verify they aren't broken. I'll add the correct URLs in a subsequent PR.

### CODE REVIEW

**Comment by RedBrogdon** [comment]
CC: @johnpryan.

**Comment by Piinks** [comment]
I think the actually links for these can be subbed in, I was just about to do the same. 😜

**Comment by Piinks** [comment]
I believe links are listed in the description for https://github.com/flutter/codelabs/pull/101

**Review by sfshaza2 — APPROVED** [review]
Thanks for not calling them codelabs!!! LGTM

**Pull request merged**
