### PR TITLE
Fixed broken store link, removed hardcoded language location from URLs

### PR DESCRIPTION
**Pull request by mattwojo**
Removing the en-us allows the site to localize to whatever language the user has their browser set to rather than forcing the English version.

_Description of what this PR is changing or adding, and why:_
Fix broken link and remove hardcoded language identifiers

_Issues fixed by this PR (if any):_
Link fixed.
User can now view content at these links based on their selected language preference.

## Presubmit checklist
- [x ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
Thanks so much for correcting these links, @mattwojo!

**Comment by sfshaza2** [comment]
Forcing a merge because we should fix these links.

**Comment by domesticmouse** [comment]
Uh, this needs to be reverted due to lack of CLA

**Comment by mattwojo** [comment]
So sorry - I've been out of office and will sign the CLA as soon as I'm out of this current meeting.

**Comment by domesticmouse** [comment]
Thanks @mattwojo!

**Comment by mattwojo** [comment]
Signed. 
Sorry again for my delay on responding! Thanks for incorporating these updates.

**Comment by domesticmouse** [comment]
Confirmed CLA signature through signcla/

Thanks again @mattwojo!

**Pull request merged**
