### PR TITLE
Added link to itsallwidgets.com

### PR DESCRIPTION
**Pull request by hillelcoren**

### CODE REVIEW

**Comment by hillelcoren** [comment]
I signed it!

**Comment by Sfshaza** [comment]
@maguinis, please review.

**Comment by maguinis** [comment]
"a full list of apps" only consists of 39 apps in this list, and there are thousands of Flutter apps. What's the criteria for them appearing on itsallwidgets? 

Don't want to deceive people into thinking this is in fact a full list.

**Comment by hillelcoren** [comment]
I've updated the text, let me know if it needs further changes.

Thanks again!!

**Comment by maguinis** [comment]
LGTM, thanks!

**Pull request merged**
