### PR TITLE
update all embeds to non-experimental, unforked versions

### PR DESCRIPTION
**Pull request by johnpryan**
staged: https://flutter-website-jr-staging.firebaseapp.com/

https://flutter-website-jr-staging.firebaseapp.com/docs/codelabs/layout-basics.html
https://flutter-website-jr-staging.firebaseapp.com/docs/codelabs/implicit-animations.html

### CODE REVIEW

**Comment by legalcodes** [comment]
Do we need to update the url for dartpad_picker?

**Comment by sfshaza2** [comment]
WOOT! I'll let Jon review/merge.

**Comment by johnpryan** [comment]
@legalcodes good catch - dartpad_picker is using the right version now. This is ready for another look

**Comment by legalcodes** [comment]
LGTM

**Pull request merged**
