### PR TITLE
Incorporating feedback and preparing for publishing.

### PR DESCRIPTION
**Pull request by Sfshaza**
Thanks for yet-another-review, @abarth, @sethladd!
Thanks for volunteering to be guinea pigs and run through the tutorial, @kwalrath, @kevmoo!

Staged here: https://sz-flutter.firebaseapp.com/tutorials/layout

The Flutter Hackathon inspired many of these changes, and other changes are intended to prepare the tutorial for publication. It's still "hidden" on the site - nothing links to it.

* The reviewers wanted to be able to access the source code and images. Linking to these required an early merge with the website in order to link to the files on the GitHub website repo.
* In the code, removed unneeded variables.
* Added more comments to the code, particularly to explain some of the trickier or less obvious Dart or Flutter code, like List.generate or DefaultTextStyle.merge.
* As requested, added a "packed" example.
* The reviewers needed better context on where to insert code snippets, which I solved by including the enclosing method names and shortening the included code using ellipses. (To minimize visual noise.)
* The reviewers felt that some of the screenshots, especially those that diagrammed the rows/columns/widgets, were small and hard to read. I reworked most of the diagrams that use call outs, making them larger, in some cases breaking them into sub diagrams and, hopefully, making them easier to read.
* Added a Tip on using the iOS simulator - important for the Pavlova example.
* I'd been holding off on adding code highlighting until things settled down, but I've now added highlighting. I expect to continue tweaking that.
* Retook many of the screenshots to a) remove the App Bar's drop shadow in some cases and b) to get higher resolution images for creating easier-to-read callouts.
* Updated all graffle files (used for creating the diagrams and saved to _diagrams), to have clear instructions on what to name each diagram.
* Updated all included images with "alt" tags, needed for compliance with accessibility.
* Clarified that the Pavlova image is available under the Creative Commons license from Pixabay.
* Edited the grammatically incorrect language in the lakes example.
* Added better descriptive text to the pubspec files.

### CODE REVIEW

**Comment by sethladd** [comment]
It may be too late now, but the yellow color for the icons in the middle of the screenshot might be hard to see for some people. It's pretty faint, on the white background. Do we need more contrast?

**Comment by sethladd** [comment]
Nevermind, looks like the new version uses Blue for the icons. :)

**Comment by Sfshaza** [comment]
Yes, I was originally using yellow, because that's how David designed the
UI. But those buttons were very hard to see, so I switched it to blue.
Also, it's a nice way to showcase the primary color theme.

**Comment by sethladd** [comment]
"Flutter’s widget tree for this UI is as follows:" might be "The widget tree for this UI is as follows:" or "Here's a diagram of the widget tree for this UI:"

"Flutter's widget tree" makes it sort of sound like "this is the only way to do it". Flutter isn't forcing this widget tree, there are lots of ways you could construct this. :)


I liked the "What's the point" where you give the "tldr" of the section. For example, in "Flutter's approach". So, I was missing the tldr for the next section "Lay out a widget". The "What's the point" is a summary of the steps, not a summary of the concepts. "Lay out multiple widgets" does a good job with the tldr.

I'd _love_ a ToC for this article in some nav. It's a long article. The left-hand ToC is for the entire site. Not sure that's super duper useful?

**Comment by Sfshaza** [comment]
Good feedback, Seth, thanks. 

Yes, I would love to see the Flutter team copy the website implementation used on www.dartlang and webdev.dartlang. We spent a lot of money and months of man hours last spring/summer getting those websites reimplemented and we're pretty happy with them. One of the nicest features is a website-wide lefthand TOC, and an in-page righthand TOC. You can see them in action here:

https://www.dartlang.org/guides/language/language-tour

We spent a lot of time refining the behavior of both TOCs and it works pretty well. The righthand TOC is optional.

Copying @LarkAscending.

**Comment by Sfshaza** [comment]
Great feedback, Seth, thanks.

As for your comments on the TOC. Yes, I would love to see Flutter use the same implementation that we use on www.dartlang and webdev.dartlang. We spent a lot of money and many man-months last spring/summer reimplementing both sites. One of our focuses was on the behavior of the TOCs, specifically. We have a website-wide left-hand TOC and an in-page (optional) right-hand TOC.

You can see both in action here:  https://www.dartlang.org/guides/language/language-tour

Copying @LarkAscending, as this subject is outside of my work scope.  :)

I will work on addressing your other issues. Thx!

**Comment by sethladd** [comment]
> would love to see Flutter use the same implementation that we use on www.dartlang

Good call. Something to consider soon.

**Comment by sethladd** [comment]
lgtm but I didn't review all the content in detail.

**Pull request merged**
