### PR TITLE
Add Brand to Footer, and Assets to Sidebar

### LINKED ISSUE #1720: Add a "Brand and Assets" section to Resources
It may be helpful to have a brand section in the resources where we can include links to the logos (and slide decks) etc that people can use for their events. 

Logo folder: https://drive.google.com/drive/u/0/folders/1KXNtO9My2AMpDOF9A9Y_4aj4_BcgmDDT

### LINKED ISSUE #2150: Add sub-tag under the 'Resources' section for "Official brand logos"
Add sub-tag under the 'Resources' section titled "Official brand logos"

That directs users to this page with our assets: 
https://drive.google.com/drive/folders/1KXNtO9My2AMpDOF9A9Y_4aj4_BcgmDDT

This can help people gain access to the logos they should use. 

Unless there is a suggestion for a better place to place this...

### PR DESCRIPTION
**Pull request by micpap25**
Fixes #1720, Fixes #2150

Puts "Flutter Brand Guide" next to the TOS on the bottom as "brand usage", and adds the drive containing Flutter's official logos in the Resources section as "Official Brand Assets". 

This resolves the issues (which were duplicates) by making the logos more accessible, and also makes the Brand Guide itself more accessible (previously, it could only be accessed through the TOS). 

Additionally, it also removes a redundant line from the TOS. Let me know if all of that is OK.

### CODE REVIEW

**Comment by sfshaza2** [comment]
Thanks for the PR @micpap25! The navigation parts of this PR look good, but modifying the Terms of Service can't be done without involving marketing and legal. I am concerned that your updated text doesn't link to the brand page.

@messi01, can you weigh in?

**Comment by messi01** [comment]
Yes we can't modify the Terms of Service without legal approval.

**Comment by sfshaza2** [comment]
I spoke to marketing offline and they confirmed that, yes, we can't tweak the Terms of Service. Can you back that out and then I can land the PR? Or, if you prefer, I can just close the PR.

**Comment by micpap25** [comment]
Fixed

**Pull request merged**
