### PR TITLE
Update banner with Q2 survey link (please merge after 12PM May 13th PDT)

### PR DESCRIPTION
**Pull request by jayoung-lee**
The survey link will go live on Monday the 13th morning (PDT). Please merge it after 12PM (noon).

I plan to take this banner down after the 26th.

Thanks! :)

### CODE REVIEW

**Comment by sfshaza2** [comment]
I see the build failed because the showcase link failed. It's working now, so I kicked off the build again.

@jayoung-lee, I am OOO on Monday. Ask Jon or Kathy to publish.

**Comment by jayoung-lee** [comment]
Thanks @Sfshaza ! I will ping Jon or Kathy.

**Comment by kwalrath** [comment]
I've restarted the job and will merge this when I see that the build succeeds.

**Comment by kwalrath** [comment]
The build break is not due to this PR, so I'm going to merge it and then try to fix the build in a separate PR.

**Pull request merged**
