### PR TITLE
Update and cleanup shared_preferences cookbook recipe

### PR DESCRIPTION
**Pull request by parlough**
- Suggest a newer and simpler method of testing
- Follow Effective Dart guidelines for comment formatting and clean them up
- Update introduction for current platform support status
- Specify correct supported types
- Other general copy and formatting cleanup

**Staged:** https://flutter-docs-prod--pr9723-feat-update-shared-p-43naiuc4.web.app/cookbook/persistence/key-value

### CODE REVIEW

**Comment by domesticmouse** [comment]
```
info • Unnecessary type annotation on a function expression parameter • test/widget_test.dart:14:49 • avoid_types_on_closure_parameters
```

**Review by domesticmouse — APPROVED** [review]
LGTM once CI passes

**Comment by parlough** [comment]
Thanks for taking a look! https://github.com/flutter/website/pull/9724 implements some fixes and clean up for the test runner that should fix that analysis issue :)

**Review by sfshaza2 — APPROVED** [review]
Thanks for doing this, @parlough! lgtm

**Pull request merged**
