### PR TITLE
Fix formatting of code snippets on iOS dev pages

### LINKED ISSUE #10725: Fix alignment on Dart snippets on first lines of "Flutter for SwiftUI Developers" page
### Page URL

https://docs.flutter.dev/get-started/flutter-for/swiftui-devs

### Page source

_No response_

### Describe the problem

Some of the dart snippets have incorrect whitespace on the first lines:

Screenshot 2024-06-07 at 12 07 40 PM
Screenshot 2024-06-07 at 12 07 36 PM

### Expected fix

Indentation should be formatted.

### Additional context

_No response_

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

### PR DESCRIPTION
**Pull request by piedcipher**
Fix Formatting.

Fixes #10725 

## Presubmit checklist

- [x] This PR is marked as draft with an explanation if not meant to land until a future stable release.
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by parlough — CHANGES_REQUESTED** [review]
Thanks for thinking about improving this!

For some reason it's not triggering, but CI is supposed to include a formatting check against these files with `dart format`. Running `dart format` will revert many of these changes. I'll work on fixing that check. (Edit: https://github.com/flutter/website/pull/11027)

What do you think about instead moving the `docregion` comments above the previous line (like `child: ...`)? It will end up showing some extra information, but I think that's okay considering the examples. We can remove those properties with other [code excerpt functionality](https://github.com/dart-lang/site-shared/tree/main/packages/excerpter#inject-instruction) if needed as well.

**Review by domesticmouse — APPROVED** [review]

**Comment by sfshaza2** [comment]
I dare not insert myself here. When you are back, @parlough, can you address this one?

**Review by sfshaza2 — APPROVED** [review]
If it lgt @domesticmouse, it looks good to me.

**Comment by piedcipher** [comment]
> Thanks for thinking about improving this!
> 
> For some reason it's not triggering, but CI is supposed to include a formatting check against these files with `dart format`. Running `dart format` will revert many of these changes. I'll work on fixing that check. (Edit: #11027)
> 
> What do you think about instead moving the `docregion` comments above the previous line (like `child: ...`)? It will end up showing some extra information, but I think that's okay considering the examples. We can remove those properties with other [code excerpt functionality](https://github.com/dart-lang/site-shared/tree/main/packages/excerpter#inject-instruction) if needed as well.

hey sry, i missed this. when i try to run some excerpter generation command locally i got an error. that's what i remember last.

**Review by parlough — APPROVED** [review]
> hey sry, i missed this. when i tried to run some excerpter generation command locally i got an error. that's what i remember last.

No worries! I went ahead and moved the comments and added replacement instructions for the code excerpt tool. You can check out the commit https://github.com/flutter/website/pull/11021/commits/9346457b46be8819894379050a11b7b7a7e94188 to see what I did.

As for the error, let me know if you hit it again and I'd be happy to fix it or work through a solution with you.

Thanks again for doing this!!

**Pull request merged**
