### PR TITLE
Revert "Removing the GetX package from Options"

### PR DESCRIPTION
**Pull request by eduardoflorence**
Reverts flutter/website#4981

* Adds the GetX package as an option among state managers.
* Currently GetX is the second most liked package on pub.dev
* For newer developers, GetX can help simplify work with Flutter
* As a package user, I can attest that this package has greatly improved my productivity with Flutter

### CODE REVIEW

**Comment by mkiisoft** [comment]
Please, do not spam PR.

**Comment by aloisdeniel** [comment]
What's the difference with #4982 ?

**Comment by eduardoflorence** [comment]
I didn't know that the person who has been criticizing GetX (@escamoteur)  had the power to close PR on behalf of the Flutter team, so I stop here, but GetX keeps growing and improving

**Comment by stefandevo** [comment]
Yeah ... I found out on Twitter that @escamoteur keeps on criticising that package ... so he's not playing it very nice here. He found it strange why GetX had so many likes on pub.dev ... between the lines he accused "that community" of doing fraudulent things to pub.dev to "get the likes". I mentioned the fact that maybe it was because GetX was also mentioned on the page on the flutter website. That was a nice tip he said; result: he added his own packages and then complained so that GetX was removed. This is such a community my friends :-) 

I spent lots of hours to contribute to pub but I think it's not worth it anymore...

**Comment by mkiisoft** [comment]
@eduardoflorence this PR was closed for being a duplicate of #4982 and for being a spam-like-fashion.

**Comment by stefandevo** [comment]
@mkiisoft I not sure why the thumbs down... can you explain pls? Did you check his twitter account?

**Comment by mkiisoft** [comment]
@stefandevo I'm trying to stop the communication over this PR for being a duplicate and avoid the whole drama which is against CoC. @Hixie Please, this comments here. Thanks in advance!

**Comment by eduardoflorence** [comment]
> @eduardoflorence este PR foi fechado por ser uma duplicata do [# 4982](https://github.com/flutter/website/pull/4982) e por ser semelhante a spam.

I understood @mkiisoft, I had closed [# 4982](https://github.com/flutter/website/pull/4982), because a group of haters was making improper comments, but I have reopened

**Comment by stefandevo** [comment]
> @stefandevo I'm trying to stop the communication over this PR for being a duplicate and avoid the whole drama which is against CoC. 

Ok understood; it seems it's no comment allowed here.

**Comment by escamoteur** [comment]
@stefandevo your accusations are wrong. All I did is pointing out lies and misleading information in the docs and changelog of getX.
Yes I find the extreme increase of likes in a short time suspicious but this is about violating the CoC after several communicaty members have tried to convince the package author to change his style which he refused
Over night he made a new commit softening the bragging a bit. But at tge same time started a new claim how much faster his Value and Streams are than ValueNotifier. 
Which is misleading in multiple ways. 
Concerning your tip, you reminded me of what Filiph had already told me,nothing more. 
So acusing me of foul play is wrong.

**Comment by stefandevo** [comment]
@escamoteur I am going to stop this thread here (and on Twitter); your twitter feeds says it all.

**Comment by Hixie** [comment]
People, I don't feel welcomed when I read this thread. This applies to everyone posting here. Please, be kind, be welcoming, be friendly. If you find you would need to post something negative, whether to defend yourself or to criticize or just because you're in a bad mood, just don't, and come back the next day to write it in a positive way instead.

**Pull request closed without merging**
