### PR TITLE
Update faq.md

### PR DESCRIPTION
**Pull request by timsneath**
Update to latest APK size info

### CODE REVIEW

**Review by sfshaza2 — COMMENTED** [review]
Thanks, that looks great! But I will leave this until you take it out of Draft.

**Comment by timsneath** [comment]
Thanks. Trying to update the iOS numbers also before I land this, for consistency.

**Comment by sfshaza2** [comment]
@cbracken, can we get these numbers for iOS?

**Comment by sfshaza2** [comment]
Hi @timsneath! Can we land this or close it? Who could update for iOS?

**Comment by timsneath** [comment]
I'm about to go on vacation for a few weeks, so it will either have to stay in draft (or closed, if that's not OK).

**Comment by sfshaza2** [comment]
FYI. Tim, I am freezing the website repo next Friday (Aug 13th). We must either land this by then or you'll have to submit another PR. (We are changing the website infrastructure, so all remaining PRs will be landed or closed.)

**Review by sfshaza2 — APPROVED** [review]
Landing for now. (I talked to Tim offline.) LGTM

**Pull request merged**
