### PR TITLE
Update flutter-for-react-native.md

### PR DESCRIPTION
**Pull request by joegoodall1**

### CODE REVIEW

**Comment by joegoodall1** [comment]
I signed it!

**Comment by mit-mit** [comment]
Thanks much @joegoodall1, but unfortunately looks like the usually friendly cla both is not seeing it. Can you check the troubleshooting tips it has above?

**Comment by joegoodall1** [comment]
Hi @mit-mit, I've updated my CLA. Hopefully everything is OK now.

**Comment by joegoodall1** [comment]
ps. Another quick thing @mit-mit, I know it's not directly related to Flutter/Dart, but the automated message I received from googlebot starts with "_Thanks for your pull request. t looks like_" rather than "_Thanks for your pull request. It looks like_".

screen shot 2018-03-02 at 10 15 37

**Comment by mit-mit** [comment]
Looks good now, thanks! And, yes, let me bring the spelling issue up with the relevant folks!

**Comment by wmleler** [comment]
There was a merge conflict with a PR I just did. I resolved the conflict and I will go ahead and do the merge.

**Pull request merged**
