### PR TITLE
SomeWidget in examples not clear

### PR DESCRIPTION
**Pull request by pashute**
I clarified where we are in the code, what SomeWidget() is and how you get the current state in the GOOD example. 

Perhaps add a line at line 123 with
    
    // No need for a function like updateWith(Item item)...

### CODE REVIEW

**Comment by pashute** [comment]
@googlebot I signed it!

**Comment by filiph** [comment]
Hi @pashute, thanks for the PR! I like the last change (adding clarification to the line comment, "... using cartModel that has the current state of the cart ...") but I'm not sure about the rest. To me the advantage of explicitly stating where we are is more than offset by the more verbose sample. How strongly do you feel about those other changes?

**Comment by pashute** [comment]
I needed to re-read a few times to understand where I was. To a newb like
me, it was not immediately clear what I'm looking at and why.
A good example should be intuitive (without need for references)
interactive and attractive.

**Comment by sfshaza2** [comment]
Have we lost you, @pashute? I will close if so.

**Comment by pashute** [comment]
I'm not sure I understand what has happened with this request. Did anyone correct the example, or merge my work into the main branch?  If so please close again...

**Pull request closed without merging**
