### PR TITLE
Update the status of Impeller on Android as of 3.22.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Review by zanderso — APPROVED** [review]
cc @mariamhas

**Review by parlough — APPROVED** [review]
🥳 Thanks!

**Comment by chinmaygarde** [comment]
May I get some guidance on the presubmit failure please? I don't believe I caused the reported error.

**Comment by parlough** [comment]
No worries about the failure, it's due to the release being cut. I'll open a separate PR to fix it.

**Review by domesticmouse — APPROVED** [review]

**Review by sfshaza2 — APPROVED** [review]
I'm definitely leery of this "release candidate" phrasing for now, but will revisit later.

**Pull request merged**
