### PR TITLE
Add a short page for Android view integration

### PR DESCRIPTION
**Pull request by xster**
Improves on https://github.com/flutter/flutter/issues/21847

### CODE REVIEW

**Review by gaaclarke — APPROVED** [review]
lgtm!

**Comment by xster** [comment]
@sfshaza2 do you know what's up with the CI check? Seems like some version tangling on head?

**Comment by xster** [comment]
Seems like there were a lot of errors but none are related to my changes. I'll try rebase again.

**Comment by xster** [comment]
@sfshaza2 seems like master's breaking on head since yesterday

Screen Shot 2021-02-05 at 8 45 45 AM

**Comment by sfshaza2** [comment]
@Xiao Yu <xster@google.com>  I just merged a commit that should fix the
code problems. I'll kick off another build.

**Comment by xster** [comment]
Thanks @sfshaza2

**Pull request merged**
