### PR TITLE
Prepare release notes for DevTools 2.13.1

### PR DESCRIPTION
**Pull request by kenzieschmoll**

### CODE REVIEW

**Comment by sfshaza2** [comment]
Kenzie, this website is frozen. Did you intend for it to go on another website?

**Comment by kenzieschmoll** [comment]
> Kenzie, this website is frozen. Did you intend for it to go on another website?

No, this is intended for the flutter website. When will the website be un-frozen?

**Comment by khanhnwin** [comment]
Hi @kenzieschmoll! Is this PR still in a good state to be landed?

**Comment by kenzieschmoll** [comment]
> Is this PR still in a good state to be landed?

I need to push a couple more updates.

**Comment by khanhnwin** [comment]
Okay, just let us know whenever it's ready!

**Comment by kenzieschmoll** [comment]
pushed up changes - ready to commit when bots go green!

**Review by domesticmouse — APPROVED** [review]

**Review by khanhnwin — APPROVED** [review]

**Comment by khanhnwin** [comment]
All green! Thanks @kenzieschmoll!

**Pull request merged**
