### PR TITLE
Update firebase.json

### PR DESCRIPTION
**Pull request by chunhtai**
## Presubmit checklist
- [ ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ ] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by sfshaza2 — DISMISSED** [review]
lgtm

**Comment by sfshaza2** [comment]
For some reason, I'm not authorized to merge this PR. ???

**Comment by domesticmouse** [comment]
> Oh, this was filed on. master. We don't use master, we use main.

We can probably delete the archived master branch now

**Comment by sfshaza2** [comment]
Deleting the archived master is a decision for @hixie. I don't have a strong opinion. Though... does the main branch have all the history of the archived master branch? If so, then maybe we should keep it around. cc @mit-mit

**Comment by chunhtai** [comment]
@sfshaza2 Can you take another look?

**Review by domesticmouse — APPROVED** [review]
LGTM once Goderbauer's edits to the linked doc are landed.

**Comment by domesticmouse** [comment]
> Deleting the archived master is a decision for @Hixie. I don't have a strong opinion. Though... does the main branch have all the history of the archived master branch? If so, then maybe we should keep it around. cc @mit-mit

My understanding is that the complete commit history of `master` is still in `main`.

**Comment by chunhtai** [comment]
> LGTM once Goderbauer's edits to the linked doc are landed.

done

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Pull request merged**
