### PR TITLE
Migrated "mocking" cookbook to null-safety

### PR DESCRIPTION
**Pull request by miquelbeltran**
In this PR I have both fixed the issues reported in #5488 as well as migrated the example to null safety.

The cookbook recipe required updating also because Mockito now uses code generation to support null safety, and some of the code samples were incomplete.

Please feel free to modify the text copy :)

@sfshaza2 @RedBrogdon

### CODE REVIEW

**Comment by sfshaza2** [comment]
I'm not yet asking Brett or John to review because you might add a complete example, yes?

**Comment by miquelbeltran** [comment]
I've added now a complete example, which includes the original code from the fetch-data cookbook recipe, but modified to be testable, and then the mock test at the end.

**Review by sfshaza2 — COMMENTED** [review]
LGTM with one question. We usually try NOT to skip analysis on complete examples. Can we avoid this?

It looks good to me otherwise, but can you review this, @johnpryan?

**Comment by miquelbeltran** [comment]
@sfshaza2 I've got an idea, I think I could move the full example into a project in the `null_safety_examples` and use the code excerpt html tag to integrate the sample. What do you think?

**Comment by sfshaza2** [comment]
Yes, I like that!

**Review by johnpryan — APPROVED** [review]

**Pull request merged**
