### PR TITLE
Adding new /go/ link for custom camera codec proposal

### PR DESCRIPTION
**Pull request by Flajt**
_Description_: Add new go link for camera custom codecs proposal in the firebase.json file. 

_Issues fixed by this PR (if any): None

_PRs or commits this PR depends on (if any): None

## Presubmit checklist

- [x] This PR is marked as draft with an explanation if not meant to land until a future stable release.
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Review by sfshaza2 — COMMENTED** [review]
Oops, I missed this before. This go link is malformed. It has a source, but it lacks the "destination:" flag.

**Comment by Flajt** [comment]
Sorry, mb. Should be fixed now I hope

**Review by parlough — APPROVED** [review]
Thanks for working on this design doc and adding this redirect! Looks good to me :)

**Pull request merged**
