### PR TITLE
Remove incomplete explicit animations codelab

### PR DESCRIPTION
**Pull request by parlough**
We've decided to remove this doc as we'll unlikely have time to finish this in the short term and it just causes confusion sitting there.

If anyone is interested in reviving and finishing this codelab in the future, that would of course be very welcome and appreciated.

You can find the latest up-to-date version of it at: 

**Whole repository:** 
https://github.com/flutter/website/tree/80151fc9d2dd37eb74002ebd5bc244264732764f

**Document:** 
https://github.com/flutter/website/blob/80151fc9d2dd37eb74002ebd5bc244264732764f/src/codelabs/explicit-animations.md

**Code snippets:** https://github.com/flutter/website/tree/80151fc9d2dd37eb74002ebd5bc244264732764f/examples/animation/explicit

**Includes:**
https://github.com/flutter/website/tree/80151fc9d2dd37eb74002ebd5bc244264732764f/src/_includes/docs/explicit-animations

Closes https://github.com/flutter/website/issues/8057

### CODE REVIEW

**Comment by domesticmouse** [comment]
@johnpryan is looking at pulling the animation code from `flutter/samples` and put it on the website. It'd be worth thinking about this PR in the context of that migration.

**Comment by parlough** [comment]
@johnpryan Have you given any thought to what form that will be in?

**Comment by sfshaza2** [comment]
Are the samples the same?

I agree that we should remove this incomplete codelab. It causes more
confusion than it helps.

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Review by domesticmouse — APPROVED** [review]
We can worry about the samples migration in a follow up PR

**Comment by parlough** [comment]
Sounds good, thanks! 

I'm not completely sure what you are meaning by that work, but I'd be happy to discuss it further! I'm always free for a chat.

**Pull request merged**
