### PR TITLE
null safety check and signature app code

### PR DESCRIPTION
**Pull request by parth5jain**
- Null safety check
-Signature application changes

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
LGTM. Thanks, @parth5jain!

**Comment by sfshaza2** [comment]
@parth5jain, two questions. First, can you sign the CLA? Second, is this PR the same as your other PR? I haven't done a line-by-line comparison, but it looks the same on a quick glance.

**Comment by parth5jain** [comment]
@googlebot I signed it!

**Comment by parth5jain** [comment]
> @parth5jain, two questions. First, can you sign the CLA? Second, is this PR the same as your other PR? I haven't done a line-by-line comparison, but it looks the same on a quick glance.

@sfshaza2 yes I have signed CLA  & I didn't create any other PR with the same code changes

**Pull request merged**
