### PR TITLE
Fix Travis CI for 1.22 stable

### PR DESCRIPTION
**Pull request by johnpryan**

### CODE REVIEW

**Comment by sfshaza2** [comment]
@johnpryan, should I ignore the broken build?

**Comment by johnpryan** [comment]
It looks like `linkcheck` is failing:

```
http://localhost:4002/docs/release/breaking-changes/route-navigator-refactoring
- (450:4) 'Flutter ..' => http://localhost:4002/docs/development/tools/sdk (HTTP 200)
  - redirect path:
    - http://localhost:4002/docs/development/tools/sdk (301)
    - /docs/development/tools/sdk/upgrading (200)
- (461:4) 'Releases' => http://localhost:4002/docs/development/tools/sdk/archive (HTTP 200)
  - redirect path:
    - http://localhost:4002/docs/development/tools/sdk/archive (301)
    - /docs/development/tools/sdk/releases (200)
- (636:4) 'Get star..' => http://localhost:4002/docs/get-started/install/ (HTTP 200)
  - redirect path:
    - http://localhost:4002/docs/get-started/install/ (301)
    - /docs/get-started/install (200)
- (1022:4) 'Flutter ..' => http://localhost:4002/docs/development/tools/sdk (HTTP 200)
  - redirect path:
    - http://localhost:4002/docs/development/tools/sdk (301)
    - /docs/development/tools/sdk/upgrading (200)
- (1033:4) 'Releases' => http://localhost:4002/docs/development/tools/sdk/archive (HTTP 200)
  - redirect path:
    - http://localhost:4002/docs/development/tools/sdk/archive (301)
    - /docs/development/tools/sdk/releases (200)
- (1261:4) 'Navigato..' => http://localhost:4002/go/navigator-with-router (connection failed)
- (1378:6) 'Navigato..' => http://localhost:4002/go/navigator-with-router (connection failed)
```

**Comment by johnpryan** [comment]
@sfshaza2 I think it's a random`linkcheck` failure. I restarted the build but it's probably safe to merge.

**Comment by sfshaza2** [comment]
I suppose we can fix the broken links in another pr...

**Comment by johnpryan** [comment]
It looks like it passed this time.

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Pull request merged**
