### PR TITLE
Add /go/ links section

### PR DESCRIPTION
**Pull request by Hixie**
cc @Sfshaza 

This adds a redirect as discussed. The idea is that in due course we would have many of these.

### CODE REVIEW

**Comment by Hixie** [comment]
I don't understand why the CI failed.

Please feel free to check this in if it's ok.

**Comment by sfshaza2** [comment]
@Hixie, I kicked off the job again, just to make sure it wasn't a glitch. It's failing on the link check, and I'm wondering if:
a) The script doesn't like the comma at the end of the newly added line (which is the last line in the list), or
b) The script doesn't like that the redirect for /go/template doesn't have a corresponding physical file.

I'm also wondering if adding go/template to tool/config/linkcheck-skip-list.txt might be useful here.

**Comment by Hixie** [comment]
I've tried removing the comma.

**Comment by sfshaza2** [comment]
That seemed to fix it! Thanks!

**Pull request merged**
