### PR TITLE
Add next/prev links to cookbook pages

### LINKED ISSUE #1370: Add next/prev links to cookbook pages
@Sfshaza is the order of the entries in the Cookbook significant? If they were presented in alphabetical order would that be ok? /cc @filiph

### PR DESCRIPTION
**Pull request by chalin**
Fixes #1370. All cookbook pages are linked together now, even across sections.

The cookbook page front matter is updated using `tool/next_prev.dart`.

Followup:
- Run `dart tool/next_prev.dart` as part of CI or a pre-commit check #2217

Staged, e.g., see https://flutter-io-staging-2.firebaseapp.com/docs/cookbook

### Screenshot

> screen shot 2019-01-16 at 09 36 08

cc @brianegan

### CODE REVIEW

**Comment by brianegan** [comment]
Overall, LGTM :) One Q: This might lead to duplicating titles across the project. 

Would it be possible to instead grab the `title` from the Front Matter of the file the `path` leads to?

**Comment by chalin** [comment]
> Would it be possible to instead grab the title from the Front Matter of the file the path leads to?

Yes, that is what the script does, https://github.com/flutter/website/pull/2218/files#diff-58c12f72833442c1d9e75ea544afa512R125

**Comment by brianegan** [comment]
Ack, my bad sorry... Missed that section and how the titles were generated.

**Comment by chalin** [comment]
No worries, it was a very valid concern. Thanks for voicing it.

**Comment by chalin** [comment]
This is mainly an infrastructure PR, so I'm going to merge now. @sfshaza2 I can address your concerns, if any, in a followup PR.

**Pull request merged**
