### PR TITLE
Moved splash screen instructions to a page under /development/ui/splash-screen.

### PR DESCRIPTION
**Pull request by matthew-carroll**
Moved splash screen instructions to a page under /development/ui/splash-screen.

### CODE REVIEW

**Comment by matthew-carroll** [comment]
@sfshaza2 do you know where I can specify a redirect so that the old splash screen URL redirects to the new one?

**Comment by legalcodes** [comment]
> @sfshaza2 do you know where I can specify a redirect so that the old splash screen URL redirects to the new one?

If I understand your use case @matthew-carroll you should be able to do that here:
https://github.com/flutter/website/blob/master/firebase.json

**Comment by matthew-carroll** [comment]
Thanks @legalcodes I added a redirect for the URL that I removed.

**Comment by matthew-carroll** [comment]
@sfshaza2 @legalcodes do these changes look good?

**Pull request merged**
