### PR TITLE
Update the options for the gen-l10n tool

### PR DESCRIPTION
**Pull request by TonyD-TuftAndPaw**
_Description of what this PR is changing or adding, and why:_

Adding `use-named-parameters` and `relax-syntax` to the list of options for the `gen-l10n` command.

_Issues fixed by this PR (if any):_

None.

_PRs or commits this PR depends on (if any):_

None.

## Presubmit checklist

- [x] This PR is marked as draft with an explanation if not meant to land until a future stable release.
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Review by sfshaza2 — APPROVED** [review]
Thanks, @TonyD-TuftAndPaw! This looks good.

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Review by domesticmouse — APPROVED** [review]

**Pull request merged**
