### PR TITLE
Missing line added i.e 'appBar: AppBar(' #5170

### LINKED ISSUE #5170: 'Write your first Flutter app, part 1' page issue
Page URL: https://flutter.dev/docs/get-started/codelab.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab.md

Description of issue:
Codes in Step 2 & 3 missing AppBar things. I couldn't run the code without it.

### PR DESCRIPTION
**Pull request by AdityaBirangal**
Fix issue #5170 - 'Write your first Flutter app, part 1' page issue

### CODE REVIEW

**Review by sfshaza2 — COMMENTED** [review]
@miquelbeltran, if you are addressing this issue, please close this PR.  Thx!

**Comment by miquelbeltran** [comment]
I will look into it, but I think this issue is caused by the automatic code-excerpt extraction and should not be fixed manually but rather fixing the code-excerpt importing issue.

**Review by sfshaza2 — COMMENTED** [review]
@miquelbeltran, can you verify this change? If not, I will close the PR.  thx

**Comment by sfshaza2** [comment]
Thanks for that info. I am closing this PR.

**Pull request closed without merging**
