### PR TITLE
Fix typo: dev_deperencies to dev_dependencies

### PR DESCRIPTION
**Pull request by LucaDorinAnton**
Fix simple typo in the **mocking.md** cookbook.

### CODE REVIEW

**Comment by LucaDorinAnton** [comment]
@googlebot I signed it!

**Review by sfshaza2 — APPROVED** [review]
Good catch! Thx!

**Comment by sfshaza2** [comment]
I can't look at it right now, but this is breaking the build for some reason.

**Review by sfshaza2 — APPROVED** [review]
OK, I've looked and this is not a true CI build failure. LGTM

**Pull request merged**
