### PR TITLE
Trim lines' end when extracting code snippets

### PR DESCRIPTION
**Pull request by rock3r**
~This allows us to avoid trailing whitespace, and fixes cases where, for example, we have empty spaces after comments that prevent the code from finding the end of the comment, causing the code to run to the end of the file and failing with an index-out-of-bounds error.~

~For example:~

```markdown
...

<!-- skip --> 
{% prettify dart %}
void main() {
  runApp(new SampleApp());
}
{% endprettify %}
```

~(notice the extra whitespace at the end of the comment line)~

~Would fail the build.~

~This PR hot-fixes that issue, although a more robust error handling should eventually be built into the code so that whenever a comment is left open there's a proper error message pointing at a line number, and explaining the issue.~

EDIT: see [comment below](https://github.com/flutter/website/pull/983#issuecomment-385158897)

### CODE REVIEW

**Comment by rock3r** [comment]
Update: after #968 has been merged, the fix proper is not needed anymore as @brianegan had incorporated it himself. This PR now is basically just running `dartfmt` on `tools/extract.dart`

**Comment by Sfshaza** [comment]
Hi, @rock3r! I'm a little unclear. I can close this PR, since Brian made it unnecessary? Or you want to modify the PR to mention dartfmt?  thx

**Comment by rock3r** [comment]
@sfshaza there is some reformatting left here, but feel free to close it if there's no value for you.

**Comment by Sfshaza** [comment]
OK, thanks. Closing.

**Pull request closed without merging**
