### PR TITLE
Update windows.md

### PR DESCRIPTION
**Pull request by ArkyTech-Inc**
added a full stop on line 17

### CODE REVIEW

**Comment by ArkyTech-Inc** [comment]
@googlebot I signed it!

**Review by sfshaza2 — APPROVED** [review]
You get points for consistency in the list but, actually, none of these items are complete sentences, so they really shouldn't have punctuation. But... LGTM

**Comment by ArkyTech-Inc** [comment]
Thank you for the clarification. Appreciate it.

**Review by sfshaza2 — CHANGES_REQUESTED** [review]
Hi, @ArkyTech-Inc! You are right that there is an error in this list, but your fix is not correct. The punctuation on a list _should_ be parallel, but are not in this list (and sublist). In this case, these are not full sentences, so they shouldn't have punctuation. So, I'd remove the periods, not add more.

You can see the rule in the [Google developer documentation style guide](https://developers.google.com/style/lists?hl=en#parallel-syntax). I'll leave this PR open so you can decide if you want to update it, otherwise I'll close.

**Review by sfshaza2 — APPROVED** [review]
LGTM

**Pull request merged**
