### PR TITLE
Column widget in FinishedPage and WaitingPage has been wrapped by Sing…

### LINKED ISSUE #11220: broken demo
### Page URL

https://docs.flutter.dev/cookbook/effects/nested-nav/

### Page source

https://github.com/flutter/website/tree/main/src/content/cookbook/effects/nested-nav.md

### Describe the problem

tried the demo and got an error  "Another exception was thrown: A RenderFlex overflowed by 64 pixels on the bottom."

### Expected fix

_No response_

### Additional context

_No response_

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

### PR DESCRIPTION
**Pull request by tbansod2018**
…leChildScrollView to avoid overflow

_Description of what this PR is changing or adding, and why:_
Column Widget in FinishedPage and WaitingPage has been wraped by SingleChildScrollView to avoid overflow.

_Issues fixed by this PR (if any):_ Fixes #11220

_PRs or commits this PR depends on (if any):_

## Presubmit checklist

- [x] This PR is marked as draft with an explanation if not meant to land until a future stable release.
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

### CODE REVIEW

**Comment by sfshaza2** [comment]
@tbansod2018, the test check is failing. If you click on the Details, it asks you to run ./dash_site refresh-excerpts to make sure the code excerpts are up to date.

@ericwindmill, I've confirmed that the DartPad example works on https://flutter-docs-prod--pr11247-main-gdgm6ks7.web.app/cookbook/effects/nested-nav, but can you review the code?

**Comment by ericwindmill** [comment]
@tbansod2018 The code looks good. But as @sfshaza2 said, you need to update the excerpts with the `./dash_site refresh-excerpts` command.  [README](https://github.com/flutter/website?tab=readme-ov-file#refresh-code-excerpts)

**Review by ericwindmill — CHANGES_REQUESTED** [review]
@tbansod2018 The code looks good. But as @sfshaza2 said, you need to update the excerpts with the `./dash_site refresh-excerpts` command.  More details are in the [README](https://github.com/flutter/website?tab=readme-ov-file#refresh-code-excerpts)

**Review by parlough — APPROVED** [review]
Thanks for the PR and fixing this! I reapplied your changes as it looks like they went missing when you merged with main or refreshed the excerpts. Note that refreshing excerpts takes the `.dart` files from the `code-excerpt` instructions as the source of truth.

I also pushed a commit to reduce the size of the lightbulbs to fit on more screen sizes without always relying on the scrolling.

Thanks again :)

**Comment by parlough** [comment]
@ericwindmill Can you give this PR another look or dismiss your request for changes? Thanks!

**Review by ericwindmill — APPROVED** [review]
LGTM

**Comment by parlough** [comment]
Thanks everyone! 🚀

**Pull request merged**
